### ISSUE TITLE
Add public Service methods to add/update/remove DeviceProfiles

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#10]
Add public Service methods to allow a device service to dynamically add/update or remove DeviceProfile objects. The operations result in changes to Core Metadata in addition to the device service's local DeviceProfile objects.

**Estimated effort**: 2-3d

**Comment by weichou1229** [comment]
@tonyespy I will work on this issue.

**Comment by cloudxxx8** [comment]
fixed by #74
