### ISSUE TITLE
Use sdk to create new device service, need create new device profile, could support value list in resource properties?

### ISSUE THREAD

**Issue by zhui19871** [edgexfoundry/device-sdk-go#1006]
# 🚀 Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
please fill out the issue template and state your question clearly

**Comment by cloudxxx8** [comment]
close this issue due to no response
please reopen it when you have detailed information about this issue
