### ISSUE TITLE
Cannot run docker build images

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/device-sdk-go#1019]
hi , I want to build a device-simple image.
I referred to [this](https://docs.edgexfoundry.org/2.0/getting-started/Ch-GettingStartedSDK-Go/),and i successfully built an image, but it failed to start.
`ERROR: for edgex-device-simple  Cannot start service device-simple: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/device-simple": permission denied: unknown`
I thought maybe there was something wrong with the configuration. 
This is my Dockerfile:
```
ARG BASE=golang:1.16-alpine3.12
FROM ${BASE} AS builder

WORKDIR /device-sdk-go

LABEL license='SPDX-License-Identifier: Apache-2.0' \
  copyright='Copyright (c) 2020: Intel'

RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories

RUN apk add --update --no-cache make git gcc libc-dev zeromq-dev libsodium-dev

COPY . .

ENV GOPROXY="https://goproxy.cn"
ENV GO111MODULE=on

RUN go mod download

RUN make build

FROM alpine:3.12
LABEL license='SPDX-License-Identifier: Apache-2.0' \
  copyright='Copyright (c) 2020: Intel'

RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories
RUN apk add --update --no-cache zeromq

WORKDIR /

COPY ./cmd/device-simple/Attribution.txt /Attribution.txt
COPY ./cmd/device-simple/ /device-simple
COPY ./cmd/device-simple/res/ /res

EXPOSE 59999

ENTRYPOINT ["/device-simple"]
CMD ["-cp=consul.http://127.0.0.1:8500", "--registry", "--confdir=/res"]
```

Please take a look. Thank you very much！

**Comment by cloudxxx8** [comment]
are you able to run in pure device-simple binary without dockerize?

**Comment by FengZeHe** [comment]
> are you able to run in pure device-simple binary without dockerize?

Yes. It's kind of weird. And sometimes I need to execute `export EDGEX_SECURITY_SECRET_STORE=false`.
![image](https://user-images.githubusercontent.com/25740210/135020549-e355d35d-8395-446d-96d9-852557049766.png)

**Comment by FengZeHe** [comment]
I changed the permissions on the file but it still doesn't work.
![image](https://user-images.githubusercontent.com/25740210/135038275-2f61d951-3642-4699-9aee-c2a3d603438f.png)

**Comment by FengZeHe** [comment]
@cloudxxx8 I haven't solved this problem yet please give me some help. Thank you very much!
The situation is that this error is displayed every time the build is run after the image.And i tried a lot of things but I couldn't find a solution.
![image](https://user-images.githubusercontent.com/25740210/140480980-274d0de7-7d97-4285-8195-a96acfb0ed59.png)

This is my dockerfile, please help to have a look. Thank you very much!

ARG BASE=golang:1.16-alpine3.14
FROM ${BASE} AS builder

ENV GO111MODULE=on
ENV GOPROXY="https://goproxy.cn"

ARG MAKE=make build
WORKDIR /device-sdk-go

LABEL license='SPDX-License-Identifier: Apache-2.0' \
  copyright='Copyright (c) 2020: Intel'

RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories

RUN apk add --update --no-cache make git gcc libc-dev zeromq-dev libsodium-dev

COPY . .
RUN [ ! -d "vendor" ] && go mod download all || echo "skipping..."

RUN ${MAKE}

FROM alpine:3.14
LABEL license='SPDX-License-Identifier: Apache-2.0' \
  copyright='Copyright (c) 2020: Intel'

RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories

RUN apk add --update --no-cache zeromq

WORKDIR /
COPY ./cmd/device-simple/Attribution.txt /Attribution.txt
COPY ./cmd/device-simple/device-simple /device-simple
COPY ./cmd/device-simple/res/ /res

EXPOSE 59995
ENV  EDGEX_SECURITY_SECRET_STORE=false
ENTRYPOINT ["./device-simple"]
CMD ["-cp=consul.http://172.16.4.151:8500", "--registry", "--confdir=/res"]`

**Comment by cloudxxx8** [comment]
did you build and run the docker image on the same machine or different machine?

**Comment by cloudxxx8** [comment]
your entrypoint is `./device-simple`
could you try to use `/device-simple`?

**Comment by FengZeHe** [comment]
> did you build and run the docker image on the same machine or different machine?

Thank you for your reply! I build and run the docker image on the same machine.
And i use entrypoint `/device-simple`, but error still displayed.
![image](https://user-images.githubusercontent.com/25740210/140697545-a56f9365-b0d7-4399-b8b7-a86b9bd7592b.png)

**Comment by FengZeHe** [comment]
Problem solved... It worked with a different machine. Thank you! @cloudxxx8
