### ISSUE TITLE
Device profile not loaded in cache if device for profile doesn't exist

### ISSUE THREAD

**Issue by marcpfuller** [edgexfoundry/device-sdk-go#1053]
# 🐞 Bug Report

### Description and Minimal Reproduction
Run migrated LLRP device service, which uses provision watcher and no static devices
https://github.com/marcpfuller/device-rfid-llrp-go

*note in logs that provision watcher failed to add due to profile not found in cache

you can see in the code link below that it is loaded by device
https://github.com/edgexfoundry/device-sdk-go/blob/main/internal/cache/init.go#L37-L45

Here shows that the provision watcher is trying to get to the profile via the cache
https://github.com/edgexfoundry/device-sdk-go/blob/main/pkg/service/managedwatchers.go#L31

## 🔥 Exception or Error
<pre><code>
level=DEBUG ts=2021-11-04T21:43:33.10203Z app=edgex-device-rfid-llrp source=driver.go:720 msg="2 provision watcher files found"
level=DEBUG ts=2021-11-04T21:43:33.1020664Z app=edgex-device-rfid-llrp source=driver.go:725 msg="processing res/provision_watchers/impinj.provision.watcher.json"
level=ERROR ts=2021-11-04T21:43:33.1023475Z app=edgex-device-rfid-llrp source=managedwatchers.go:61 msg="failed to find ProvisionWatcher llrp-impinj-provision-watcher in cache"
level=INFO ts=2021-11-04T21:43:33.1024189Z app=edgex-device-rfid-llrp source=driver.go:750 msg="Adding provision watcher:llrp-impinj-provision-watcher"
level=ERROR ts=2021-11-04T21:43:33.1024522Z app=edgex-device-rfid-llrp source=managedwatchers.go:34 msg="device profile LLRP-Impinj-Profile doesn't exist for provision watcher llrp-impinj-provision-watcher"
level=DEBUG ts=2021-11-04T21:43:33.1024818Z app=edgex-device-rfid-llrp source=driver.go:725 msg="processing res/provision_watchers/llrp.provision.watcher.json"
level=ERROR ts=2021-11-04T21:43:33.10262Z app=edgex-device-rfid-llrp source=managedwatchers.go:61 msg="failed to find ProvisionWatcher llrp-provision-watcher in cache"
level=INFO ts=2021-11-04T21:43:33.102658Z app=edgex-device-rfid-llrp source=driver.go:750 msg="Adding provision watcher:llrp-provision-watcher"
level=ERROR ts=2021-11-04T21:43:33.1026816Z app=edgex-device-rfid-llrp source=managedwatchers.go:34 msg="device profile LLRP-Device-Profile doesn't exist for provision watcher llrp-provision-watcher"
level=ERROR ts=2021-11-04T21:43:33.1027245Z app=edgex-device-rfid-llrp source=driver.go:816 error="error adding provision watcher llrp-impinj-provision-watcher: device profile LLRP-Impinj-Profile doesn't exist for provision watcher llrp-impinj-provision-watcher; error adding provision watcher llrp-provision-watcher: device profile LLRP-Device-Profile doesn't exist for provision watcher llrp-provision-watcher" msg="Error adding provision watchers. Newly discovered devices may fail to register with EdgeX."
level=DEBUG ts=2021-11-04T21:43:33.1028128Z app=edgex-device-rfid-llrp source=discover.go:120 msg="total estimated network probes: 508, async limit: 508, probe timeout: 2s, total estimated time: 2s"
</code></pre>

## 🌍  Your Environment
**EdgeX Version:**
Ireland and Jakarta WIP

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@cloudxxx8 , this change Ireland. In Hanoi the code that checked Metadata for the profile (add pushing if not found) was putting the profile in the cache.
