### ISSUE TITLE
When my auto-discovery device push into device Channel, but cache.ProvisionWatchers() have nothing.

### ISSUE THREAD

**Issue by Haoyuli1990** [edgexfoundry/device-sdk-go#1086]
https://github.com/edgexfoundry/device-sdk-go/blob/010109ac27d0c5bf83524e8a72dc5fbfafcc8fd1/pkg/service/async.go#L93

When my auto-discovery device push into deviceCh, but pws := cache.ProvisionWatchers().All() length is 0, 
what is ProvisionWatchers? 
How do I get values in the cache.ProvisionWatchers().All() ？

**Comment by hahattan** [comment]
For reference of ProvisionWatcher: 
https://docs.edgexfoundry.org/2.0/design/legacy-design/device-service/discovery/#filtered-device-addition

To add a ProvisionWatcher you can use Metadata API:
https://app.swaggerhub.com/apis/EdgeXFoundry1/core-metadata/2.0.0#/default/post_provisionwatcher

**Comment by Haoyuli1990** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Haoyuli1990** [comment]
@hahattan ok, you mean that I must add a ProvisionWatcher via restPOST before device auto-discovery?
Does edgex UI have some function to add ProvisionWatcher to core-matedata ?

**Comment by cloudxxx8** [comment]
there is a ProvisionWatcher tab on UI.  you can give it a try.
https://github.com/edgexfoundry/edgex-ui-go

**Comment by cloudxxx8** [comment]
and yes, you have to create ProvisionWatcher before triggering AutoDiscovery, and the Device Service will know which Device Profile should be adopted

**Comment by Haoyuli1990** [comment]
@cloudxxx8 OK, I get it. thanks a lot!
