### ISSUE TITLE
schedule and event need to be removed from DS sending Event/Reading

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-sdk-go#110]
The schedule and event fields should not be in the Event/Reading sent from a Device Service (these are mistakes from the early Go model work).  Here is an example of the Event/Reading message that includes these two null fields that should be removed:  [{"id":"5be7a0d80e360800019dbd26","pushed":0,"device":"RandNum-Device01","created":1541906648020,"modified":0,"origin":1541906648017,"schedule":null,"event":null,"readings":[{"id":"5be7a0d80e360800019dbd27","pushed":0,"created":1541906648020,"origin":1541906648017,"modified":0,"device":"RandNum-Device01","name":"Random","value":"6"}]}

this is for Edinburgh release - not clean up that is needed for Delhi or Delhi Dot

**Comment by cloudxxx8** [comment]
@jpwhitemn For this issue, I am not sure there is anything Device Service SDK can do.
We might need to open this issue in edgex-go repository to remove those two fields in the model.
If you think so, I can help open and fix this issue in edgex-go repository.
Thanks.

**Comment by jduranf** [comment]
I agree with @cloudxxx8. This is a edgex-go issue, which is [already created](https://github.com/edgexfoundry/edgex-go/issues/314) by @tonyespy.

**Comment by jduranf** [comment]
@jpwhitemn, I created the PR [789](https://github.com/edgexfoundry/edgex-go/pull/789) in edgex-go in order to fix this issue.

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/pull/789
