### ISSUE TITLE
lastReported of device not populated

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-sdk-go#1151]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
all device services

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
The lastReported timestamp on devices is not populating.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by jpwhitemn** [comment]
Covered in Core WG of 5/5/22.  Topic to be covered in Levski Planning Meeting

**Comment by iain-anderson** [comment]
Decision in Levski planning meeting that this will not be implemented. Instead the last read or write interaction with a device will be provided via metrics, and other device interactions (eg disconnect, re-connect) will be reported in control plane events
