### ISSUE TITLE
Bootstrap checks the unnecessary service when startup

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#1157]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in:  device service

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
Deploy EdgeX without core-data service
1. Run docker-compose up with the attached compose file [docker-compose-no-secty.txt](https://github.com/edgexfoundry/go-mod-bootstrap/files/8638551/docker-compose-no-secty.txt)
2. Inspect the logs to see the error 

## 🔥 Exception or Error
```
$ docker logs edgex-device-virtual
level=INFO ts=2022-05-06T08:09:57.1401603Z app=device-virtual source=config.go:391 msg="Loaded service configuration from /res/configuration.toml"
level=INFO ts=2022-05-06T08:09:57.143074Z app=device-virtual source=variables.go:352 msg="Variables override of 'Service.Host' by environment variable: SERVICE_HOST=edgex-device-virtual"
...
level=INFO ts=2022-05-06T08:10:08.5731585Z app=device-virtual source=init.go:152 msg="Check core-metadata service's status via Registry..."
level=INFO ts=2022-05-06T08:10:08.5788327Z app=device-virtual source=init.go:54 msg="Service clients initialize successful."
level=WARN ts=2022-05-06T08:10:08.5797848Z app=device-virtual source=clients.go:137 msg="unable to Get service endpoint for 'core-data': no matching service endpoint found. retrying..."
level=WARN ts=2022-05-06T08:10:09.5832072Z app=device-virtual source=clients.go:137 msg="unable to Get service endpoint for 'core-data': no matching service endpoint found. retrying..."
level=WARN ts=2022-05-06T08:10:10.5850074Z app=device-virtual source=clients.go:137 msg="unable to Get service endpoint for 'core-data': no matching service endpoint found. retrying..."
level=WARN ts=2022-05-06T08:10:11.5867834Z app=device-virtual source=clients.go:137 msg="unable to Get service endpoint for 'core-data': no matching service endpoint found. retrying..."
level=WARN ts=2022-05-06T08:10:12.5915349Z app=device-virtual source=clients.go:137 msg="unable to Get service endpoint for 'core-data': no matching service endpoint found. retrying..."
level=WARN ts=2022-05-06T08:10:13.5961904Z app=device-virtual source=clients.go:137 msg="unable to Get service endpoint for 'core-data': no matching service endpoint found. retrying..."
```

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

main branch

**Anything else relevant?**

The user might don't need to deploy the core-data, but the device service still needs to keep the core-data client config. When deploying the EdgeX, the bootstrap blocks the device service with endpoint checking.
This issue can refer to https://github.com/edgexfoundry-holding/device-onvif-camera/issues/56

**Comment by lenny-intel** [comment]
Need to add conditional around this check so only required when NOT using the MessageBus

**Comment by cloudxxx8** [comment]
ok, we should remove the check from sdk and the notification client check in core-metadata
@weichou1229 please help check and modify them

**Comment by cloudxxx8** [comment]
I just noticed this issue has been moved to sdk, reopening the issue
