### ISSUE TITLE
Convert DeviceService into an interface that can be easily mocked and unit tested

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#1168]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

https://github.com/edgexfoundry/device-sdk-go/blob/c4c7375013d1152251e98051bf37b0c1fd0193e8/pkg/service/service.go#L60-L81

### Description [**REQUIRED**]

Convert `DeviceService` into an interface that can be easily mocked and unit tested.

### Describe alternatives you've considered

Creating custom wrapper interfaces on a per device service level.

**Comment by cloudxxx8** [comment]
that's a breaking change, and we can't make this change until next major release

**Comment by lenny-intel** [comment]
> 

@cloudxxx8 , I think it could be done in an `alternative` manner so that it is not breaking. Make the current way as Deprecated and remove it in Edgex 3.0.

**Comment by cloudxxx8** [comment]
@lenny-intel this public function should return the interface instead of the struct, so I thought it's a breaking change
https://github.com/edgexfoundry/device-sdk-go/blob/c4c7375013d1152251e98051bf37b0c1fd0193e8/pkg/service/service.go#L244-L247

**Comment by lenny-intel** [comment]
@cloudxxx8 , yes that would have to stay the same. 
What I am proposing is adding new function, say `Service()` , that returns the interface.
 ```
//  Service returns the Service instance which is running as an interface
 func Service() DeviceServiceInterface { 
 	return ds 
 } 
```

**Comment by cloudxxx8** [comment]
I see.  This can work.

**Comment by hahattan** [comment]
Do you think we can refactor device-sdk in 3.0 to be more like app-sdk ?
For example a factory function to return the `DeviceService` interface ?

**Comment by lenny-intel** [comment]
Yes, that would be a good improvement. Get rid of the global instance.
