### ISSUE TITLE
Implement command API via message bus

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-go#1173]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for... device-sdk-go

### Description [**REQUIRED**]
 Implement N/S message bus as per ADR 0023

### Describe the solution you'd like
SDK to subscribe to internal messagebus channels as detailed in the ADR, and receive device requests from them.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by iain-anderson** [comment]
@hahattan  is this closed by https://github.com/edgexfoundry/device-sdk-go/pull/1212 and subsequent fixes?

**Comment by hahattan** [comment]
Yes #1189 is duplicate of this issue and both are addressed in #1212 and subsequent fixes
