### ISSUE TITLE
Device profile versioning and or updating

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#1191]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
device-sdk-go

### Description [**REQUIRED**]
Right now on startup the SDK checks if the device profiles exist, and if not ingests them into core-metadata. The problem occurs when the device service updates the device profile yaml file, those changes are not reflected in core-metadata unless the user manually updates them.

### Describe the solution you'd like
When the device service starts up, it checks a version number or hash to see if the device profile has been updated, and if so, it should update core-metadata.

Caveats: If the user modifies the device-profile through core-metadata directly, we would want to be able to know that and not clobber their changes. Unfortunately this is probably why the system already works the way it does.

### Describe alternatives you've considered
- Instruct the user how to manually push the updated profile
- Publish the new profile under a different name (say, profile_blah-v2) to avoid conflicts (assuming the existing startup profile check is on a per-profile basis), and migrate the devices to use the newer profile.

**Comment by cloudxxx8** [comment]
@ajcasagrande it is as our design.  the auto provisioning feature is designed for the developer easily testing.  users should use core-metadata to manage devices and device profiles.
you can write a script to create or update devices and profiles outside of device services.  that's the design decision we made.
