### ISSUE TITLE
fail to invoke device service callback for adding device Simple-Device01, err: failed to send a http request -> Post \"http://localhost:59999/api/v2/callback/device\": dial tcp 127.0.0.1:59999: connect: connection refused

### ISSUE THREAD

**Issue by tntthanh** [edgexfoundry/device-sdk-go#1199]
I got this ERROR when run the executable file of the example provided that it do not instantly update new device that I provisioned via core-metadata, but I need to re-run manually the executable file to update that new device.

The log of the error I met:
level=ERROR ts=2022-07-25T04:47:13.904241164Z app=core-metadata source=notify.go:53 msg="fail to invoke device service callback for adding device Simple-Device01, err: failed to send a http request -> Post \"http://localhost:59999/api/v2/callback/device\": dial tcp 127.0.0.1:59999: connect: connection refused"

**Comment by cloudxxx8** [comment]
what is your environment? are you running core services in container or device service in container?
it's a network issue. you need to define the device service ip address properly in the configuration- Service.Host
if you run the core services in docker and device service in binary (running in host), Service.Host should be docker0 ip on your host, such as 172.17.0.1

**Comment by tntthanh** [comment]
@cloudxxx8 
Okay! I had got it solved! Thank you very much!

**Comment by Vincent990413** [comment]
> @cloudxxx8 Okay! I had got it solved! Thank you very much!

I'm sorry, but can you give me the code of your configuration? I've also encountered this problem.
