### ISSUE TITLE
Implement private device struct

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#12]
Implement a new private device struct which encapsulates the public [Device](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/device.go) object imported from edgex-go.  This new struct can then include a mutex which can be used to prevent a Device from being removed while operations involving it are in-progress.

**Estimated effort**: 3d

**Comment by cloudxxx8** [comment]
fixed by #74
