### ISSUE TITLE
CommandRequestTopic in the example misses the device service name

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#1219]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-simple

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]

https://github.com/edgexfoundry/device-sdk-go/blob/32167e186cd280efad328d3bc9a5f43c05eae3ff/example/cmd/device-simple/res/configuration.toml#L70

It should be "edgex/command/request/device-simple/#"

**Comment by hahattan** [comment]
resolved in #1220
