### ISSUE TITLE
Put command with wrong parameter name should return 400 error

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#123]
In the current implementation, the wrong parameter name in put command would return 200 OK with a warn log.  The 400 bad request error should be returned to client

https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/handler/command.go#L284

**Comment by tonyespy** [comment]
My vote would be to bump the priority on this one, as otherwise our API is not behaving correctly. I think this should be fixed for Edinburgh.

**Comment by SteveOss** [comment]
Agree, is a bug, should be fixed.

**Comment by cloudxxx8** [comment]
fixed by #211
