### ISSUE TITLE
Device set command should return BaseResponse

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-sdk-go#1233]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-sdk-go

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
Send device set command via external MQTT

## 🔥 Exception or Error
<pre><code>
{"ReceivedTopic":"edgex/device/command/response/device-simple/Simple-Device01/Xrotation/set","CorrelationID":"14a42ea6-c394-41c3-8bcd-a29b9f5e6835","ApiVersion":"v2","RequestID":"e6e8a2f4-eb14-4649-9e2b-175247911369","ErrorCode":0,"Payload":null,"ContentType":"application/json","QueryParams":{}}
</code></pre>

The response payload should contain BaseResponse not null

## 🌍  Your Environment
**Deployment Environment:**
MacOS

**EdgeX Version [**REQUIRED**]:**
latest

**Anything else relevant?**

**Comment by lenny-intel** [comment]
Per the ADR, it should return nil Payload with ErrorCode = 0.

**Comment by hahattan** [comment]
Closing this issue as current behavior is expected
