### ISSUE TITLE
Return BaseResponse in response envelope when ds-returnevent=no for command request via messaging

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-sdk-go#1235]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for device-sdk-go

### Description [**REQUIRED**]
Related to https://github.com/edgexfoundry/go-mod-messaging/issues/177  
while doing the initial implementataion of the `IssueGetCommandByName(ctx context.Context, deviceName string, commandName string, dsPushEvent string, dsReturnEvent string) (*responses.EventResponse, errors.EdgeX)`
If there's no response from device-service, it's hard for the CommandClient to determine whether the request succeeded or the request(response) timed out

### Describe the solution you'd like
Return BaseResponse (instead of EventResponse) in the response envelope

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by hahattan** [comment]
@lenny-intel any thought on this ?
discussed with @cloudxxx8 and this might be the easiest solution right now (althought it might cause slight difference between REST API and messaing API)

**Comment by lenny-intel** [comment]
I thought in the ADR we specified that the device service would still publish a response in this case with `ErrorCode=0`, but the payload would be empty. 

Command Client APIs should have a timeout on receiving the response.
