### ISSUE TITLE
type string has no field or method Hex

### ISSUE THREAD

**Issue by wangnuannuan** [edgexfoundry/device-sdk-go#125]
I get this repo by run `go get github.com/edgexfoundry/device-sdk-go` , Then run 'make build', it raise the error:
```
CGO_ENABLED=0 go build -o example/cmd/device-simple/device-simple ./example/cmd/device-simple
# github.com/edgexfoundry/device-sdk-go/internal/cache
internal/cache/valuedescriptors.go:54:25: descriptor.Id.Hex undefined (type string has no field or method Hex)
internal/cache/valuedescriptors.go:59:34: descriptor.Id.Hex undefined (type string has no field or method Hex)
internal/cache/valuedescriptors.go:79:25: vd.Id.Hex undefined (type string has no field or method Hex)
internal/cache/valuedescriptors.go:90:16: vd.Id.Hex undefined (type string has no field or method Hex)
Makefile:13: recipe for target 'example/cmd/device-simple/device-simple' failed
make: *** [example/cmd/device-simple/device-simple] Error 2
```

**Comment by cloudxxx8** [comment]
@wangnuannuan 
edgex-go just replaced BSON id format as UUID.  We will modify device-sdk-go accordingly.
Could you please run with delhi branch for now?  Or modify glide.yml to build with the delhi branch of edgex-go.  Thanks.

**Comment by jduranf** [comment]
@wangnuannuan before run `make build` you should run `make prepare`
@cloudxxx8 you are right, but glide.yml already it's using delhi branch

**Comment by wangnuannuan** [comment]
The package `cache`, import the `github.com/edgexfoundry/edgex-go/pkg/models`. And the Descriptor Struct
```
type ValueDescriptor struct {
	Id           string      `json:"id"`
	Created      int64       `json:"created"`
	Description  string      `json:"description"`
	Modified     int64       `json:"modified"`
	Origin       int64       `json:"origin"`
	Name         string      `json:"name"`
	Min          interface{} `json:"min"`
	Max          interface{} `json:"max"`
	DefaultValue interface{} `json:"defaultValue"`
	Type         string      `json:"type"`
	UomLabel     string      `json:"uomLabel"`
	Formatting   string      `json:"formatting"`
	Labels       []string    `json:"labels"`
}
```
Id is a string
In `edgex-go`, I run `make run`, there is no error.

**Comment by wangnuannuan** [comment]
@cloudxxx8 
I checkout branch delhi, and there is no error. Thank you.

**Comment by cloudxxx8** [comment]
@jduranf thanks, I just noticed that, and I will modify it to master in master branch.
@wangnuannuan Id was BSON Id, and it was just modified to pure string recently.  We will make a change to fit the new design soon.  Thanks for reporting this issue.

**Comment by wangnuannuan** [comment]
I see the repo `edgexfoundry/device-mqtt-go`. In this repo, you use mqtt client in the driver, so the hardware device is mqtt server. If  i want add multiple hardware devices, I need to create multiple drivers. Beacuse each server has a different port, and each mqtt client can only subscribe one server. Why don't you use MQTT borker in driver. This allows you to add devices dynamically.

**Comment by cloudxxx8** [comment]
@wangnuannuan please open an issue on device-mqtt-go repository for any suggestion.  This is an irrelevant topic to this issue.  We noticed that the current design of device-mqtt-go is not flexible, but we made it as the initial release for simplicity.  It could be improved gradually.
