### ISSUE TITLE
Add isVirtual property to DeviceResources model, for Resources that do not originate in south-bound device data

### ISSUE THREAD

**Issue by TomBrennan-Eaton** [edgexfoundry/device-sdk-go#1272]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
This feature request is for core-metadata's model of DeviceResources, and its use in the Device SDKs when handling GET and PUT  /device/name/{device}/{command} APIs.

### Description [**REQUIRED**]
We have identified a need for upper level services (ie, Analytics, north-bound, or UI) to be able to extend the set of Device Resources of a Device created in a south-bound Device Handler service. These upper-level services need to add new Resources that the south-bound service must host but is otherwise not concerned with the contents; we are proposing that these be called "Virtual Resources", and that they be identified by a new property in the DeviceResources model (isVirtual) when it is set to True. 

A Virtual Resource is expected to be managed by an upper-level service and not by the south-bound service. We see this as very valuable when the upper-level services extend the data related to a given Device by configuration related to those services or output from, eg, an Analytics service that creates new Resource data that is related to the Device. As an example, a cloud app service might add a Cadence resource for a Device's data; by putting this data in the set of Device Resources at the south-bound Device, it makes it available to other services, such as the local UI, and makes its relationship to the overall Device data clear.

This feature request is part of the solution for the [UCR for Extending Device Data](https://github.com/edgexfoundry/edgex-docs/blob/main/docs_src/design/ucr/Extending-Device-Data.md).

The flow that I anticipate for this would be

1. An upper-level service discovers the Device, and determines that it wants to extend its Device Resources by adding one or more.
2. This upper-level service updates the south-bound Device's Device Profile to add the new Resources (if they are not already present), setting the isVirtual property to True.
3. The south-bound service allocates for the new Resources; if they have a defaultValue property, it uses that; otherwise they should be  Null.
4. The upper-level service provides the values for these Resources using the core-command's PUT /device/name/{device}/{command}, ideally also setting its [new ds-pushevent field](https://github.com/edgexfoundry/device-sdk-go/issues/1271) to True.
5. Subsequent GET and PUT commands are directed to the south-bound service, and it simply provides or updates its copy of the Resources accordingly.

### Describe the solution you'd like
Core-metadata will extend the model for DeviceResources to add the new isVirtual property, which will be False by default.

The Device SDKs will be enhanced to work with this isVirtual property to instantiate the Resource(s) and support them for GET and PUT /device/name/{device}/{command} commands.

### Describe alternatives you've considered
Previously in the TSC meetings, we discussed putting these extended Resources at the upper-level service and getting core-command to associate them with the south-bound device but yet direct the commands for them to the upper-level service. However, besides the additional complexity for core-command, this approach had difficulties linking the extended Resources (particularly their metadata) to the south-bound device that they were associated with. The proposed approach here simplifies that problem by centralizing the data in one location, the south-bound Device, making it a true composite Twin Device.

**Comment by TomBrennan-Eaton** [comment]
This approach was discussed in today's Device Services working group meeting, and recommended as being likely to be of general interest.

**Comment by cloudxxx8** [comment]
I plan to add a new extendable field `Others` in the `resourceProperties`, and it will be a key/value map, and I will bring this topic to the next Core WG meeting.
https://github.com/edgexfoundry/go-mod-core-contracts/issues/770#issuecomment-1386128917

@TomBrennan-Eaton Do you think it's possible to use `DeviceResource.Properties.Others["isVirtual"]` to fulfill your requirement?  In this way, you can add more resource properties in `Others`.

**Comment by iain-anderson** [comment]
@TomBrennan-Eaton the above is now implemented - does this fulfill the requirement here?

**Comment by lindseysimple** [comment]
Based on the discussion in the Device WG meeting on January 30, 2024, this solution is no longer needed from Eaton. 

Since there's no other requirement for this feature from the community, closing this issue.
