### ISSUE TITLE
Add resource, command, and device tags to reading/event

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/device-sdk-go#1294]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 device-sdk

### Description [**REQUIRED**]
Based on https://github.com/edgexfoundry/go-mod-core-contracts/issues/767
Device, device resource, and device command now have the `Tags map[string]interface{}` field that allows users to provide additional information. device-sdk should add these tags to reading/event.
### Describe the solution you'd like
Before sending out an event, do the following:
1. Add device resource tags in reading level
2. Add device command tags in event level
3. Add device tags in event level

The device tags should take precedence over the device command tags if the tag name is the same.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by TomBrennan-Eaton** [comment]
What's the "Why?" here? Why put the tags in every Event, when they are available in metadata?
Event size is always a concern, though the contribution from Tags appears to be small.
