### ISSUE TITLE
Remove UseMessageBus config in 3.0

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/device-sdk-go#1296]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for...
all device services

### Description [**REQUIRED**]
 
The message bus is always used after 3.0

### Describe the solution you'd like
 
remove the config `UseMessageBus`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
The reason we brought up this issue is that, if useMessageBus is false, the System Events callback will not be received

**Comment by lenny-intel** [comment]
> The reason we brought up this issue is that, if useMessageBus is false, the System Events callback will not be received

Makes sense, but it also has the side effect of not allowing the old way of POSTing Events via REST (which is ok IMO). So that code need to also be removed.
