### ISSUE TITLE
Remove the global variable in service package

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-sdk-go#1304]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for device-sdk-go

### Description [**REQUIRED**]
We created the device service interface in #1194, we should further refactor the `service` package and remove the global instance.

### Describe the solution you'd like
Remove the service global instance 
https://github.com/edgexfoundry/device-sdk-go/blob/3773e8a09c42b3e5a0abcc52fe8487ac954c24c5/pkg/service/service.go#L46-L48

and the function accessing it
https://github.com/edgexfoundry/device-sdk-go/blob/3773e8a09c42b3e5a0abcc52fe8487ac954c24c5/pkg/service/service.go#L278-L281

Instead we update the ProtocolDriver Initialize method signature
https://github.com/edgexfoundry/device-sdk-go/blob/3773e8a09c42b3e5a0abcc52fe8487ac954c24c5/pkg/models/protocoldriver.go#L27

to be:
```Go
Initialize(sdk interfaces.DeviceServiceSDK, asyncCh chan<- *AsyncValues, deviceCh chan<- []DiscoveredDevice) error
```

so that the device service developer is able to leverage the `DeviceServiceSDK` interface.

However this might create the interdependent bidirectional dependency between the `DeviceServiceSDK` and `ProtocolDriver` implementation.

After refactoring we will expect something like:
```Go
// Init bootstraps the Device Service
func (s *DeviceService) Init() {
    ...
    s.driver.Initialize(s, s.asynCh, s.deviceCh)
    ...
}

func Factory(driver models.ProtocolDriver) {
    // create DeviceServiceSDK instance
    service := NewDeviceService(driver)
    service.Init()
    ...
}
```

Not sure if this is a good pattern or not.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by hahattan** [comment]
@lenny-intel any thought/concern on the proposed design ?

**Comment by cloudxxx8** [comment]
@ajcasagrande @iain-anderson could you help review Chris' refactoring design?  Thanks.

**Comment by lenny-intel** [comment]
@hahattan , I think this is ok since the driver is takes the SDK Interface as the parameter. This is nice as it allows unit tests to pass a mock of the interface.
