### ISSUE TITLE
Add Start function to the ProtocolDriver interface to allow startup tasks

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#1339]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
https://github.com/edgexfoundry/device-sdk-go/blob/v2.3.0/pkg/models/protocoldriver.go

### Description [**REQUIRED**]
Currently the `ProtocolDriver` interface does not have a `Start` function. It only has `Initialize` and `Stop`. However, the `Initialize` is called _before_ the sdk has been completly bootstrapped, causing issues if you attempt to use certain sdk features during this function call.

### Describe the solution you'd like

Add a `Start` function to the `ProtocolDriver` interface to allow the service to run startup tasks _after_ the sdk has been completely initialized. This should be called after the sdk has been completely initialized. However this may be tricky, as the best place for it, may be within the go-mod-bootstrap code itself, around this area:

https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/bootstrap/bootstrap.go#L237-L240

Which might requiore a breaking change in that package as well.

### Describe alternatives you've considered
Run startup tasks in the `Initialize` function, which leads to issues such as #1331

**Comment by hahattan** [comment]
This is doable after the recent refactoring:
https://github.com/edgexfoundry/device-sdk-go/blob/e5f9ace8858ef16ed7fd9fdcaf664427cc73e288/pkg/service/service.go#L173-L175
