### ISSUE TITLE
Can not find the new device resource because of device cache inconsistency

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/device-sdk-go#1347]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device services

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Start running edgex services
  ```
  docker compose -f docker-compose-no-secty.yml up -d
  ```
2. Create a new device resource to device-virtual profile `Random-Boolean-Device`
  ```
  curl -ki -X POST http://localhost:59881/api/v2/deviceprofile/resource -d '[  
    {
      "apiVersion": "v2","profileName":"Random-Boolean-Device",
      "resource": {
        "name": "resource-add-1", 
        "properties": {"valueType": "Bool","readWrite": "RW"}}
    }
  ]'
  ```
3. Send GET command to read the new device resource and return error
  ```
  curl -ki http://localhost:59900/api/v2/device/name/Random-Boolean-Device/resource-add-1   
  ```

  ```
  {"apiVersion":"v2","message":"error reading DeviceResource resource-add-1 for Random-Boolean-Device -\u003e resource not found","statusCode":500}
  ```
4. Restart device-virtual and send GET command again, return 200
  ```
  {"apiVersion":"v2","statusCode":200,"event":{"apiVersion":"v2","id":"713faa40-fa60-4b3d-aa06-c50675e953f5","deviceName":"Random-Boolean-Device","profileName":"Random-Boolean-Device","sourceName":"resource-add-1","origin":1677213763774591000,"readings":[{"id":"c6578840-16bf-4dd1-92db-5f6a6a69391b","origin":1677213763774591000,"deviceName":"Random-Boolean-Device","resourceName":"resource-add-1","profileName":"Random-Boolean-Device","valueType":"Bool","value":"true"}]}}
  ```

## 🔥 Exception or Error
<pre><code>

error reading DeviceResource resource-add-1 for Random-Boolean-Device -\u003e resource not found
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
main branch/Leviski 

**Anything else relevant?**

**Comment by lenny-intel** [comment]
Is this the same root issue as #1331 ?
@ajcasagrande FYI

**Comment by ajcasagrande** [comment]
@lenny-intel no, these are unrelated.
