### ISSUE TITLE
device-simple when put {"Switch":"false"} error 

### ISSUE THREAD

**Issue by caocaocaodou** [edgexfoundry/device-sdk-go#135]
when i put the command {"Switch":"false"}
the device-simple says that 
ERROR:Handler-parseWriteParams: parsing Write parameters failed {"Switch":"false"},json: can not unmarshal object into Go value of type []map[string]string

thank you!

**Comment by cloudxxx8** [comment]
@caocaocaodou 
The Write parameter only accepts JSON array for now.  Please try
`[{"Switch":"false"}]`

**Comment by caocaocaodou** [comment]
thank you very much！

**Comment by caocaocaodou** [comment]
excuse me, when i use the postman it is ok, but if i use this in the edgex-ui-go, although i can see the state of the switch is changed, the return is "failed", i find that the error is "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
thank you! @cloudxxx8

**Comment by cloudxxx8** [comment]
@caocaocaodou 
got it, and I am fixing this issue on #141, so this one is duplicated
the PR for this fix will be opened today

**Comment by caocaocaodou** [comment]
thank you!
