### ISSUE TITLE
[Levski] Device Service not registered prior to driver initialization

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#1358]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

### Is this a regression? No

 This hasn't caused an issue until the new Cameras services need the service to be registered prior to driver initialization. See  https://github.com/edgexfoundry/device-sdk-go/issues/1331

### Description and Minimal Reproduction [**REQUIRED**]
All edgex services are running normally. Called docker stop . Wait a while. Call docker start . Observe issue where no device commands work due to 404 device not found error, even though the devices clearly exist in core-metadata.

The first error message code is located in device.Initialize and it calls for _, device := range d.sdkService.Devices() {, which in turn calls return cache.Devices().All(), which leads me to believe the devices do in fact exist in the cache.

## 🌍  Your Environment
**Deployment Environment:**
docker compose 2.x
edgex compose levski branch v2.3.0

**EdgeX Version [**REQUIRED**]:**
2.3.0

**Anything else relevant?**

**Comment by ajcasagrande** [comment]
Can be closed now
