### ISSUE TITLE
Implement a device interface to allow unit testing

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#14]
A Device interface should be created to allow the mocking of the device cache to allow unit testing of the command REST endpoint (and possibly other code).

**Estimated effort**: 2-3d

**Comment by falkerson** [comment]
@tonyespy I'm working on it. Could you pls assign it to me along with https://github.com/edgexfoundry/device-sdk-go/issues/15?

**Comment by cloudxxx8** [comment]
DeviceCache is an interface now
