### ISSUE TITLE
Device Profile Submitted wrong info: Failed to unmarshal request body as JSON

### ISSUE THREAD

**Issue by Vincent990413** [edgexfoundry/device-sdk-go#1407]
Hi, when I added one Device-Profile.yml, and I submitted from the dashboard PAGE, I got a problem which went: "code: 400 , message: request failed, status code: 400, err: {"apiVersion":"v2","message":"Failed to unmarshal request body as JSON.","statusCode":400}"

**Comment by cloudxxx8** [comment]
please state the version you are using, and upload the yaml file here.
it's the general error if the yaml file format is wrong.

**Comment by cloudxxx8** [comment]
please also try to use the core-metadata api instead of gui to see what happens

**Comment by Vincent990413** [comment]
Thank you very much for replying to me so quickly first, and I've already fixed this problem by changing it to the proper Version V2.2.0 to conform to the version of EdgeX Foundry.
