### ISSUE TITLE
Make Put command body accept simple JSON type

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#141]
Currently, put command accept JSON array only, like
`[{"key1":"value1"}, {"key2":"value2"}]`
It could be improved to also accept
`{"key1":"value1", "key2":"value2"}`

**Comment by tonyespy** [comment]
This looks to be a mistake in the [device service requirements (v8)](https://wiki.edgexfoundry.org/display/FA/Architecture+Issues+and+Decisions?preview=/7602423/18907296/edgex-cali-delhi-device-requirements-v8.pdf) where the body for a PUT to **/device/{id}/{command}** was described as:

> 
> body:
> An application/json cmdargs, which is an array of key/value pairs where the keys are valid ValueDescriptor names,and provides the command arguments for each device.Ex.'{"VDS-CurrentTemperature": "32.52"}, {"VDS-CurrentHumidity": "1.0"})

This looks like it was never changed when we decided to drop the **All** form of the command endpoint for PUT requests, which was a shorthand to send invoke the specified command endpoint for all devices. It was decided that doing this wasn't really a valid use case as you'd never (in theory) want to invoke for the same command for every device with the same map of parameters for each.

What actually should be supported is a single map of paramters. Ex.

> '{"enableRandomization":"false", "collectionFrequency":"5"}'

**Comment by cloudxxx8** [comment]
I made Delhi support both JSON map and array for backward compatibility, and made master support JSON map only
