### ISSUE TITLE
Make devices/profiles directories relative to the service config directory

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry/device-sdk-go#1414]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
Device services

### Description [**REQUIRED**]
As a side effect of recent changes to config bootstrapping (see https://github.com/edgexfoundry/edgex-go/issues/4448), `DEVICE_PROFILESDIR` and `DEVICE_DEVICESDIR` environment variables no longer apply when using config provider. These configurations are part of the [common device configuration](https://github.com/edgexfoundry/edgex-go/blob/90e066c8f118aeb4a988f9c2e8073aae7cdb5770/cmd/core-common-config-bootstrapper/res/configuration.yaml#L119-L120) that get pushed to the config provider via the Core Common Config Bootstrapper component. 

This affects the device snaps because it is no longer possible to override the path and set the correct directories. See for example the now ineffective device virtual environment variables [here](https://github.com/edgexfoundry/device-virtual-go/blob/5b3a117d3f948b56f5091c16d5e74c3d7a6abbf9/snap/snapcraft.yaml#L32-L33). 

For docker based deployments, it is no longer possible to give a custom path as described [here](https://docs.edgexfoundry.org/2.3/examples/Ch-ExamplesAddingModbusDevice/#add-custom-configuration-to-docker-compose-file).

### Describe the solution you'd like

The [devices and profiles paths](https://github.com/edgexfoundry/edgex-go/blob/90e066c8f118aeb4a988f9c2e8073aae7cdb5770/cmd/core-common-config-bootstrapper/res/configuration.yaml#L119-L120) are relative to the execution directory. I propose changing that to make it relative to the service's config directory set via `-cd`, `--configDir` flags described as "Specify local configuration director" or the corresponding environment variable (see [docs](https://docs.edgexfoundry.org/3.0/microservices/configuration/CommonCommandLineOptions/#confdir)). This makes it consistent with how the service `configuration.yaml` file gets loaded. The default value of config directory is `./res` so the default devices and profiles paths need to be updated to `./devices` and `./profiles` respectively.

The implementation may continue to support absolute paths in case the configured path is absolute (i.e. starting with `/` in unix-based systems). Go provides platform-agnostic implementation to detect that: https://pkg.go.dev/path/filepath#IsAbs

### Describe alternatives you've considered

Inject the path into the local `configuration.yaml` file of the service with the actual path or with a dummy path that can be then overridden by environment variables upon bootstrapping. For example, the following could be added to `configuration.yaml`:
```yaml
Device:
  ProfilesDir: /var/snap/edgex-device-virtual/current/config/device-virtual/res/profiles
  DevicesDir: /var/snap/edgex-device-virtual/current/config/device-virtual/res/devices
```

**Comment by iain-anderson** [comment]
@farshidtz Does the move of devices/profile directory out of the common configuration (https://github.com/edgexfoundry/device-sdk-go/pull/1423 https://github.com/edgexfoundry/device-mqtt-go/pull/563 etc) remove this requirement?
