### ISSUE TITLE
Events which created by AutoEvent contains the reading didn't set on device AutoEvent

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/device-sdk-go#1418]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-service

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://github.com/edgexfoundry/edgex-compose/blob/8a22ffe3ee580c257e50e40c2b53eff48da465fe/docker-compose-no-secty.yml#L27)
2. Verify the events of `Random-UnsignedInteger-Device` which pushing by auto event

```
GET  localhost:59880/api/v2/event/device/name/Random-UnsignedInteger-Device

{
    "apiVersion": "v2",
    "statusCode": 200,
    "totalCount": 28,
    "events": [
        {
            "apiVersion": "v2",
            "id": "8f8f2746-d892-408e-8eff-42546b9a10a8",
            "deviceName": "Random-UnsignedInteger-Device",
            "profileName": "Random-UnsignedInteger-Device",
            "sourceName": "Uint16",
            "origin": 1681191249346359994,
            "readings": [
                {
                    "id": "d5c3b949-8778-4436-a15b-320827a2cfc0",
                    "origin": 1681191249346359994,
                    "deviceName": "Random-UnsignedInteger-Device",
                    "resourceName": "Uint16Array",
                    "profileName": "Random-UnsignedInteger-Device",
                    "valueType": "Uint16Array",
                    "value": "[24214, 10860, 9406, 54914, 7435]"
                },
                {
                    "id": "308af7f6-0a3d-4d9e-8cff-20ce698db4b9",
                    "origin": 1681191249346359994,
                    "deviceName": "Random-UnsignedInteger-Device",
                    "resourceName": "Uint16",
                    "profileName": "Random-UnsignedInteger-Device",
                    "valueType": "Uint16",
                    "value": "39176"
                }
            ]
        },
...
}
```

## 🔥 Exception or Error
[Default auto event setting](https://github.com/edgexfoundry/device-virtual-go/blob/9393cb199918d0b51a604a638f19df0ef5e84a0a/cmd/res/devices/devices.yaml#L47-L60) didn't contain resource Uint16Array, but got the `Uint16Array reading` in the event

## 🌍  Your Environment
**Deployment Environment:** Ubuntu22 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
we have to update sdk code to handle this situation.
@lenny-intel @iain-anderson @jpwhitemn  we enable regexp by default, but here is the side effect.
should we disable regexp by default and allow users to enable it when they need?

**Comment by iain-anderson** [comment]
Even if I had enabled regexp I would not expect "UInt16" to expand to "UInt16Array"
Use `CompilePOSIX` and `FindString` and check that the string found is the entire resource name?
