### ISSUE TITLE
Unable publish event with empty space name when using MQTT as message bus

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#1433]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device service

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
If the event sourceName contains empty space like `test resource`, the SDK can't publish the event because the [common.URLEncode(event.SourceName) method](https://github.com/edgexfoundry/device-sdk-go/blob/main/internal/common/utils.go#L74) encodes the empty space to plus sign `+`. 

for example,
```
edgex/events/device/device-simple/Simple-Device/Simple-Device01/Counter+test
```
the plus sign ( + ) cannot be used in MQTT publish topic.

To solve this issue, we should use url.PathEncode instead.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
Main branch

**Anything else relevant?**

- core-contracts https://github.com/edgexfoundry/go-mod-core-contracts/pull/806
- device-sdk https://github.com/edgexfoundry/device-sdk-go/pull/1335
- edgex-go https://github.com/edgexfoundry/edgex-go/pull/4376

**Comment by cloudxxx8** [comment]
fixed by the above merged PRs
