### ISSUE TITLE
device-virtual memory keeps increasing when device contains autoevents

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/device-sdk-go#1447]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-service

### Is this a regression?

 No, Levski also has same issue.

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX by [compose file](https://github.com/edgexfoundry/edgex-compose/blob/7890ef9232c37fd7451a8a36992d226649d52797/docker-compose-no-secty.yml)
2. Create a new device with us/ms interval autoevent, post device with request body as below.
 ```
[
   {
      "device":{
         "name":"Test-Device",
         "description":"Test-Device",
         "adminState":"UNLOCKED",
         "operatingState":"UP",
         "protocols":{
            "other":{
               "Address":"simple01",
               "Port":"300"
            }
         },
         "labels":[
            "device-sample"
         ],
         "location":"{lat:45.45,long:47.80}",
         "serviceName":"device-virtual",
         "profileName":"Random-Integer-Device",
         "autoEvents": [
                {
                    "interval": "13us",
                    "onChange": false,
                    "sourceName": "Int8"
                },
                {
                    "interval": "10ms",
                    "onChange": false,
                    "sourceName": "Int16"
                },
                {
                    "interval": "1323us",
                    "onChange": false,
                    "sourceName": "Int32"
                },
                {
                    "interval": "331ms",
                    "onChange": false,
                    "sourceName": "Int64"
                }
        ]
      },
      "apiVersion":"v3"
   }
]
```
3. Monitor container memory usage by `docker stats`

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/41656797/235827040-54fdf26e-b997-46c2-8769-d7ad28bc9e79.png)

device-virtual memory usage is over than 100MB.

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 2204 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by weichou1229** [comment]
After running testing and analysis with the go pprof tool, the device service creates lots of goroutine to execute the auto event.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/11187505/236760982-0dfaf502-0c1b-4d1d-8bac-402d69cd4811.png">

This issue can be resolved by:
- decreasing the auto event amount or interval to reduce the effort of device service
- increasing the Device.AsyncBufferSize to leverage the CPU capability to handle more auto event.
  ```
  Device:
    AsyncBufferSize: 1
  ```

**Comment by cloudxxx8** [comment]
related golang issue: https://github.com/golang/go/issues/34457

**Comment by cherrycl** [comment]
Test 1 auto event with 100us and 1ms intervals. For 1ms, the both memory usages, device-virtual and app-rules-engine, still work fine. But for 100us, memory usage grows abnormal.

**Comment by cloudxxx8** [comment]
close this as a limitation
