### ISSUE TITLE
Duplicated function to set device operating state

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#1450]
https://github.com/edgexfoundry/device-sdk-go/blob/c2fb876fcd1e0284408ad645a921007a1ace85f5/pkg/service/manageddevices.go#L105-L141

Is there a reason for both? Should one of them be removed? Is one of them deprecated?

**Comment by cloudxxx8** [comment]
you are right.  we should remove `SetDeviceOpState`
