### ISSUE TITLE
device-simple make build error

### ISSUE THREAD

**Issue by hoihkj** [edgexfoundry/device-sdk-go#146]
Hello,

I follow the link to practice the device service in go and have a make build error. Do you have a suggestion for this error?

UBUntu 18.04 x64
go version go1.11.4
glide v0.13.2

make build
go build ./...
/# github.com/edgexfoundry/device-simple/internal/mock 
 internal/mock/mock_addressableclient.go:29:39: cannot use bson.ObjectIdHex("5b977c62f37ba10e36673802") (type bson.ObjectId) as type string in field value
/# github.com/edgexfoundry/device-simple/internal/common
 internal/common/utils.go:231:19: cannot use bson.ObjectIdHex(id) (type bson.ObjectId) as type string in assignment 
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 2

https://nexus.edgexfoundry.org/content/sites/docs/staging/master/docs/_build/html/Ch-GettingStartedSDK.html

**Comment by cloudxxx8** [comment]
@hoihkj 
Thanks for reporting this bug.  I am fixing it.
It happens because the change of edgex-go.  The format of Ids are changed.

**Comment by cloudxxx8** [comment]
Please see the change in https://github.com/edgexfoundry/edgex-go/pull/938
@hoihkj for testing purpose, please use delhi branch, because it is a stable version

**Comment by hoihkj** [comment]
Hi cloudxx8,

The delhi version could pass the make build, many thanks.
