### ISSUE TITLE
Refactor loading of provision to use common code instead of very similar different code

### ISSUE THREAD

**Issue by ejlee3** [edgexfoundry/device-sdk-go#1482]
# 🚀 Refactor

### Relevant Package [**REQUIRED**]

 This feature request is for device-sdk-go

### Description [**REQUIRED**]
 Refactor the internal/provision/device.go, internal/provision/profile.go, and internal/provision/provisionwatchers.go to clean up repetitive code

### Describe the solution you'd like
 refactor to use a common function that generalizes the type specific information

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
The existing code works, but it could be cleaner and easier to maintain if it is properly cleaned up.

**Comment by jinlinGuan** [comment]
The current code is straightforward and remains clear. Keeping it as it is.
