### ISSUE TITLE
[URI4Files] Expand definition of the provision watchers  and profiles URI index file

### ISSUE THREAD

**Issue by ejlee3** [edgexfoundry/device-sdk-go#1483]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for device-sdk-go

### Description [**REQUIRED**]
 In the code for loading the provision watchers and profiles, it would be nice to know the name of the Provision Watcher or Profile and check if it needs to be loaded before loading it from network when it might just be ignored. 

### Describe the solution you'd like
 We could expand the index.json to include the Provision Watcher/Profile name in order to perform this check. However, this would just work for the URI implementation. For the file implementation, the Provision Watcher/Profile may need to be loaded before the check can be performed.

### Describe alternatives you've considered
 loading it anyways

**Comment by lenny-intel** [comment]
@cherrycl , your TAF tests for URI for device files (profiles & provision watchers) will need to be updated for this new scheme for the index.json file. Note that loading of device files hasn't changed.
