### ISSUE TITLE
Readings always are generated with Name=RO.Parameter 

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#150]
If a call to the command endpoint is successful, the return value is a JSON `Event` containing one or more `Readings`. These same `Event` and `Readings` are also pushed to Core Data as part of the processing of the command. When device-sdk-go creates new `Reading` objects, it uses the `Parameter` field of the associated `ResourceOperation`, however as resource command `Parameter` fields don't always resolve to a device resource name (which has an associated `ValueDescriptor` that shares its name), this can lead to one or more `Readings` without an associated `ValueDescriptor`.

The Java device SDK instead uses the following logic (from [ObjectStore.java::createObjectsList()](https://github.com/edgexfoundry/device-sdk-tools/blob/master/templates/ObjectStore.java#L118)) to set the name of a new `Reading`:

```
if (profiles.descriptorExists(operation.getParameter())) {
        object.setName(operation.getParameter());
        objectsList.add(object);
      } else if (profiles.descriptorExists(object.getName())) {
        objectsList.add(object);
}
```
Note this function is called by the put() function in ObjectStore, which walks through the objects returned by createObjectsList() and uses the `Name` of each to set `Reading.Name`.

For an example of a device profile which defines resource commands with Parameter fields that don't map to `ValueDescriptor` names, see [KMC.BAC-121036CE.profile.yaml](https://github.com/edgexfoundry/device-bacnet/blob/master/deviceprofile_samples/KMC.BAC-121036CE.profile.yaml
).

**Comment by cloudxxx8** [comment]
The `ValueDescriptor` name is created according to `Parameter`
https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/provision/profiles.go#L126

In current design, `Parameter` is mapping to `ValueDescriptor` and is more human readable, and `Object` is mapping to the device operation name for machine

**Comment by tonyespy** [comment]
My point is that a `ResourceOperation.Parameter` may not refer to a `DeviceResource` name, but may instead refer to a `Resource` name.  As `ValueDescriptors` are always created from `DeviceResources`, this may lead to `Reading` which can't be understood. For instance, here's an example from device-virtual [KMC.BAC-121036CE.profile.yaml](KMC.BAC-121036CE.profile.yaml)](https://github.com/edgexfoundry/device-virtual/blob/master/bacnet_sample_profiles/KMC.BAC-121036CE.profile.yaml#L78)

```
name: "CurrentTemperature"
  get:
   -
   { operation: "get", object: "AnalogValue_40", property: "value", parameter: "CurrentTemperature" }
   set:
   -
   { operation: "set", object: "enableRandomization", property: "value", parameter: "enableRandomization" }
   -
   { operation: "set", object: "collectionFrequency", property: "value", parameter: "collectionFrequency" }
```
In this case, if the **command** endpoint was called with "**command=CurrentTemperature**", then the `Reading` name should be **AnalogValue_40** not **CurrentTemperature**.

**Comment by cloudxxx8** [comment]
@tonyespy , @brandonforster would like to provide his help on this issue.  Please provide some guidance about how to resolve it.  We could discuss the solution here.  Thanks.

**Comment by brandonforster** [comment]
Tony, I've got some bandwidth coming up and would like to help out. Do you need any help with this issue? Would you like me to take it over?

**Comment by iain-anderson** [comment]
So are we saying that we should always use the `DeviceResource` name, on the basis that that is what core-data and other upstream services need in order to do ValueDescriptor lookups? That makes sense to me but it means that the `parameter` field in a `ResourceObject` is superfluous for get operations, and confusing for set operations (in that it allows a datapoint's name to be different according to whether you are doing a read or a write). Should we deprecate `parameter` altogether?

**Comment by tonyespy** [comment]
I don't think this issue is really valid...

I went back and re-visited both the Java SDK and Tyler's comments in response to our questions about device profiles.

The Java ProfileStore class creates value descriptors based on **ResourceOperation.Parameter** names (see the [addDevice(Device device)](https://github.com/edgexfoundry/device-sdk-tools/blob/master/templates/ProfileStore.java#L85) function). The code does this:

 * it sets **descriptors** to the results of a query to Core Data for all the existing value descriptors
 * it sets **usedDescriptors** to all of the _expected values_ as defined by the profile's commands section
 * it iterates through all of the **ResourceOperations** defined in the resources section:
  * if there's already an existing value descriptor with the name **op.Parameter**, then it's skipped
  * else it first checks if **op.Parameter** is found in **usedDescriptors** [1]
    * if **false**, then it's skipped
    * it **true**, it creates a new value descriptor in Core Data using the name **op.Parameter,** and the value property from the underlying object

This last bit means that value descriptors are always created with op.Parameter names, not the actual names of the device resources themselves. As most device profiles just use the same names in both places, this wasn't obvious.

Tyler additionally stated:

> ResourceOperation Parameters on get methods map the DeviceResource call to the specified field if the associated ValueDescriptor exists, otherwise it falls back to the DeviceResource.
> 
> e.g. for a ResourceOperation 
> - { operation: “get”, object: “light”, parameter: “intensity” }
> 
> If a ValueDescriptor with name "intensity" exists, the value received from the get call to "light" is mapped to it (Reading = {"name": "intensity", ...}), otherwise it will fall back to "light" (Reading = {"name": "light", ...})

To Cloud's point, if the value descriptors are always created using **ResourceOperation.Parameter**, then I'm not sure how one would ever get created with with a name of a device resource that wasn't also the name of **ResourceOperation.Parameter**.

**Note** - the Java SDK also had code that would auto create resource commands for device resources which lacked corresponding resources. When it did this, the embedded ResourceOperation.Name and Parameter were always set to the same value.

[1] device-sdk-go doe not make this check

**Comment by iain-anderson** [comment]
I think there's still an issue here one way or another. The SDK generates Value Descriptors with DeviceResource names, and generates Readings with Parameter names (this will have to change to an extent with #218 as that will allow Readings without an associated Resource Operation).

**Comment by tonyespy** [comment]
OK, after a bit more investigation, the reason that Readings are being generated with Name=RO.Parameter is that @cloudxxx8 made a decision at some point to change how value descriptors are populated.  The original Java SDK populated value descriptors with the name of _device resources_, which makes sense because the device resources define the value properties.

@cloudxxx8 mentioned that using the RO.Parameter made more sense because these are the "human readable" names, however there's nothing preventing device resource names from being defined as such. The actual mapping to protocol-specific names/ids can be handled via the device resource attributes.

Note - the old Java SDK would only create a value descriptor if resource's (device command) object and a command's (core command) expected values referenced a device object. The Go SDK lacks the second check.

**Comment by iain-anderson** [comment]
For info, C SDK currently generates Readings with name = DeviceResource.Name, and generates ValueDescriptors also with name = DeviceResource.Name.
ValueDescriptors are generated for each DeviceResource in every DeviceProfile that is created (ie, no check on whether they are used in a CoreCommand).

**Comment by cloudxxx8** [comment]
@tonyespy how about I change the ValueDescriptors name generated from DeviceResource.Name, and make it the same as C SDK?
In this case, I don't think `PropertyValue.parameter` can do anything.  Could we remove it?
