### ISSUE TITLE
Getting InternalServerError 500 instead of Bad Input 400 when trying to set a device resource value with some wrong/invalid parameter

### ISSUE THREAD

**Issue by TuhinDasgupta-eaton** [edgexfoundry/device-sdk-go#1520]
**Relevant Package [REQUIRED]**

We are facing this with the edgex device-virtual service when trying to update/set a device channel resource value with wrong/invalid parameter.

**Description [REQUIRED]**

We are currently getting "InternalServerError, 500" when trying to set a device resource value with some wrong/invalid parameter. The expected error with status code should be "Bad Input, 400".  As per our finding this is happening within the function flow: SetCommand->writeDeviceResource->createCommandValueFromDeviceResource (device-sdk-go/internal/application/command.go, line no.  290). Error type mapped in this is: "KindServerError". It should be: "KindContractInvalid" which points to Bad Input.
For example we are setting are providing -1 as input parameter to a device channel resource whose expected datatype is uint32, we are getting "InternalServerError, 500" as response in this case. But, say if we provide some valid parameter say 1000 which is valid as per uint32 datatype but is actually out of range for the same device channel resource value, then that time we do get "Bad Input, 400" as response which is actually expected. Below are the attached screenshots for better understanding:

![400_Issue](https://github.com/edgexfoundry/device-sdk-go/assets/104066448/4ed2ffdc-24b8-4dea-a5e3-d2106feb8218)

![Issue_500](https://github.com/edgexfoundry/device-sdk-go/assets/104066448/40672167-8f38-4acc-b601-52195e2f6f69)

**Describe the solution you'd like**
Whenever we try to update/set a device channel resource value with such invalid parameters as in this case, the response should be of typec"Bad Input, 400" which signifies that we are giving an invalid input. This is working for valid out of range device channel resource value.

**Comment by cloudxxx8** [comment]
`createCommandValueFromDeviceResource` is also reused by Get Command, so the source value might come from Device, which should not be bad user input.
We can wrap the error to contract error in `writeDeviceCommand` and `writeDeviceResource`
https://github.com/edgexfoundry/device-sdk-go/blob/8a4e603c9daa9d98ee8f2e5896cc64fc9a451017/internal/application/command.go#L290
https://github.com/edgexfoundry/device-sdk-go/blob/8a4e603c9daa9d98ee8f2e5896cc64fc9a451017/internal/application/command.go#L388

**Comment by cloudxxx8** [comment]
@mehulrana017 this is a simple bug.  if you want, you can start from this one.
