### ISSUE TITLE
Use UUID format for id in unit tests

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#158]
Currently, the id format in unit tests are still BSON Id.  They should be replaced with UUID format to consistency

**Comment by tonyespy** [comment]
Does this cause the unit tests to break? If not, it seems like we should fix them, and maybe add a test to ensure that the Ids are proper UUIDs.

**Comment by tonyespy** [comment]
@cloudxxx8 Can you add a pointer to a specific unit test?

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/controller/restfuncs_test.go

**Comment by cloudxxx8** [comment]
fixed by #200
