### ISSUE TITLE
Simplify device profile caching

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#16]
The current implementation of the local device profile caching as implemented in profiles.go is based on the original EdgeX Java Device Services SDK. The original code is overly-complicated and has one enormous function called addDevice() which should be broken up.  Instead of having a simple map or array of DeviceProfile structs, maps of DeviceObjects and commands are created.

Recently a map of DeviceProfile objects was added to handle automatic importing of device profiles via on-disk YAML files.

This task is to explore simplification of the code, possibly using recently added DeviceProfile map directly instead using the derived command and objects maps.  Thread safety should also be reviewed, and unit tests added as part of this task.

**Estimated effort**: 5-8d

**Comment by weichou1229** [comment]
@tonyespy I'm woking on this issue with https://github.com/edgexfoundry/device-sdk-go/issues/10

**Comment by cloudxxx8** [comment]
fixed by #74
