### ISSUE TITLE
Add GetDeviceByName method to device-sdk-go ManagedDevices.go

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry/device-sdk-go#161]
cache.Devices is internal so does not get exposed to outside callers; making this GetDeviceByName access method warranted.

I would need to clean up commit history but implementation proposed here:
Ref: https://github.com/edgexfoundry/device-sdk-go/pull/160/files

**Comment by tobiasmo1** [comment]
Commit squashed and review was accepted here:
https://github.com/edgexfoundry/device-sdk-go/pull/163#pullrequestreview-196356371

**Comment by cloudxxx8** [comment]
@tobiasmo1 , one question about this issue.  we are making another device service encountering the similar issue, but the protocol driver doesn't have the device name.  how does your driver get the device name in advance?  I am thinking about adding a GetDeviceByAddressableName

**Comment by tobiasmo1** [comment]
In my case, the device service is supplying the name when adding new (or checking for existing) device; e.g., serial number of a discovered network camera.
