### ISSUE TITLE
Add more information to log in start up time

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#167]
To consist with edgex-go, the service should log the following information:

> Service started in: xxx
> Listening on port: xxx

**Comment by alexcourouble** [comment]
Can this be assigned to me? Seems like a good issue to start with to get familiarized with the project.

**Comment by cloudxxx8** [comment]
@alexcourouble sure, please take it.  Thank you :)

**Comment by alexcourouble** [comment]
Should this code live in `main.go` or `simpledriver.go`?

**Comment by cloudxxx8** [comment]
No, it should be in bootstrap.go or service.go, because it needs to reside in SDK.
main.go or simpledriver.go are under example

**Comment by cloudxxx8** [comment]
fixed by #214
