### ISSUE TITLE
Review devices/profiles struct and pointer usage

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#17]
Review composition of internal complex data types as used in the device and profile cache.  Should arrays/maps use structs or pointers to structs?  Currently the device cache use pointers to Device structs in it's map, whereas the profile cache code doesn't use pointers in its commands and objects maps. In theory, none of the code that accesses devices in the local cache should need to modify the devices, so there's no reason for the pointer usage other than the potential optimization.

**Estimated effort**: 2-3d

**Comment by jduranf** [comment]
@tonyespy the current implementation of devices using pointers it's buggy and can't handle more than one device. This happens because the device are added in a [for loop](https://github.com/edgexfoundry/device-sdk-go/blob/master/devices.go#L51), and the `md` is added as a reference, but `md` is always the same variable in the for.
One solution is to change the device map from pointers to structs. If it's fine, I can fix it.

**Comment by cloudxxx8** [comment]
@tonyespy 
May I know why the OperatingState is DISABLED during newDeviceCache function?

**Comment by cloudxxx8** [comment]
@jduranf 
It looks like Tony prefers to use pointer, and the size of Device variable might be really large.
May we use the following code to create pointer in the DeviceCache?

```
		for index, _ := range mDevs {
			err = svc.dc.UpdateOpState(mDevs[index].Id.Hex(), "DISABLED")
			if err != nil {
				svc.lc.Error(fmt.Sprintf("Update metadata DeviceOpState failed: %s; error: %v", md.Name, err))
			}

			mDevs[index].OperatingState = models.OperatingState("DISABLED")
			dc.add(&mDevs[index])
		}
```

**Comment by jduranf** [comment]
@cloudxxx8 
Yes, if you prefer to use pointers, this will also solve the issue. I will update the PR

**Comment by cloudxxx8** [comment]
@jduranf 
Thanks for your effort on this.  I've merged the PR.

**Comment by tonyespy** [comment]
@cloudxxx8 @jduranf The original implementation used pointers because as a C programmer, the idea of copying a **Device** struct around seemed counter-intuitive. A quick checking using **unsafe.SizeOf** shows that the size of **Device** struct is ~904 bytes. Note, as I understand it, this doesn't include length of any memory referenced by the struct (eg. slices, strings, ...). So this is the original reason I used pointers.

**Comment by tonyespy** [comment]
@cloudxxx8 I think we should open a separate issue for the device being set to DISABLED on startup. If you think it makes sense to remove it, I'd say go for it.

**Comment by tonyespy** [comment]
@jduranf @cloudxxx8 Can this issue be closed now?

**Comment by jduranf** [comment]
For me, this issue can be closed

**Comment by cloudxxx8** [comment]
ok, let's close it
thanks all
