### ISSUE TITLE
Re-runnable Example

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry/device-sdk-go#171]
The example errors on subsequent runs, during device-simple app's creation of device from configuration.toml.  Cleaning mongoDB between runs is a workaround.

```
level=DEBUG ts=2019-02-11T16:09:43.434651041Z app=device-simple source=devices.go:26 msg="Device Simple-Device01 doesn't exist, creating a new one"
level=DEBUG ts=2019-02-11T16:09:43.437816224Z app=device-simple source=utils.go:236 msg="Addressable Simple-Device01 exists, using the existing one"
level=DEBUG ts=2019-02-11T16:09:43.440598805Z app=device-simple source=devices.go:63 msg="Adding Device: (device props)...
...
level=ERROR ts=2019-02-11T16:09:43.450245082Z app=device-simple source=devices.go:66 msg="Add Device failed {\"created\":0,\"modified\":0,\"origin\":1549901383439,\"description\":\"Example of Simple Device\",\"id\":null,\"name\":\"Simple-Device01\",...
```

**Comment by cloudxxx8** [comment]
@tobiasmo1 could you please provide the recreate steps?  Thanks

**Comment by tobiasmo1** [comment]
1. In terminal #1, initiate EdgeX stack. 
`cd ~/go/src/github.com/edgexfoundry/edgex-go/bin;./edgex-launch.sh
`
2. In terminal #2, initiate SDK example app.
`cd $GOPATH/src/github.com/edgexfoundry/device-sdk-go/example/cmd/device-simple;./device-simple
`
3. Stop SDK example by pressing Ctrl+C in terminal #2.

4. Repeat step (2), initiating SDK example app.
Note that now the Simple-Device01 device is registered with EdgeX (stored in mongo) but does not exist in device cache (cache is non-persistent and not initialized/refreshed on startup).

(error reproduces here)

```
> level=DEBUG ts=2019-02-13T06:13:47.374176364Z app=device-simple source=devices.go:26 msg="Device Simple-Device01 doesn't exist, creating a new one"
> level=DEBUG ts=2019-02-13T06:13:47.376291723Z app=device-simple source=utils.go:245 msg="Addressable Simple-Device01 exists, using the existing one"
> level=DEBUG ts=2019-02-13T06:13:47.378537932Z app=device-simple source=devices.go:72 msg="Adding Device: {\"created\":0,\"modified\":0,\"origin\":1550038427377,\"description\":\"Example of Simple Device\",\"id\":null,\"name\":\"Simple-Device01\",\"adminState\":\"UNLOCKED\",\"operatingState\":\"ENABLED\",\"addressable\":{\"created\":1550036864849,\"modified\"
> ...
> level=ERROR ts=2019-02-13T06:13:47.387751906Z app=device-simple source=devices.go:81 msg="Add Device failed {\"created\":0 ... ,  error: 409 - Duplicate name for device\n"
> 
```

5. This can be further confirmed by explicitly deleting a device by name from EdgeX (removing persisted device from mongo) before adding a device.

Update from [line 61 of internal/provision/devices.go](https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/provision/devices.go#L61) to add two lines shown in the following block of code. Then **make build** and repeat step (2). 
Expect: The error no longer occurs since there is no name conflict.

```
> 	device.Origin = millis
> 	device.Description = dc.Description
> 	common.LoggingClient.Debug(fmt.Sprintf("Adding Device: %v", device))
> 
> 	// BEGIN
> 	common.LoggingClient.Debug(fmt.Sprintf("First deleting EdgeX device named: %v", dc.Name))
> 	common.DeviceClient.DeleteByName(dc.Name)
> 	// END
> 
> 	id, err := common.DeviceClient.Add(device)
> 	if err != nil {
> 
```

**Comment by tonyespy** [comment]
@tobiasmo1 Your original description is a bit unclear... 

I *think* what you're trying to describe is that if you run the device-sdk-go's example device-simple, exit it via signal, and then re-run it, the service generates errors because it tries to re-add a device with a name which is already present in Core Metadata. Does the example still work (i.e. the log messages are just misleading)?

The creation of devices from **configuration.toml** or the registry was something introduced with the new SDKs as part of the Delhi release. The original behavior was always for a device service to just use any devices found in Core Metadata, which I think is still happening. New devices were added out-of-band from the device service.

That said, these are `level=DEBUG `messages, are they really a problem?

**Comment by tobiasmo1** [comment]
Yes you've summarized the condition well. But it creates a fatal condition, and does log other errors (I was listing the debug entries just for context).

Here are a few additional errors:
`level=ERROR ts=2019-02-11T07:19:52.168809581Z app=device-simple source=devices.go:29 msg="creating Device from config failed: {Simple-Device01 Simple-Device
...
level=ERROR ts=2019-02-13T00:07:44.008184074Z app=device-simple source=executor.go:66 msg="Schecule Event readSwtich execution failed, AppErr: {<nil> Device: Simple-Device01 not found;  404}"
...
level=ERROR ts=2019-02-13T00:07:49.001452546Z app=device-simple source=command.go:41 msg="Device: Simple-Device01 not found; "
`

Unfortunately it isn't just that it is logging the condition as an error. The example simply does not work on subsequent runs. It endlessly loops with device-Simple01 device not being found on scheduled interval (i.e., device service is unaware the device is registered with EdgeX).

As you'll notice it doesn't add the device to the cache.Devices() upon this error (see a few lines later in same createDevice method I linked). This cache is the device service's source-of-record for persisted devices. Absence of it causes the scheduled events for polling readings or other commands to fail.

**Comment by cloudxxx8** [comment]
@tobiasmo1 I read the code again and confirmed device-sdk-go handles this situation.  Also, I can't reproduce it.  May I know which version of edgex-go you are running?
Could you please try to retrieve the following information to me after step 3.

1. Open browser and call the API to retrieve Devices by Service Name: http://${host}:48081/api/v1/device/servicename/device-simple
2. Open browser and call the API to retrieve the Devices by Name: http://${host}:48081/api/v1/device/name/Simple-Device01

Thanks

**Comment by tobiasmo1** [comment]
GET http://edgex-core-metadata:48081/api/v1/device/servicename/device-simple
returns 404 "Item not found"
GET http://edgex-core-metadata:48081/api/v1/device/name/Simple-Device01
returns 404 "Item not found"

Also... 

GET http://edgex-core-metadata:48081/api/v1/deviceservice/Simple-Device01
returns 500 "Invalid object ID"

GET http://edgex-core-metadata:48081/api/v1/deviceservice/name/Simple-Device01
returns 404 "Item not found"


GET http://edgex-core-metadata:48081/api/v1/deviceservice
returns 200 OK with application/json body "[]"

GET http://edgex-core-metadata:48081/api/v1/device
returns 200 OK with application/json body "[]"

**Comment by tobiasmo1** [comment]
I will post responses from after first run also.

Currently I am getting this error on startup of device-simple (against a clean mongodb running on non-default port 27018).. I need to confirm several service config files are updated to assure they're aware of correct mongo target:
```
Init: useRegistry: false profile:  confDir: 
Bypassing registration in registry...
Calling service.Start.
EnableRemote is false, using local log file
level=INFO ts=2019-02-25T17:10:59.594831416Z app=device-simple source=init.go:138 msg="Check Metadata service's status ..."
level=INFO ts=2019-02-25T17:10:59.595034216Z app=device-simple source=init.go:138 msg="Check Data service's status ..."
level=INFO ts=2019-02-25T17:10:59.607337595Z app=device-simple source=init.go:48 msg="Service clients initialize successful."
level=DEBUG ts=2019-02-25T17:10:59.609143058Z app=device-simple source=service.go:126 msg="Trying to find Device Service: device-simple"
level=ERROR ts=2019-02-25T17:10:59.617504931Z app=device-simple source=service.go:136 msg="DeviceServicForName failed: Item not found"
error: Couldn't register to metadata service

```

**Comment by cloudxxx8** [comment]
@tobiasmo1 I can re-run device-simple in master release now.  Could you please help confirm whether this issue is still valid?  Thanks.

**Comment by cloudxxx8** [comment]
@tobiasmo1 is this issue still valid?

**Comment by tobiasmo1** [comment]
The behavior is much better now. I would say this is resolved. 
Let's address remaining issues related to persisted cache separately.
