### ISSUE TITLE
Modify the NotFound error type to comply with the client code change

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#174]
To meet the change:
https://github.com/edgexfoundry/edgex-go/commit/65d80f6cb45a5483de5233600e275d54995d9d6c#diff-2311174e4ebc3d4be67d0cf62dc5e1d2

**Comment by jduranf** [comment]
After [this PR](https://github.com/edgexfoundry/go-mod-core-contracts/pull/9) I think the only thing to do to fix the issue is update the `go.mod` file.

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/go-mod-core-contracts/pull/9
