### ISSUE TITLE
Version Query from ping API

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#179]
According to [Releases, Versions & Patches](https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=21823969) document on wiki, the ping API should return the version number instead of `pong`

**Comment by difince** [comment]
Can this be assigned to me?

**Comment by SteveOss** [comment]
Hi @difince for some reason your name is not appearing on Assignee list, so I can't assign. @cloudxxx8 can you do this?

**Comment by cloudxxx8** [comment]
@difince we can't assign to you on the issue, but leave a comment here is enough.  please take it :)

**Comment by cloudxxx8** [comment]
fixed by #205
