### ISSUE TITLE
New DeviceServiceClient error handling logic is wrong

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#182]
Issue #142 updated the error handling logic for the error types.ErrNotFound for client calls to AddressableClient and DeviceServiceClient.  The original code did this:

`if _, ok := err.(types.ErrNotFound); ok`

which was changed to this:

`if errsc, ok := err.(*types.ErrServiceClient); ok && (errsc.StatusCode == http.StatusNotFound)`

Maybe this works for the `AddressableClient` calls, but it doesn't work for `DeviceServiceClient.DeviceServiceForName()`, which still returns a concrete `types.ErrNotFound` instance if the device service isn't found.

**Note** - ironically the [PR](https://github.com/edgexfoundry/device-sdk-go/pull/145) that made this change had requested my review, but it was merged before I could do so...  ;)

I'm also going to file a separate bug against the new ErrServiceClient, as I don't think it's current implementation is well thought out, and there's zero godoc in the source file.

**Comment by jduranf** [comment]
The client behavior was modified 100 days ago in edgex-go and then in go-mod-core-contracts [5 days ago](https://github.com/edgexfoundry/go-mod-core-contracts/pull/9). Now, in order to work properly, as I said in #174, go.mod file should be updated in order to fix the issue.

**Comment by tonyespy** [comment]
Thanks for the explanation, updating go.mod to use "latest" for go-mod-core-contracts does fix the issue. I think keeping it at latest until we release is probably best. That'll keep us honest.

That said, I still am going to file an issue against go-mod-core-contracts regarding the lack of godoc in models/types/error.go, and the fact that checking for a simple **NotFound** return code requires so much code.

**Comment by tobiasmo1** [comment]
This resolves the discussion on same condition I mentioned in PR#172 . 

https://github.com/edgexfoundry/device-sdk-go/pull/172

Thanks Tony!
