### ISSUE TITLE
Improve HandleReadCommands / HandleWriteCommands API

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-go#187]
A number of suggestions have been made for changes to these functions.

One is that we add the name of the device being queried. This would allow a ProtocolDriver to obtain full device and profile information if necessary via GetDeviceByName(). It would also allow for more informational logging in the implementation.
Another is to reduce the contents of CommandRequest to only those elements that the driver will need, rather than large parts of the device profile.

Currently we have:

```
type CommandRequest struct {
        RO models.ResourceOperation
        DeviceResource models.DeviceResource
}
HandleReadCommands(addr *models.Addressable, reqs []CommandRequest) ([]*CommandValue, error)
HandleWriteCommands(addr *models.Addressable, reqs []CommandRequest, params []*CommandValue) error
```

This could become:

```
type CommandRequest struct {
        Attributes map[string]interface{}
        VType ValueType
}
HandleReadCommands (devname string, protocols map[string]map[string]string, reqs []CommandRequest) ([]*CommandValue, error)
HandleWriteCommands (devname string, protocols map[string]map[string]string, reqs []CommandRequest, params []*CommandValue) error
```

(map[string]map[string]string is the replacement type for Addressable in a device).
This would need to change further if we allow for mixed get and set operations within a command.

**Comment by jduranf** [comment]
Those change have already done. Maybe this issue can be closed.

**Comment by iain-anderson** [comment]
Some of them have, and the rest is covered in #213 so yes I think so.
