### ISSUE TITLE
Add devices init/remove command support

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#19]
Add support for generic init and disconnect functions when devices are added or removed from the device service.  The commands must be valid commands in the corresponding device profile.  The functions are defined by the configuration settings **InitCmd** and **RemoveCmd** settings, and arguments for both are specified in the **InitCmdArgs** and **RemoveCmdArgs** settings. 

Note - it might be a good idea to update the setting names to include "Dev" or "Device".  Also maybe **InitCmd** should be **AddDeviceCmd** to make things more sensical?

### Estimated effort: 3-4d

**Comment by cloudxxx8** [comment]
@tonyespy I don't understand this item very well.   Could you please provide more background or point out which section in the requirement document?  Thanks.

**Comment by iain-anderson** [comment]
AddDeviceCmd / AddDeviceArgs and RemoveDeviceCmd / RemoveDeviceArgs sounds good to me.
The arguments to be a JSON string?

**Comment by iain-anderson** [comment]
I'm not sure about having the configuration options apply to every device managed by the service. Could they be scoped to device profiles in some way?

**Comment by tonyespy** [comment]
This needs some more discussion, and we're going to punt for Edinburgh.

**Comment by anonymouse64** [comment]
How does this relate to #276 ?

**Comment by iain-anderson** [comment]
I think 276 allows for more flexible connect/disconnect options but the driver has to implement them itself rather than the SDK doing it

**Comment by jpwhitemn** [comment]
Jim to research Java origins per 9/16/2019 WG meeting.  Hold for now.

**Comment by iain-anderson** [comment]
I'm closing this issue and the corresponding one in CSDK. If we get requirements / use case in future we can reconsider but the solution will not necessarily look like this.
