### ISSUE TITLE
Health Check Unsuccessful

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/device-sdk-go#190]
After the recent PR #186 confirmed device services are registering themselves with Consul, however the health check is failing. Needs root cause and troubleshooting.

<img width="606" alt="screen shot 2019-03-01 at 10 31 27 am" src="https://user-images.githubusercontent.com/1342980/53652395-68fb0200-3c0e-11e9-8132-7b7d45f73932.png">

**Comment by tsconn23** [comment]
Further investigation shows that the above result happens when the device-simple is started by itself, independently of the other services. So for example, if the availability checks for metadata or core-data fail, the device-simple health check (and by extension all device services implementing the SDK) also fails.

**Comment by lenny-intel** [comment]
@tsconn23 isn't having the other services running a requirement of the device service?

**Comment by tsconn23** [comment]
@lenny-intel I don't see why it would be, especially if we ever deploy into a load-balanced, HA environment. Services that are down, may come back up. A device service should be autonomous in my opinion w/r/t its startup. EdgeX services aren't a dependency like Consul or Mongo.

**Comment by tsconn23** [comment]
Closing as this has been root caused now. Considering opening another issue related to the hard dependency on startup with other edgex services.

**Comment by anonymouse64** [comment]
@tsconn23 the dependency on other EdgeX services is in the device services requirement doc that @tonyespy wrote
