### ISSUE TITLE
Implement readings cache in Device Services

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/device-sdk-go#195]
The SDKs will implement a means to provide a cache of readings. This allows the collection and response for a request of a reading to be decoupled (and more asynchronous).

Moved from original location
https://github.com/edgexfoundry/edgex-go/issues/829

**Comment by iain-anderson** [comment]
I'm not sure how this is intended to work. Here's one suggestion

**Driver posts an Event on the asynchronous channel:**

- Event is sent to core-data
- Event is cached

**Device Service receives a GET query:**
_Does a cached Event exist for the required Device and deviceCommand?_
_If Yes_

- Return the cached Event
- Discard the cached Event
- Do not re-send it to core-data

_If No_

- Query the driver for new readings
- Return the resulting Event
- And send it to core-data

**Comment by iain-anderson** [comment]
A different version of that would be that an Event generated asynchronously would not be immediately sent to core-data, it would only be cached. In that case the Event would go to core-data in response to an incoming GET.

**Comment by cloudxxx8** [comment]
The first version looks more reasonable to me because async reading is a kind of passive operation, not active operation.   Get command is a kind of active operation.  Also, we might need to add a attribute in Device Resource of Device Profile to indicate whether it is async value.

**Comment by iain-anderson** [comment]
Agreed to defer pending requirements clarity (at WG meeting Aug 5)

**Comment by cloudxxx8** [comment]
@iain-anderson have you implemented this in C SDK? Should we put into Hanoi scope?

**Comment by iain-anderson** [comment]
Closing this: functionality better implemented elsewhere eg, support-data
