### ISSUE TITLE
Implement Reading assertions

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#20]
Assertions are another attribute  in a device resource's value PropertyValue which specify a string value which the result is compared against.  If the  comparison fails, then the result is set to a string of the form “Assertion failed for device resource: <name>, with value: <result>”, this also has a side-effect of setting the device operatingstate to DISABLED.  In the case of the single device /command endpoint, a 500 status code is also returned. If the all form of the /command endpoint is used an assertion failure will return a 200 status, and it's the responsibilty of the client to check each reading for assertion failures.

As assertions are operations on results *after* they've been transformed into the string to be passed in the Reading, assertions cannot as currently defined, be applied to binary readings which result in an array of bytes vs. a string result in the Reading.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

**Estimated effort**: 2d

**Comment by cloudxxx8** [comment]
fixed by #74
