### ISSUE TITLE
Update Device SDK Go document for Edinburgh release

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry/device-sdk-go#201]
Hi,

This is the only doc I was able to find for device-sdk-go: https://docs.edgexfoundry.org/Ch-GettingStartedSDK.html

It seems outdated (it mentions go glide and make prepare which do not work with the current version). 

Is there an updated version of this doc that would work with the master branch?

I'd love to help updating it, if needed.

**Comment by cloudxxx8** [comment]
@alexcourouble the document is for our released version- delhi, so please use delhi branch with this document.  The master branch is for Edinburgh release (next release), and the code is still developing.  we will provide more document during code freeze (April first).  It's nice to get your help for the documentation :)

**Comment by cloudxxx8** [comment]
doc has been updated
https://github.com/edgexfoundry/edgex-docs/blob/fuji/getting-started/Ch-GettingStartedSDK-Go.rst
