### ISSUE TITLE
Log messages shouldn't dump entire objects

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#202]
ERROR log statements should only include enough information in the log message to diagnose what went wrong vs. dump the current state of entire objects.

The function createDevice() in internal/provision/devices.go dumps the entire offending object in an [ERROR log message](https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/provision/devices.go#L63) when a request to add a new device to Core Metadata fails.

Dumping entire objects in log messages is typically reserved for DEBUG log messages as extremely large log messages can eat up persistent storage and actually in some instances make it harder to analyze logs.

Here's just the first ~20% of log message looks like this case:

`level=ERROR ts=2019-03-10T14:49:55.350296056Z app=device-random source=devices.go:69 msg="Add Device failed {\"created\":0,\"modified\":0,\"origin\":1552229395318,\"description\":\"Example of Device Random\",\"id\":null,\"name\":\"Random-Integer-Generator01\",\"adminState\":\"UNLOCKED\",\"operatingState\":\"ENABLED\",\"addressable\":{\"created\":1552229198065,\"modified\":1552229198065,\"origin\":1552229198055,\"id\":\"4d87e39c-5b2d-4011-9cab-ba964588109c\",\"name\":\"Random-Integer-Generator01\",\"protocol\":\"OTHER\",\"address\":\"device-random-01\",\"baseURL\":\"OTHER://device-random-01:0\",\"url\":\"OTHER://device-random-01:0\"},\"lastConnected\":0,\"lastReported\":0,\"labels\":[\"device-random-example\"],\"location\":null,\"service\":{\"created\":1552229197756,\"modified\":1552229197756,\"origin\":1552229197746,\"description\":\"\",\"id\":\"9cb1cffa-fb37-45e8-ac24-1a55a8a7694f\",\"name\":\"device-random\",\"lastConnected\":0,\"lastReported\":0,\"operatingState\":\"ENABLED\",\"labels\":[],\"addressable\":{\"created\":1552229197737,\"modified\":1552229197737,\"origin\":1552229197727,\"id\":\"42e27695-ad68-4577-a4f6-8b0c72deb2bb\",\"name\":\"device-random\",\"protocol\":\"HTTP\",\"method\":\"POST\",\"address\":\"localhost\",\"port\":49988,\"path\":\"/api/v1/callback\",\"baseURL\":\"HTTP://localhost:49988\",\"url\":\"HTTP://localhost:49988/api/v1/callback\"},\"adminState\":\"UNLOCKED\"},\"profile\":{\"created\":1552229197846,\"modified\":1552229197846,\"origin\":0,\"description\":\"Example of Device-Random\",\"id\":\"9cdae6e7-3598-4576-9774-323b4482f788\",
`

**Comment by tobiasmo1** [comment]
Good catch Tony. Also a reminder that it appears this could needlessly leak sensitive information into logs. I suspect that now supplying a correlation id is sufficient to replace these contents; hopefully even for DEBUG purposes.

**Comment by difince** [comment]
@tobiasmo1 No, currently the correlation id is not part of the error log messages. 
Could I work on this issue taking in consideration [https://github.com/edgexfoundry/go-mod-core-contracts/issues/27](url)

**Comment by cloudxxx8** [comment]
@difince yes, please take this issue, and I will help review the change.  thanks.

**Comment by cloudxxx8** [comment]
@difince since the code freeze date is approaching, I just opened a PR for this issue.  please help review if you have time.
