### ISSUE TITLE
Implement Reading transforms

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#21]
Implement transformations of device readings.

The values that can be read from a device are defined in the PropertyValues of device resources as defined by a DeviceProfile.   A PropertyValue may specify optional attributes which are used to transform the readings from devices/sensors. These attributes are defined below and are applied to the native data types (float* or int/uint*) in the following order:

base – a base value which is raised to the power of the reading value
scale  – a multiplicative factor applied to the reading
offset – an additive factor applied to the reading

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

**Estimated effort**: 2d

**Comment by jduranf** [comment]
@tonyespy I started to work in this issue, and I think should be easier to implement this issue if `NumericResult []byte`, `StringResult string` and `BoolResult bool` are changed by a `Result string` in [CommandResult](https://github.com/edgexfoundry/device-sdk-go/blob/master/commandresult.go).
I think this will also simplify the code and the implementation of #24 and #20 issues.
What do you think?

**Comment by cloudxxx8** [comment]
@jduranf I thought we could keep this design, because NumericResult and BoolResult might be helpful in some cases.  Also, if the Type is bool or string, we could skip the transformation and only do the mappings only.  If the `Result string` is a numeric value, you still need to cast it to another type to do the transformation.  What do you think?

**Comment by cloudxxx8** [comment]
fixed by #74
