### ISSUE TITLE
command endpoint doesn't respond to device resource names

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#218]
The device-sdk-go (latest in master) doesn't respond to the command endpoint if the given command name is a device resource. It only responds to a command request if the given name is a resource. For instance, device-random (again latest master) rejects the following:

/api/v1/device/c31d0300-e0ca-4be2-9dea-2569ea2d9a54/RandomValue_Int8

...but accepts:

/api/v1/device/c31d0300-e0ca-4be2-9dea-2569ea2d9a54/GenerateRandomValue_Int8

This means it's not possible for someone to use Support Scheduler to define ScheduleEvents (not sure what then name is for these) which directly query device resources.  This was possible with the Java SDK, and the device-sdk-c was just updated recently to support them. This is related to issue #150.

**Comment by tonyespy** [comment]
After reviewing the original Java SDK, I believe my understanding of how this all works is slightly off.

When importing a device profile, a list of valid commands is generated based on the defined resource operations in each resource (now called device command). When one of these resource operations results in a new valid command, the associated device resource is also enabled.

What this means was that you couldn't just have a device profile with a single device resource and expect it to be usable as a command. You also need a resource operation which references the given device resource.

Note - one problem with fixing this issue currently is that the SDK now creates value descriptors with Name=RO.Parameter. This means someone using a device resource name as a command would return a result with a name which doesn't match any existing value descriptor name.

Ex. 

DeviceResource1.Name = Foo
DeviceCommand.Name = Command
  GetRO.Param = Fubar

If the REST endpoint is called with "Command", the returned Reading will have the value descriptor name "Fubar". If the REST endpoint is called with "Foo", then the result will use "Foo", and thus not match any value descriptors.

See issue #150 for more details.

**Comment by tonyespy** [comment]
@iain-anderson Please review my previous comment.

**Comment by iain-anderson** [comment]
IMO the most logical behavior would be for the device service to answer only to what are now DeviceCommands. But I expect that it will be very convenient - especially for devices with a large number of resources - to also allow access to individual DeviceResources. Effectively having an implicit DeviceCommand with the same name for every DeviceResource. So I agree with the issue as originally stated.
As to the names attached to readings and ValueDescriptor generation, I think that RO.Parameter adds unhelpful ambiguity and should not be supported.

**Comment by cloudxxx8** [comment]
let's discuss in the working group meeting next tomorrow.  we could decide whether RO.Parameter could be removed from contract and edgex-go.  After #270, this field becomes useless
