### ISSUE TITLE
Implement Reading mappings

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#22]
Implement reading mappings.

Mappings are an attribute in resource operation (see Appendix C - Device Profiles for details) and consist of a static list of string result values that contain a fixed mapping.  Ex.

[ “8675309”: “911”, “2112”: “1”, “777”: “666”]

Mapping are applied after assertions are checked, and are the final transformation before readings are created.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

**Note** - support for mappings is a nice-to-have for Dehli.

**Estimated effort**: 2d

**Comment by cloudxxx8** [comment]
fixed by #74
