### ISSUE TITLE
Implement binary encoding of Events & Readings

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#23]
Implement binary encoding (using CBOR) of events & readings.

This first assumes that a new bytes field (vs. the result field which is a string) has been added to the Reading struct, so the CBOR can encode the byes properly.

**Estimated effort**: 5-7d

**Comment by tobiasmo1** [comment]
The 'mediaType' property has been added to go-mod-core-contracts value descriptor. Update device-simple01 example to assign MediaType to binary Event readings; e.g., mediaType='PNG'.

First determine if mediaType could be assigned in response to DeviceInitialize (new ProtocolDriver callback described in issue #276 ), or by directly mirroring the mediaType property (after adding to CommandValue structure).

**Comment by tsconn23** [comment]
`Binary Value []byte` has been added to the Reading

https://github.com/edgexfoundry/go-mod-core-contracts/blob/24a36f294d12b108636e27c6184f22ea24766959/models/reading.go#L38

The `EventClient` should both facilitate the [marshaling](https://github.com/edgexfoundry/go-mod-core-contracts/blob/24a36f294d12b108636e27c6184f22ea24766959/clients/coredata/event.go#L64) of the event and [addition](https://github.com/edgexfoundry/go-mod-core-contracts/blob/24a36f294d12b108636e27c6184f22ea24766959/clients/coredata/event.go#L53) of the event as a byte array.

**Comment by tobiasmo1** [comment]
This is resolved in [PR#293](https://github.com/edgexfoundry/device-sdk-go/pull/293)

**Comment by cloudxxx8** [comment]
As @tobiasmo1 mentioned, this is resolved in PR#293
