### ISSUE TITLE
Implement floating point base64 encoding

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#24]
CommandResult currently does not encode floating point values as base64 strings.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

**Estimated effort**: 2d

**Comment by cloudxxx8** [comment]
fixed by #74
