### ISSUE TITLE
Can't ctrl-c exit from a device service during initialization

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#242]
To reproduce:
- Don't run EdgeX at all
- Modify the configuration.toml to have `ConnectRetries = 10`
- Run `device-simple` 

Now, you can't exit device-simple until after it times out

**Comment by cloudxxx8** [comment]
right, it's a bug.  the service doesn't listen to the OS signal during initialization
thanks for catching it
