### ISSUE TITLE
Remove of DeviceProfile from Device struct

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#244]
To support https://github.com/edgexfoundry/go-mod-core-contracts/issues/27 and https://github.com/edgexfoundry/go-mod-core-contracts/issues/40, SDK should modify the code to query Profile cache for every reference of Device Profile instead of calling device.Profile

**Comment by alexcourouble** [comment]
Is this something I can work on? Or is @difince doing this?

**Comment by tsconn23** [comment]
I have a very specific plan I'm working on with @difince for this effort

**Comment by cloudxxx8** [comment]
This will be implemented with V2 API

**Comment by hahattan** [comment]
This is implemented in v2 core-metadata and device service will adopt it when we finish #528

**Comment by hahattan** [comment]
this is resolved in v2 models and #768
