### ISSUE TITLE
Rename fields within Device Profile's ResourceOperation 

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry/device-sdk-go#245]
Requires Triage

As part of completing earlier name changes in Device Profile (ref issue https://github.com/edgexfoundry/device-sdk-go/issues/168), the ResourceOperation model (and references to these fields in clients such as DS SDK, device services) should be updated for consistency:

1. In go-mod-core-contracts/contracts/models/resourceoperation.go
Rename ResourceOperation.Object -> ResourceOperation.DeviceResource
Rename ResourceOperation.Resource -> ResourceOperation.DeviceCommand

2. Update references to these fields in DS SDK; e.g., https://github.com/edgexfoundry/device-sdk-go/blob/0274f64a751a96cc1ba77f68e07e361ef0a29cf4/internal/provision/profiles.go#L120

**Comment by iain-anderson** [comment]
Agreed in WG 24th Jun that there would be new fields named as above but the old ones would be kept undocumented/deprecated for backward compatibility.

**Comment by iain-anderson** [comment]
depends on https://github.com/edgexfoundry/go-mod-core-contracts/issues/114

**Comment by cloudxxx8** [comment]
I will work on this issue after https://github.com/edgexfoundry/go-mod-core-contracts/pull/127 is merged
