### ISSUE TITLE
Implement All form of GET command endpoint

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#25]
Currently the command endpoint only supports specifying a deviceId. Another form of the endpoint replaces a specific device id with the word "all", which instructs the device service to send the given command to all of it's devices.

**Note** - this form of the command was intended for ease of scheduling periodic readings of all of a device service's devices.  If the device service supports multiple device profiles, then the same command needs to be available in all of them.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

Estimated effort: 3-4d

**Comment by cloudxxx8** [comment]
fixed by #74
