### ISSUE TITLE
Add GoMetaLinter to Makefile

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry/device-sdk-go#250]
[PR#249](https://github.com/edgexfoundry/device-sdk-go/pull/249) performs a clean up of SDK codebase.

To help maintain the condition of the codebase going forward, let's update Makefile to add linting as a regular step in build/test process.

**Comment by anonymouse64** [comment]
In addition to that, similar to other edgexfoundry repos the `make test` target should also check that the code is formatted correctly with `gofmt`. See @lenny-intel's PR at https://github.com/edgexfoundry/go-mod-registry/pull/8 for an example of how this should work
