### ISSUE TITLE
[Proposal] Use command line option to setting the registry path

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#253]
To meet the behavior of C SDK and make users more easy to set up the registry, we suggest to make -r or --registry to input the path string instead of a simple boolean

-r, --registry=[url]

**Comment by lenny-intel** [comment]
Do you also plan to pass in the registry type in the command line? 
i.e. --registry=[type]:[url]

For this to work you will need to parse the value to supply the parts to the Registry Config in https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/config/loader.go
See lines 56 & 58.

**Comment by iain-anderson** [comment]
I'm parsing the URL as [type]://[location]
eg,  consul://localhost:8500

**Comment by cloudxxx8** [comment]
@weichou1229 @FelixTing , after this change is merged, you need to modify the Dockerfile in each device service repository as:
`ENTRYPOINT ["/device-modbus","--registry=true","--profile=docker","--confdir=/res"] `

The point is  "--registry**=true**"

Please refer to https://github.com/edgexfoundry/device-sdk-go/blob/8d4cf2815b71786e68cd86f6f84ece9696cbb71c/example/cmd/device-simple/Dockerfile#L41

**Comment by anonymouse64** [comment]
The snap and all device-service snaps built from the device-sdk-go will also need to be updated with this change

**Comment by tsconn23** [comment]
Re-opening as an agenda item for Device Services WG 30-Sept-19. Discussed during Core WG 26-Sept-19.

@iain-anderson @cloudxxx8 for visibility

**Comment by tsconn23** [comment]
Discussed Device Service WG 30-Sept-19

Order of precedence:
 ENV_VAR_OVERRIDE
--registry=<registry_url> - Use the registry at that url
--registry=Load the value from configuration.toml
no flag - Don't use the registry

**Comment by cloudxxx8** [comment]
what is 
`--registry=Load the value from configuration.toml`
does it mean empty string?

**Comment by tsconn23** [comment]
> what is
> `--registry=Load the value from configuration.toml`
> does it mean empty string?

I updated my comment. Hopefully it's clearer.

**Comment by cloudxxx8** [comment]
thanks, @tsconn23 
@iain-anderson @TomFlem it is the same as my original proposal in #274 
I didn't join the Sep-30 meeting.  Please help confirm whether both of you agree with this approach. If yes, I will make the change

**Comment by iain-anderson** [comment]
The other services allow --registry without a URL, and use the toml in that case. So, we should support the same if we have time to implement it. There's an effort to rationalize the way config works in Geneva and hopefully that will iron out some of the odd behaviors we have at the moment.

**Comment by hahattan** [comment]
> --registry `<Load the value from configuration.toml>`
> no flag - Don't use the registry

Hi I'm working on this issue and a little confused about the difference between no argument and no flag, what exactly does `Don't use the registry` mean ?  
[In the latest release](https://github.com/edgexfoundry/device-sdk-go/blob/7246b081e39c94c1a031e8225182de1f797289b9/internal/config/loader.go#L140) we load the configuration from toml file but didn't push configuration to Registry, does this implementation belong to no argument or no flag ?
