### ISSUE TITLE
Implement resource command chaining

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#26]
Implement device resource command chaining.

Command chaining is when a device resource specifies another device resource in it's Resource Operation as opposed to specifying actual device resource commands.  See the following comment in command.go for more details:

https://github.com/edgexfoundry/device-sdk-go/blob/master/command.go#L150

**Estimated effort**: 2-3d

**Comment by cloudxxx8** [comment]
This feature is powerful, but might make the profile too complicated.
It's hard to detect infinite loop or dead lock

**Comment by iain-anderson** [comment]
Agreed in Levski planning meeting that this would not be implemented. Note that the fields specifying nested device commands were removed in the profile rework for EdgeX 2.0
