### ISSUE TITLE
Implement actuation command support

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#27]
The current SDK only handles querying device readings.  This task is to add command actuation (i.e PUT) support.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

Estimated effort: 5d

**Comment by cloudxxx8** [comment]
fixed by #74
