### ISSUE TITLE
Protocol driver need callback for device changing(CRUD).

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#276]
We need to add a Callback mechanism for device entity changing(CRUD).
For example, MQTT device service subscribes to topics when device service initializes or device is created. Or close the MQTT connection when the device is removed.

**Comment by tobiasmo1** [comment]
We talked about this very briefly during Seoul face-to-face. Could we propose callbacks for ProtocolDriver:

-DeviceInit
-DeviceDiscover
-DeviceUpdate
-DeviceDisconnect (exists)

**Comment by tobiasmo1** [comment]
device-simple01 example adds devices with configuration.toml. As each device gets added on startup, DS SDK initiates **DeviceInitialize** with parameter of the created device (includes dynamically crafted properties name/id, etc.).
We discussed that DeviceDiscovery (or device change CRUD handlers) would be valuable to serve as a template device service authors; e.g., DS SDK provides an opportunity for DS to manually implement device discovery on startup - we could include an example/reference implementation of DeviceDiscovery callback where DS performs scan and registers new devices at regular interval.

Is this issue inclusive of this use case?

**Comment by iain-anderson** [comment]
For consistency with the existing DeviceDisconnect would it be better to have DeviceConnect.
Do we want Update rather than Disconnect followed by Connect? I'm thinking yes because we might have cached data which would still be valid on Update.

**Comment by tobiasmo1** [comment]
Has there been discussion of pros/cons of adding new callbacks to address specific states (DeviceConnect, DeviceDisable, etc.). Or alternately, it may be advantageous to replace DeviceDisconnect with a more inclusive callback (such as **Update**) that allows DS author to be notified and take proper action upon any device state change (connected, disconnected, disabled, other _state_ changes). To me 'update' suggests that potentially more than simply state has been modified.

**Comment by iain-anderson** [comment]
What can actually be modified on a device?

- Device is created
- Device is deleted
- Device is moved to another device service (similar to delete but not necessarily handled the same)
- Changed to a different device profile (is this possible? sensible?)
- Changes to the device profile itself
- New location - updated ProfileProperties
- Administrative State change
- Operating State change
- Automatic Events changes

plus various informational metadata that we probably don't need to worry about - description etc.
Ideally most of this would be handled within the SDK, the question is what does the protocol driver need to know.

**Comment by cloudxxx8** [comment]
@tobiasmo1 I thought we need some clear use case for device discovery, but these callbacks could be leveraged by device discovery in the future.  Basically, when a new device is discovered, the DeviceConnect (or Add) would be called in the driver.

@iain-anderson I thought most of the cases you listed could be covered by DeviceUpdate, and I don't think the protocol driver should know the Profile change because there is no Profile information in driver now.  Attributes are all passed in, and the Profile will be decoupled from the Device object.

**Comment by cloudxxx8** [comment]
Overall, I believe we only need to add the following callbacks:

- DeviceConnect (for add, if we keep DeviceDisconnect as the name)
- DeviceUpdate

Make DeviceUpdate inclusive everything might cause the implementation difficulties to driver providers.

**Comment by tobiasmo1** [comment]
This should enable ProtocolDriver to handle external influences on DS-managed devices. Parameters sent by DSDK to these methods need elaboration.

**Comment by cloudxxx8** [comment]
I just noticed the disconnect method name is `DisconnectDevice`, so the design would be:
- ConnectDevice(deviceName string, protocols map[string]contract.ProtocolProperties) error
- UpdateDevice(deviceName string, protocols map[string]contract.ProtocolProperties) error

**Comment by iain-anderson** [comment]
email from Daniel Harms at Dell:

> I have been working on a device service for IP cameras that is meant to asynchronously feed analytics events from the camera (motion detected, tampering detected, etc) into EdgeX as events/readings.  I use the Go SDK's AsyncValues channel inside the Driver struct to get these readings to EdgeX, and it works great.
> 
> One thing I've had to workaround in my device service is the lack of any per-device bootstrapping/initialization built into the SDK.  Because I'd like the analytics events to be proactively sent to EdgeX (polling every second is wasteful, and polling less frequently risks missed events) I need the device service to spin up a listener goroutine for each camera.  Initializing this goroutine should happen whenever a device is added, or for all devices upon boot.
> 
> I'm currently using the following workaround suggested by Cloud:
> 
>     1. When the Device Service starts up, Initialize function is called, and get all the existing Devices to run the initialization logic.  Create a map to store the Devices have been initialized.
>     2. Whenever the HandleReadCommands or HandleWriteCommands is called, check whether the Device is initialized by Device name from the map in step 1.  If no, initialize it and store it into the map.  If yes, just execute the command.
>     3. Be care of the concurrency issue of handling the map
> 
> 
> This flow seems to be working for me, but I believe that this requirement won't be unique to my protocol in the future, and it would be very helpful to have some support for a routine that runs once for each device built into the SDK.
>

**Comment by iain-anderson** [comment]
I think we have this covered with Connect/Disconnect/Update as suggested above. Is the call to get all devices usable during the initialize callback or does the DS implementation have to wait until service startup is complete?

**Comment by iain-anderson** [comment]
@cloudxxx8 We probably want to pass AdminState in the Connect and Update methods. The driver will want to "mute" the device if it gets put into the LOCKED state

**Comment by cloudxxx8** [comment]
@iain-anderson since the driver can get deviceName, it can retrieve the whole Device from cache and get the AdminState.  we might not need to pass additional field to it.

**Comment by iain-anderson** [comment]
I'm thinking that the driver is going to often want the Protocols and the AdminState, and rarely anything else, so we could pass both in the method. Is that an okay assumption?

**Comment by cloudxxx8** [comment]
In today's working group meeting, we proposed:

- ConnectDevice(deviceName string, protocols map[string]contract.ProtocolProperties, adminState contract.AdminState) error
- UpdateDevice(deviceName string, protocols map[string]contract.ProtocolProperties, adminState contract.AdminState) error
- DisconnectDevice(deviceName string, protocols map[string]contract.ProtocolProperties) error

**Comment by tonyespy** [comment]
This looks good to me although two comments:

 * I don't love the usage of "Connect" and "Disconnect" here. As described previously (and in yesterday's working group call) these functions are meant to notify a ProtocolDriver implementation that a new device has been added or an existing device has been removed. Just because the interface used to have a "ConnectDevice" method doesn't mean we need to re-use the same name. What about the case where ConnectDevice is called with adminState=LOCKED? In this case, a ProtocolDriver implementation might choose to add the device to a local map, but not actually establish a connection to the device. Likewise a DS developer could also choose to "disconnect" a device when the adminState changes (via UpdateDevice). 
 * Is there any reason for passing ProtocolProperties on a Disconnect/RemoveDevice call?

**Comment by cloudxxx8** [comment]
@tonyespy I can answer the second comment.  Disconnect/RemoveDevice might need the ProrocolProperties to clean up the real connection for some protocols.  For example, MQTT Device Service should stop listening to a specific topic on a MQTT broker when a MQTT Device is removed.

**Comment by SteveOss** [comment]
@cloudxxx8 Could the device itself not have cached everything it needs to disconnect?

**Comment by cloudxxx8** [comment]
@SteveOss yes, it can retrieve everything from cache, but @iain-anderson metioned

> I'm thinking that the driver is going to often want the Protocols and the AdminState, and rarely anything else, so we could pass both in the method.

we can only pass device name to these three method, and let the driver to retrieve anything it needs from cache

**Comment by iain-anderson** [comment]
The device driver itself could maintain this state, but I'd rather not mandate it. The SDK will have the information to hand as part of its own response to the create/update/remove request.

**Comment by iain-anderson** [comment]
As to names I'm not much keen on Connect/Disconnect either. How about `AddDevice`, `UpdateDevice`, `RemoveDevice` ?

**Comment by cloudxxx8** [comment]
@iain-anderson please help confirm the design

- AddDevice(deviceName string, protocols map[string]contract.ProtocolProperties, adminState contract.AdminState) error
- UpdateDevice(deviceName string, protocols map[string]contract.ProtocolProperties, adminState contract.AdminState) error
- RemoveDevice(deviceName string, protocols map[string]contract.ProtocolProperties) error

or only reserve device name and driver can retrieve any information they need from cache

- AddDevice(deviceName string) error
- UpdateDevice(deviceName string) error
- RemoveDevice(deviceName string) error

**Comment by iain-anderson** [comment]
The former, ie with all the parameters
