### ISSUE TITLE
Update device-simple example

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry/device-sdk-go#285]
Propose that we add the following to res/configuration.toml to highlight how two simple commands. 
* One triggers boolean application/json event (switch)
* Second triggers binary application/cbor event (image)

Also changing the frequency of the AutoEvent to publish a Switch event each 5 seconds. Note that needs to also toggle the value from false->true at some point for better demonstration. Then show the representation using binary every 15 seconds (binary image of a light that is on/off).

**configuration.toml**
```
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Switch"
  [[DeviceList.AutoEvents]]
    Frequency = "15s"
    OnChange = false
    Resource = "Image"
 
```

**Comment by cloudxxx8** [comment]
fixed by #298
