### ISSUE TITLE
Implement discovery logic

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#29]
Implement discovery logic: if discovery endpoint hit, call protocoldriver.scan(), process ScanList, and add new devices that match any provisionwatchers.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

**Estimated  effort:** 5-7d

**Comment by tonyespy** [comment]
See comment in issue #30.

**Comment by tonyespy** [comment]
We discussed during today's WG meeting and it was decided to defer SDK-based dynamic device discovery to Fuji. It was felt that someone should review the original design first, and expand the design to also cover black-listing, before we implement anything.

It also should be noted that a DS can implement dynamic device discovery on its own with both C and Go SDKs.

**Comment by jpwhitemn** [comment]
Agreed per 9/16/2019 WG meeting this is Geneva item with design work in Fuji release.  Probably impacting non-backward compatibility.

**Comment by hahattan** [comment]
resolved in #448
