### ISSUE TITLE
Add settings support for provisionwatchers

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#30]
Dynamically create provisionwatcher instances based on configuration settings so that device services can implement dynamic discovery.

For more details see the [Device Services functional requirements](https://wiki.edgexfoundry.org/download/attachments/7602423/edgex-cali-delhi-device-requirements-v8.pdf?version=1&modificationDate=1533761857000&api=v2) document.

**Estimated effort**: 3d

**Comment by jduranf** [comment]
If it's fine, I will work on it

**Comment by cloudxxx8** [comment]
Sure, thank you very much

**Comment by tonyespy** [comment]
Let's discuss this. I'd prefer for someone to review the original design and document it before we re-implement in Go. For one, I think requiring an endpoint for discovery is overkill, as it'd require the use of the support scheduler. Instead, it'd be simple to add a scan interval to the SDK, so that the DS could be configured to use a sensible interval and the SDK itself would schedule the required polling.

**Comment by cloudxxx8** [comment]
@jduranf agree, they should be implemented together

**Comment by tonyespy** [comment]
We discussed during today's WG meeting and it was decided to defer SDK-based dynamic device discovery to Fuji. It was felt that someone should review the original design first, and expand the design to also cover black-listing, before we implement anything.

It also should be noted that a DS can implement dynamic device discovery on its own with both C and Go SDKs.
