### ISSUE TITLE
How to delete a device profile.

### ISSUE THREAD

**Issue by bus710** [edgexfoundry/device-sdk-go#307]
**TL;TR - Delete the device first**

Originally, I wanted to register the simple device made by the SDK. 

However, I found there is an existing device that has same device name so that I tried to delete the related information. 

With a DELETE request, the device profile ID API (http://localhost:48081/api/v1/deviceprofile/id/DEVICE-PROFILE-ID) returns **Can't delete device profile, the profile is still in use by a device**.
As the response, the device it self should be deleted first. 

With another DELETE request to the device API (http://localhost:48081/api/v1/device/id/DEVICE-ID), the device could be deleted. 
The following DELETE request to the device profile ID API also properly deleted the profile.

The steps could be:
- find devices (GET to http://localhost:48082/api/v1/device)
- delete a target device (DELETE to http://localhost:48081/api/v1/device/id/DEVICE-ID)
- find device profiles (GET to http://localhost:48081/api/v1/deviceprofile)
- delete a target device profile (DELETE to http://localhost:48081/api/v1/deviceprofile/id/DEVICE-PROFILE-ID)

Thanks,

**Comment by cloudxxx8** [comment]
thank you, @bus710 to share all your experience here.
I will tag all your articles a tips label, and it would be easy to search in the future.

**Comment by malepurakesh** [comment]
Thank you @bus710 for sharing your experience, it helped me.
