### ISSUE TITLE
Remove Creation of ValueDescriptors from the SDK

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/device-sdk-go#318]
Currently, value descriptors are [created](https://github.com/edgexfoundry/device-sdk-go/blob/9c16751eb33bbe0a682fe4b2aeae4f8a0e2e1fef/internal/provision/profiles.go#L138) within core-data by the Device Service SDK when a Device Profile is either [created](https://github.com/edgexfoundry/device-sdk-go/blob/9c16751eb33bbe0a682fe4b2aeae4f8a0e2e1fef/managedprofiles.go#L45) or [updated](https://github.com/edgexfoundry/device-sdk-go/blob/9c16751eb33bbe0a682fe4b2aeae4f8a0e2e1fef/managedprofiles.go#L118). This functionality should be moved out of the Device SDK and should be moved to core-metadata. Thus, when core-metadata is asked to [create](https://github.com/edgexfoundry/edgex-go/blob/6b4a598816fcfb16ccd31072baaf3109d13e93f7/internal/core/metadata/rest_deviceprofile.go#L48) or [update](https://github.com/edgexfoundry/edgex-go/blob/6b4a598816fcfb16ccd31072baaf3109d13e93f7/internal/core/metadata/rest_deviceprofile.go#L90) a DeviceProfile, it should also manage the ValueDescriptors in the same manner.

Currently, the Device Service [caches ValueDescriptors](https://github.com/edgexfoundry/device-sdk-go/blob/9c16751eb33bbe0a682fe4b2aeae4f8a0e2e1fef/internal/provision/profiles.go#L133) after it adds each one. I recommend this behavior be changed to cache ValueDescriptors based on the DeviceResources within the DeviceProfile since those serve as the basis for ValueDescriptors.

Related issue https://github.com/edgexfoundry/edgex-go/issues/1471 The work on these two issues should be either closely timed, or else a configuration toggle should be added in order to turn this behavior on/off prior to its removal, pending integration with the Core Services.

**Comment by cloudxxx8** [comment]
@tsconn23 Since only Device has the connection to Device Service, could core-metadata send a callback to Device Service to notify any change happens on Device Profile?  Creation is fine to ignore the callback because there is no Device created for the Profile at that moment, but any update of profile should notify the Device Service associated to related Devices.

**Comment by cloudxxx8** [comment]
It might be a separated issue, and I just think about it because of relating to the Value Descriptor management.

**Comment by tsconn23** [comment]
@cloudxxx8 The way I was thinking of it was the SDK could use the DeviceResources in order to manage its cache without the need for a callback. We know that there's a 1 to 1 mapping between DeviceResources and ValueDescriptors, so why not have the SDK manage that on its own side and eliminate the extra network traffic. Make sense?

**Comment by cloudxxx8** [comment]
@tsconn23 yeah, that's the plan once we remove ValueDescriptors management from Device Service.  However, my concern is that if users update the profile to add additional DeviceResources and core-metadata should also create new corresponding ValueDescriptors in core-data, Device Service SDK might still need a callback to know the changes, or the core-command execution would be failed.

**Comment by tsconn23** [comment]
Device Services WG -- 24-Jun-2019

It appears the Value Descriptor cache is only used by unit tests, so it can probably be removed. @cloudxxx8 to verify.

Also -- clarification from the above meeting. The callback being discussed here pertains to a Device Profile update from the UI. When a profile is updated via the UI, metadata has the responsibility to identify the unique device services for all the devices applicable to the updated profile. The proposed callback will target the device service rather than targeting each specific device.

**Comment by tsconn23** [comment]
@cloudxxx8 @iain-anderson I found that the SDK will handle updates to Device Profiles
https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/handler/callback/profile.go

The only issue I see is that I cannot currently specify which profile has been updated. If I issue a PUT to the Device Service and specify "PROFILE" as an ActionType, the logic above will refresh all of the profiles in the service. This will work, obviously but seems a bit heavy handed. Should we look at adding an ID parameter to the callback? The actual callback handling is done here:

https://github.com/edgexfoundry/device-sdk-go/blob/9c16751eb33bbe0a682fe4b2aeae4f8a0e2e1fef/internal/handler/callback/general.go#L26

**Comment by tsconn23** [comment]
![DeviceProfileUpdate](https://user-images.githubusercontent.com/1342980/60049832-cbcc4980-9694-11e9-9669-cb9bc9a82801.png)

**Comment by cloudxxx8** [comment]
ok, that sounds good to me.  I also thought it a redundant call to get the device or profile by id again

**Comment by tsconn23** [comment]
I have updated the diagram above per discussion in the Core WG this morning. Note that the callback to the Device Service now includes an `item` property. This is because @iain-anderson had the idea to also use this callback for updated devices, eliminating the need to callback to core-metadata when a device is updated. Some generically named property needed to be added to the request to facilitate passing either an updated device or device profile. The device service logic should look to the `type` field to interpret what `item` contains and then unmarshal the string accordingly.

**Comment by tsconn23** [comment]
@cloudxxx8 @iain-anderson It looks like we still have outstanding work on this. I had to pull down the latest device-sdk for some testing today and I notice the logic to create value descriptors hasn't changed. We have [implemented](https://github.com/edgexfoundry/edgex-go/blob/c4034e410266fcbefd481afaac65e066e6aa6419/cmd/core-metadata/res/configuration.toml#L3) the toggle in core-metadata.

Are we waiting on the change to include the the new DeviceProfile definiton as shown in the callback RE: diagram above?

**Comment by cloudxxx8** [comment]
@tsconn23 sorry, I just haven't had time to implement that.
I know you have made the toggle, so I would like to leverage the System Management API to get the configuration from core-meatadata to see whether Device Service should manage ValueDescriptor
