### ISSUE TITLE
./device-simple -r consul://localhost:8500 -c res/  error

### ISSUE THREAD

**Issue by xinminsu** [edgexfoundry/device-sdk-go#322]
1. consul agent -data-dir consul_data/ -node=127.0.0.1 -bind=127.0.0.1 -datacenter=dcl -ui -client=0.0.0.0 -server -bootstrap-expect 1

2../core-config-seed-go -c true
res/configuration.toml
+ConfigPath = 'edgex/core/1.0'
+GlobalPrefix = 'edgex/core/1.0'

3.after add -r ture in each launch line then 
make run  

4.cd device-sdk-go/example/cmd/device-simple
./device-simple -r consul://localhost:8500 -c res/

get
Init: useRegistry: consul://localhost:8500 profile:  confDir: res/
Check registry is up... http://localhost:8500
Register in registry...
Calling service.Start.
EnableRemote is false, using local log file
level=INFO ts=2019-06-25T05:50:06.78091076Z app=device-simple source=init.go:137 msg="Check Metadata service's status ..."
level=INFO ts=2019-06-25T05:50:06.780933864Z app=device-simple source=init.go:137 msg="Check Data service's status ..."
level=INFO ts=2019-06-25T05:50:06.853930264Z app=device-simple source=init.go:47 msg="Service clients initialize successful."
level=INFO ts=2019-06-25T05:50:06.894753302Z app=device-simple source=loader.go:237 msg="listen for config changes from Registry"
level=INFO ts=2019-06-25T05:50:06.898096435Z app=device-simple source=service.go:149 msg="Device Service device-simple exists"
level=INFO ts=2019-06-25T05:50:06.938283535Z app=device-simple source=loader.go:261 msg="Writeable configuration has been updated. Setting log level to INFO"
level=ERROR ts=2019-06-25T05:50:06.988117686Z app=device-simple source=init.go:37 msg="Device cache initialization failed: Name cannot be blank"
level=ERROR ts=2019-06-25T05:50:07.074450407Z app=device-simple source=profiles.go:44 msg="couldn't read Device Profile from Core Metadata: Name cannot be blank"
error: Failed to create the pre-defined Device Profiles

**Comment by cloudxxx8** [comment]
may I see what your configuration.toml is?

**Comment by xinminsu** [comment]
configuration.toml:
[Writable]
LogLevel = 'INFO'

[Service]
Host = "localhost"
Port = 49990
ConnectRetries = 20
Labels = []
OpenMsg = "device simple started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-simple.log"

# Pre-define Devices
[[DeviceList]]
  Name = "Device-adsb"
  Profile = "Device-adsb"
  Description = "Device adsb in sdr"
  Labels = [ "industrial" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "simple01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "10s"
    OnChange = false
    Resource = "Switch"
  [[DeviceList.AutoEvents]]
    Frequency = "30s"
    OnChange = false
    Resource = "Image"

**Comment by cloudxxx8** [comment]
After looking into the code, there might a Command in one of your profile contains empty name.  Could you please show your profile or the result of http://localhost:48081/api/v1/deviceprofile

**Comment by xinminsu** [comment]
@cloudxxx8 thank you.
Device adsb in result of http://localhost:48081/api/v1/deviceprofile is
{
	"created": 1561106910343,
	"modified": 1561106910343,
	"description": "Device adsb in sdr",
	"id": "cc0c4f05-9621-40d7-96a0-2acb3d2c649b",
	"name": "Device-adsb",
	"manufacturer": "Bigxiong Tech",
	"model": "DA-01",
	"labels": ["modbus"],
	"deviceResources": [{
		"description": "Switch On/Off.",
		"name": "SwitchButton",
		"properties": {
			"value": {
				"type": "Bool",
				"readWrite": "RW"
			},
			"units": {
				"type": "String",
				"readWrite": "R",
				"defaultValue": "On/Off"
			}
		}
	}, {
		"description": "Visual representation of Switch state.",
		"name": "Image",
		"properties": {
			"value": {
				"type": "Binary",
				"readWrite": "R"
			},
			"units": {
				"type": "Binary",
				"readWrite": "R",
				"defaultValue": "On/Off"
			}
		}
	}],
	"deviceCommands": [{
		"name": "Switch",
		"get": [{
			"operation": "get",
			"object": "SwitchButton"
		}],
		"set": [{
			"operation": "set",
			"object": "SwitchButton"
		}]
	}, {
		"name": "Image",
		"get": [{
			"operation": "get",
			"object": "Image"
		}]
	}],
	"coreCommands": [{
		"id": "07d13159-1369-455c-825f-a91596fdc4cb",
		"name": "Switch",
		"get": {
			"path": "/api/v1/device/{deviceId}/SwitchButton",
			"responses": [{
				"code": "503",
				"description": "service unavailable"
			}]
		},
		"put": {
			"path": "/api/v1/device/{deviceId}/SwitchButton",
			"parameterNames": ["SwitchButton"]
		}
	}, {
		"id": "53a8bf1a-f32c-4fd2-aefc-a32425ccd3fe",
		"name": "Image",
		"get": {
			"path": "/api/v1/device/{deviceId}/Image",
			"responses": [{
				"code": "200",
				"description": "CBOR encoded image transmitted as event to Core-Data",
				"expectedValues": ["Image"]
			}, {
				"code": "500",
				"description": "Internal Server Error"
			}]
		},
		"put": {}
	}]
}

**Comment by cloudxxx8** [comment]
http://localhost:48081/api/v1/deviceprofile might contain other result, not only adsb.
Could you please provide all of them? Or, just check whether there is any coreCommand name is empty string.

**Comment by cloudxxx8** [comment]
Please list your version, environment and all the recreate steps.
