### ISSUE TITLE
Override Configuration Using Environment Variables

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/device-sdk-go#323]
# 🚀 Feature Request

### Description

Enable ability to override service configuration using environment variables.  This is the generally accepted mechanism to inject variation when instantiating a container.

My specific use case -- a Helm Chart to support the management of multiple instances of EdgeX in a Kubernetes cluster -- precludes use of the containerized `configuration.toml` files.  Further, unlike edgex-go core services, DSSDK-based services do not seed the registry by default.  Because each instance of EdgeX must have its own uniquely named Kubernetes service to facilitate inter-instance communication, any EdgeX service that communicates with another would need its configuration updated with that unique instance/service name.

edgex-go core services were modified to support this functionality in https://github.com/edgexfoundry/edgex-go/issues/1450.

### Describe the solution you'd like

- Support environment variable override of DSSDK's RegistryService Host, Port, and Type fields to allow a containerized service instance to be pointed at an alternate registry location.

- Support environment variable overrides for when the DSSDK uploads its  `configuration.toml` content to the registry because it does not already exist there.  This is the equivalent of the config-seed implementation of this feature in edgex-go.

**Comment by iain-anderson** [comment]
Should we make the device services be more like the others with respect to config-seed behavior: If there is no config in the registry, populate a default set of values, with overrides from the environment variables.

**Comment by michaelestrin** [comment]
@iain-anderson Not sure if you're suggesting a separate config-seed-equivalent process.  

Currently, if the registry command line option is provided and no service configuration exists in the registry, the DSSDK will populate the registry with the configuration obtained from the local `configuration.toml` file.

Is this the desired behavior or are you suggesting some alternative behavior?

**Comment by iain-anderson** [comment]
I'm thinking that config-seed sets up the registry based on defaults and the DSs should do something similar. What they have now requires the local file the first time you run them with the registry option. I agree with the idea that the DS should be doing that population, rather than config-seed or another process like it.

**Comment by michaelestrin** [comment]
@iain-anderson How does what you're thinking should happen and what is currently implemented differ?

**Comment by iain-anderson** [comment]
The registry if found to be empty is populated with:
Now - settings from a .toml file. This must exist, but its location may be specified on the commandline
With this issue - as above but with environment variables overriding settings
As I'd like - default values hardcoded in the DS, with environment variables overriding them.

**Comment by SteveOss** [comment]
The argument for removing the toml files for default configuration, and hard coding these into a
service, is that the toml file is not really accessible to the user. If a user wants to change the defaults,
then can either set environment variables or modify the values in the registry.

**Comment by michaelestrin** [comment]
The decision was made in today's Core WG call to defer the larger conversation around how to handle default configuration across the entirety of the system.  Consensus was for me to complete the environment variable configuration override work without tackling the removal of toml files.

**Comment by iain-anderson** [comment]
I realize I'm coming to this late, but in the DS we've been using a URL to specify registry, the reasons being that it makes for a single setting rather than three, and it also allows the potential for future registry implementations that don't fit the type/host/port pattern

**Comment by michaelestrin** [comment]
> the DS we've been using a URL to specify registry

I implemented as three separate settings -- edgex_registry_host, edgex_registry_port, and
edgex_registry_type -- intentionally so as to be consistent with the edgex-go core implementation
(see edgexfoundry/edgex-go#1450) which consumes the registry service but does not use the command-line registry flag in the same way as the DSSDK.  

I understand your implicit ask to be change the existing and/or add a new single environment variable setting that specifies the override url (equivalent to the content of the registry command-line flag's value).

Shouldn't the use of the registry flag and the environment variable override variable names/usage be consistent across the EdgeX ecosystem?

**Comment by SteveOss** [comment]
I think it's obvious that the answer to the above is "yes". So perhaps the discussion should be as to the
common form adopted.

**Comment by SteveOss** [comment]
Forgot to say that IMHO, should attempt to represent one logical configuration element as one (as opposed
to multiple) configuration variables.

**Comment by akramtexas** [comment]
Good points, Steve. I do wish to bring attention back to a (the?) central
point that came up earlier in this thread, where Michael pointed out that "*The
decision was made in today's Core WG call to defer the larger conversation
around how to handle default configuration across the entirety of the
system*..."

To the latter point, I believe it's been captured yesterday (in the Core WG
meeting minutes) as a "*Discussion item for future meetings – green field
notions of service configuration*". So that will be a larger discussion in
which we revisit some central, underlying notions regarding whether
configuration lives with the service, immutably packaged into the
artifact(s)? Or is configuration "mediated" by the control plane, able to
adapt dynamically to live conditions, and providing an additional way to
control services? Is there a hybrid approach? Etc.

 ~Akram

*Akram Ahmad*
Principal Software Engineer
*Dell Technologies *| IoT Solutions Division
*Mobile/Text +1 763-670-8082*
Akram_Ahmad@Dell.com

**Comment by SteveOss** [comment]
Am looking forward to the wider discussion, but that does not preclude discussing some of the issues ahead of time IMHO.

**Comment by michaelestrin** [comment]
> that does not preclude discussing some of the issues ahead of time

Agreed though I'm not sure this issue is the best place to host an ecosystem-wide discussion.  

Is there an objection to merging the PR as-is with the intent to follow with a post-discussion set of PRs across the ecosystem to normalize implementation across all services?

**Comment by iain-anderson** [comment]
OK, it's easy enough changed

**Comment by iain-anderson** [comment]
Closed via #328
