### ISSUE TITLE
No way to use same logging client as service messages before service Start

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#326]
Currently, if you encounter errors/issues in setting up a `ProtocolDriver` before calling `startup.Bootstrap` or `Start` on a service there's no way to use the same logging client to issue warnings or errors as what's used from within the SDK unless you create an object with the same arguments which it's not clear to me if this is supported or not by the logging client. The logging client is only provided during the Initialize method of the ProtocolDriver. 

I think that the LoggingClient should be exposed in some way after the service is at least created with `device.NewService`.

**Comment by cloudxxx8** [comment]
before creating the Logging client, we can only use fmt to print out the log to stdout or stderr

**Comment by anonymouse64** [comment]
Yes but I'm saying it should be created earlier so it can be used as early as possible

**Comment by tsconn23** [comment]
From core services
https://github.com/edgexfoundry/edgex-go/blob/0bb6f38d41c1fd7c43a982641d64e8fe591cccf2/cmd/core-data/main.go#L79

**Comment by anonymouse64** [comment]
@tsconn23 what are the implications of creating a logger client twice with the same service key? What if I wanted to simply print off debug/info messages and not completely error out?

**Comment by tsconn23** [comment]
The logger in this case is just scoped to the function so it'll be GC'ed when the function exits. No problem as far as service key naming. If you want a different level of messaging, then you could either change the function to log at that level by default or otherwise pass the desired level in as a param.

**Comment by anonymouse64** [comment]
So basically the suggestion here then is to:
* create a logger with the same service key
* garbage collect or otherwise delete that logger instance before calling `service.Start`

Additionally, how does one hookup the logger instance with the remote logging setup like what happens here: 

https://github.com/edgexfoundry/device-sdk-go/blob/d1865f01213a505f6a4432c9b99b4cbb6bcb14f4/internal/clients/init.go#L74-L87

In order to fully follow the suggestion and create the logger client independently of the SDK before `service.Start` is called, I would then also need to somehow read in the configuration toml, again duplicating the logic the SDK is already doing. Accessing the driver configuration toml is already mentioned here: https://github.com/edgexfoundry/device-sdk-go/issues/324

**Comment by tsconn23** [comment]
>Additionally, how does one hookup the logger instance with the remote logging setup

In the example provided above, remote logging isn't an option since we've not read the config yet. Logging just goes to StdOut. What if in the edge case the support-logging service hasn't bootstrapped yet or is down? If you want to do remote logging, then you're working on a different requirement.

**Comment by anonymouse64** [comment]
Sure in that scenario you can't use remote logging, but for a generic device service I don't think that assertion holds.

For example in my case, I might need to have the driver config control whether to talk directly to the Linux kernel for Bluetooth devices or use something like bluez. There are many other configuration items which are:

- not protocol or device specific (i.e. doesn't belong in a device's protocol spec)
- needed to setup things that are common to all devices in the device service (for example some kind of Singleton object creation that is shared amongst all devices in the service implementation)
- useful to setup the protocol driver that is passed to service.Start or service.Bootstrap

As such, it seems that if I wanted to use remote logging with a device service and also perform device service specific setup that may trigger warnings or errors _before_ starting the SDK service with service.Start or service.Bootstrap I can't configure my device service to allow a user to choose that from the configuration.toml

What I have been advocating for in this issue and in the other one is that I think there should be a way from the SDK before starting the service loop itself to run a minimal amount of device service setup including the following tasks:
- read configuration.toml
- create various module clients, such as the logger (this issue) registry client, core-metadata, client from core-contracts etc. to be used by the SDK service

What I think I should make clear is that this issue is about usability of the SDK. Yes I could technically workaround this issue by parsing the configuration.toml myself and also pass in all the relevant arguments to create a logger and then delete it before starting the service SDK loop, but I think that since the SDK already knows how to do these things, they should just be exposed in a more usable way. The SDK should make it easier.

**Comment by cloudxxx8** [comment]
@anonymouse64 we might have fixed this issue in #432
please help verify it.  thanks

**Comment by anonymouse64** [comment]
unfortunately I don't have the bandwidth to look into this at all, sorry. [My repo](https://github.com/anonymouse64/device-thingy52/tree/master) is still available if someone wants to take a stab at updating it to "do the right thing" with the updated sdk methods, patches welcome :smile:

**Comment by cloudxxx8** [comment]
we are going to remove Logging Service, and it will be cleaned up in
https://github.com/edgexfoundry/device-sdk-go/issues/544
