### ISSUE TITLE
Example device-simple snap should expose an app to run device service interactively

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#337]
Since the device-simple snap is meant to be a learning tool and show how to develop device services, it would be useful to be able to run the command from the snap that is built directly in the terminal and see the output while adjusting arguments, etc.

Currently the snap only has a service which is somewhat hidden from the user behind `snap logs` and `snap services`.

**Comment by iain-anderson** [comment]
closing as per discussion in WG on 6th June
