### ISSUE TITLE
Port device-simple snap to the edinburgh branch?

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#338]
I'm wondering if it makes sense for us to also provide snap packaging on the edinburgh branch here. It's not clear to me that there's significant changes now between master + edinburgh, but if there will be in the future then it would be nice for folks learning how to build device service snaps to create an edinburgh specific device-simple snap rather than always have to follow master or build against Fuji. 

@tonyespy what do you think?

**Comment by tonyespy** [comment]
Based on our recent versioning discussion in the devices WG, I'm not sure it actually makes any sense for us to release anything on the edinburgh branch, as we've said that the major release of the SDKs will correspond to the major release of EdgeX. So if/when the next release of device-sdk-go is minted, it'll be 1.1, and it will be compatible with both Edinburgh and Fuji. As for snap packaging, I'll totally fine with leaving it just on master.
