### ISSUE TITLE
Precision lost after transformation with scale

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#339]
We got lots of use cases when the type of Device Resource is integer with a float scale, such as 0.01, and the precision lost after transformation.  It is the usual case in Modbus devices.
For example, 
http://ftp.icpdas.com/pub/cd/usbcd/napdos/dl_100/DL100TM485/Documents/DL_100TM485_V102.pdf
![image](https://user-images.githubusercontent.com/11695863/62216912-3c752d00-b3dc-11e9-976f-8126418706d3.png)

The temperature and humidity are both stored in int16 data type in the Modbus device with the scale 0.01.  If the temperature is 26.53, the read value will be 2653.  After transformation in SDK, it becomes 26 and lost 0.53.  The worse case is mentioned on the slack
https://edgexfoundry.slack.com/archives/CE44YG81E/p1558527994093400

The result might be 0.2 and it always becomes 0.  We need a way to make the device resource data type different from the value descriptor data type.

**Comment by cloudxxx8** [comment]
My proposed solution is to add a field "valueDescriptorType" in property value.
https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/propertyvalue.go

If it is empty, keep the same behavior.  If it is not empty, it will be the data type of value descriptor and reading value data type after transform.

**Comment by iain-anderson** [comment]
I think for this scenario we should make the PropertyValue Type (and therefore the type in the valuedescriptor) a float. What we then want is a way of telling the device driver that the data that it needs to retrieve from the device is actually an int16.
At the moment we can achieve this by defining an Attribute that will contain this information, but Attributes are specific to individual device services - better would be to have, as you say, an additional field in PropertyValue. I'd suggest deviceDatatype or similar.

**Comment by cloudxxx8** [comment]
ok, deviceDataType is for the device internally, and the original "type" is for the valueDescriptor.
If deviceDataType is empty, everything works as before.

**Comment by iain-anderson** [comment]
As raised in the WG meeting, the trouble with introducing a new field in PropertyValue is that the potential values that it can take are specific to a device class anyway. Bluetooth GATT for example defines many more datatypes than are used in Modbus. So on reflection I'd keep doing things the way we are: the device service defines an Attribute to be provided in the device profile, which indicates the native type to be retrieved from the device (if it cannot be correctly inferred from the EdgeX type).

**Comment by cloudxxx8** [comment]
We are implementing it in
https://github.com/edgexfoundry/device-modbus-go/issues/78

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/device-modbus-go/pull/80
