### ISSUE TITLE
How to fix this error: "mgoGetAddressableById Invalid Object ID"

### ISSUE THREAD

**Issue by lcq987** [edgexfoundry/device-sdk-go#340]
I have followed the official document step by step, but when I run "./device-simple" command, it always occur "Add Device failed RandNum-Device01, error: 400 - mgoGetAddressableById Invalid object ID : A device must be associated to an Addressable\n". I know a device must associated to an addressable object, but I don't how to modify my configuration.toml.

**Comment by cloudxxx8** [comment]
@lcq987 may I know which version you are running?
for the latest version, there is no need to create Addressable in Device

**Comment by lcq987** [comment]
I think it is the latest version, but if there is no need to create Addressable in Device, how can device associated with its own addressable?

**Comment by cloudxxx8** [comment]
The device is not associated with the addressable in the latest version.
How do you run it?
In the configuration.toml, you just need to define the protocol driver without addressable as the example on GitHub
https://github.com/edgexfoundry/device-sdk-go/blob/master/example/cmd/device-simple/res/configuration.toml#L63-L64

**Comment by lcq987** [comment]
Sorry,I made a mistake. the version I used is v0.7.1, where can I download latest docker-compose.yml file?

**Comment by cloudxxx8** [comment]
Please use the edinburgh release folder
https://github.com/edgexfoundry/developer-scripts/tree/master/releases

If you want to use master, please use the nightly-build, but it might not be stable

**Comment by lcq987** [comment]
thanks!!!

**Comment by cloudxxx8** [comment]
@lcq987 no problem.  please close this issue if you confirm it works fine
