### ISSUE TITLE
Add option for device services to "overwrite" consul with local configuration changes

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#342]
In device service snaps, we have been creating examples where the service is configured to always use consul, as well as specify the configuration.toml in the command line options/arguments. This is because the command line arguments for services is not easily modified for snaps, and we want to make it work in the easiest way possible... 

This setup has the net effect that when a device service is initially installed and started for the first time, it will try to read from consul, then not find anything for the device service and instead import the configuration.toml file specified for the snap (usually at `$SNAP_DATA/config/device-service/res/configuration.toml`) into consul.

On all subsequent runs of the service, it will use the configuration from consul and ignore the local configuration.toml file, which is expected. This is unfortunate however if a user is developing a service or otherwise needing to make many changes to the configuration because they all need to be made in consul instead of in the configuration.toml file which is usually quicker/easier to edit. Furthermore, if a user makes changes the configuration.toml, expecting the service to be updated, it will take a bit of exploration to determine that the service is importing all it's configuration from consul and ignoring the local files.

What we did to solve this problem for the snap is to add a command called `push-config` to the snap which just calls config-seed with a special `-overwrite` flag which will overwrite the configuration in consul with what's in the configuration.toml file. 

I propose we add a similar overwrite option flag to the device SDK to easily enable creating this kind of app which a user runs after modifying their configuration.toml locally to push it into consul. This would also make it easy for someone who wants to make their device service always use configuration.toml files, but make the configuration also available in consul for other purposes (i.e. maybe so a management agent can report the configuration back to some other metrics/config database).

**Comment by iain-anderson** [comment]
If there was an option on edgex-cli to upload a config file (or to change an individual value) would that be useful?

**Comment by anonymouse64** [comment]
Yes that would be independently useful but I don't think that would replace my request here. I don't want to have to install another tool just to push the configuration.toml into consul for my device service.

**Comment by cloudxxx8** [comment]
@iain-anderson and @anonymouse64 ,  let's discuss in the working group meeting.  If we all agree with adding this argument, I can implement it easily.
However, `--overwrite` is not a clear flag to me.  Do you have better idea?  How about `--overwrite-config`?

**Comment by anonymouse64** [comment]
I only propose --overrride because it matches config-seed in edgex-go

**Comment by anonymouse64** [comment]
Upstream edgex-go issues/commits/PRs for context: 

- https://github.com/edgexfoundry/edgex-go/pull/902 is the PR that added --overwrite to config-seed (which itself was triggered from https://github.com/edgexfoundry/edgex-go/issues/827)
- https://github.com/edgexfoundry/edgex-go/issues/922 is the issue I have for explaining a bit of the same background around usage of this option within the edgexfoundry snap, and what we ended up implementing in the snap with https://github.com/edgexfoundry/edgex-go/pull/1319/commits/67dc4666098777fb126218c86539c2088f8b74b0

**Comment by cloudxxx8** [comment]
closed by #383
