### ISSUE TITLE
NewBinaryValue() and NewCommandValue() with type Binary behave differently

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/device-sdk-go#345]
See:

https://github.com/edgexfoundry/device-sdk-go/blob/master/pkg/models/commandvalue.go#L226

One pathway includes a call to `encodeBinaryValue()` and one does not, leaving events created in these separate ways incompatible.

**Comment by tobiasmo1** [comment]
These should create compatible values. With changes to this logic, be sure to add tests to express and confirm resulting behavior. As I recall, the NewCommandValue method is invoked during creation of values originating from a device's resource operation (typically static values loaded during startup), whereas the NewBinaryValue is prepared at runtime by device service's command handler (called by HandleReadCommand in response to command(s) at runtime).

**Comment by lenny-intel** [comment]
I have also run into this with my REST device service attempting to support binary data. 

My case is `NewBinaryValue()` doesn't call `encodeBinaryValue()`, but `BinaryValue()` in unit tests calls `decodeBinaryValue()`. 

`NewBinaryValue()`  needs to call `encodeBinaryValue()`

**Comment by lenny-intel** [comment]
I switched to using `NewCommandValue()` rather than the individual New<type>Value() calls and now all consistent encoding for my use. :-)

**Comment by jdharms** [comment]
@lenny-intel `NewCommandValue()` should *not* call `encodeBinaryValue()`, as far as I know.  Further down the line `encodeBinaryValue()` is called by the SDK, which essentially double-encodes the value.  It's possible things may have changed in the SDK since I last looked into this, but that was the state when I created this issue.

**Comment by lenny-intel** [comment]
@jdharms , The SDK's `NewCommandValue()` does call `encodeBinaryValue()`, which is why it is now working for me. There is no double encoding.

**Comment by jdharms** [comment]
I dug in a little more to try to page back the context. `event.CBOR()` calls `encodeAsCBOR()` to encode the CBOR payload.

restfuncs:commandFunc() calls `event.HasBinaryValue()` to determine whether or not `EventClient.MarshalEvent()` should be called to CBOR encode the event (using the two functions listed above).

If you are creating your Binary CVs using NewCommandValue, the `.BinValue` field will be set to a CBOR encoded value, which will then get marshaled again into CBOR via the call to `event.CBOR()` in `eventRestClient.MarshalEvent()`

Out of curiosity, how are you decoding your CBOR events?

AFAIK, and @tobiasmo1 please jump in if I'm wrong, you should *not* be using the `NewCommandValue()` function as a DS author. It's used by the SDK to create CommandValues to pass to the DS, but shouldn't be used in the other direction.  The incompatibility of binary CVs created across the two functions is evidence of this--intentional or not.

**Comment by lenny-intel** [comment]
@jdharms , ahh yes the binary value should never be encodes as we are CBOR encoding the whole event/reading. Good catch!

**Comment by jdharms** [comment]
Yes, that’s my understanding as well.  You’re right on the decode part,
though. My pr seems incomplete at the moment.
