### ISSUE TITLE
Move version number from /ping to /version API

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#347]
Currently, the version number is returned by /ping, but it is not consistent with edgex-go.  We discussed to use /version instead.  Thus, /ping should returns "pong", and /version returns the plain text version number.

**Comment by iain-anderson** [comment]
Should return the version in application/json (see eg https://github.com/edgexfoundry/edgex-go/blob/86c40c7972745d23b935c2c300b436537df68d8d/internal/pkg/version.go#L24).
In the CSDK I've also put the sdk version in, in case it may help in issue diagnostics

**Comment by cloudxxx8** [comment]
In the discussion of WG meeting, we decide to keep the response of /ping as is.
