### ISSUE TITLE
Don't pass query parameters with prefix "ds-" to ProtocolDriver

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#354]
Support was recently added to the SDK to pass query parameters received on GET requests to the ProtocolDriver via the attributes map.

As there are some potential use cases for query parameters which impact the operation of the SDK's core logic itself (eg. don't send JSON reply, don't push to Core Data, ...), it was decided that query parameters reserved for the SDK would be name-spaced by appending a prefix "ds-" (note, "sdk-" was initially proposed, but I think "ds-" is a better fit).

This issue should be resolved before the next release of the SDK so that people don't start using query parameters and wonder why parameters with the prefix aren't being passed through to their ProtocolDriver.

See the following PR for reference:

https://github.com/edgexfoundry/device-sdk-go/pull/336

**Comment by cloudxxx8** [comment]
The current implementation is to pass the whole query string to the protocol driver without parsing it.  Is it necessary to remove all the "ds-*" from the raw query string?

**Comment by tonyespy** [comment]
Yes, that's correct. @iain-anderson do you agree?
