### ISSUE TITLE
Provide example of aggregating device resources

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-go#355]
In addition to the existing example device service, a new one simulating e.g. a 3-axis gyroscope.
This will illustrate the use of the deviceCommands section in a device profile. We should also remove the deviceCommands for the existing example as they don't do anything.

**Comment by cloudxxx8** [comment]
There is a quick design to enhance the device-simple:

- add three device resource as int16 type: x-value, y-value, and z-value
- add a device command called 3-axis and aggregate all three values
- the 3-axis device command supports both get and put command

Please see whether this design is acceptable

**Comment by iain-anderson** [comment]
Sounds okay. For information here is the profile for the corresponding example in CSDK. It's meant to represent a sensor so it's read-only.

[Gyro.yaml.txt](https://github.com/edgexfoundry/device-sdk-go/files/3545527/Gyro.yaml.txt)
