### ISSUE TITLE
Add update callback of deviceprofile for protocol driver

### ISSUE THREAD

**Issue by nbfhscl** [edgexfoundry/device-sdk-go#365]
I'm working on an opcua device service which monitors nodes base on deviceprofile. It needs to CUD the monitorItem whenever the deviceresource in deviceprofile updates. Now that you have added CUD callbacks for device, what about add a update callback for deviceprofile?

**Comment by cloudxxx8** [comment]
Device Profile doesn't link to Device Service directly.  We need to find a good way to implement the update callback for Device Profile

**Comment by cloudxxx8** [comment]
@tsconn23 is it possible to make a callback to Device Service when a Device Profile is updated. It needs to retrieve all the associated Devices and get all the related Device Services.

**Comment by nbfhscl** [comment]
I think the callback of Device Profile to all related Device Service has already been implemented by metadata.

**Comment by cloudxxx8** [comment]
Got it
Then, we can implement the callback in Device Service SDK
@iain-anderson does C SDK provide this callback?

**Comment by iain-anderson** [comment]
It does not. But we did decide that Profiles are not permitted to be updated if there are Devices using them, so if you discard your cached profile when the last relevant device is removed, you should always be up-to-date.

**Comment by cloudxxx8** [comment]
yeah...I forgot it

**Comment by nbfhscl** [comment]
What bad is going to happen if Profiles were updated when there are Devices using them?

**Comment by nbfhscl** [comment]
In my case, an opcua server may contains many nodes, and the nodes you want to monitor(subscribe) may increase or decrease. Currently I'm comparing the Profile with the Cache and update the monitorItems based on it.

**Comment by cloudxxx8** [comment]
@nbfhscl if  you are monitoring OPC-UA server from the device service, you can just call UpdateDeviceProfile API and it would update Device Profile in both cache and core-metadata.
Since the update is triggered from the Device Service side, we don't need the callback.

**Comment by nbfhscl** [comment]
@cloudxxx8@iain-anderson, If the Profiles are not permitted to be updated (from the metadata side) when there are Devices using them. Then what's this api for:
`Put http://core-metadata/api/v1/deviceprofile`

**Comment by cloudxxx8** [comment]
@nbfhscl we have figured out the root cause of this issue, and move this to
https://github.com/edgexfoundry/edgex-go/issues/2442

device-sdk-go has nothing can do for this issue
