### ISSUE TITLE
make: *** [cmd/device-simple/device-simple] Error 1

### ISSUE THREAD

**Issue by wassim6975** [edgexfoundry/device-sdk-go#368]
Hello everyone, 

I have a problem when I want to make build device-simple.
Can you help me ? 

Thank you

MacBook-Air-de-wassim:device-simple wassim$ make build
CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/device-simple.Version=1.1.0" -o cmd/device-simple/device-simple ./cmd/device-simple
build github.com/edgexfoundry/edgex-go/device-simple/cmd/device-simple: cannot load github.com/edgexfoundry/device-simple: git ls-remote -q https://github.com/edgexfoundry/device-simple in /Users/wassim/go/pkg/mod/cache/vcs/bbf8e69a3538895a7b56d1a3ab86eda5d501603dba71e3bba2abd37e336b87e5: exit status 128:
	git@github.com: Permission denied (publickey).
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
make: *** [cmd/device-simple/device-simple] Error 1
MacBook-Air-de-wassim:device-simple wassim$

**Comment by tsconn23** [comment]
@wassim6975 You have a problem with your local git configuration. Unrelated to this application.
