### ISSUE TITLE
Update the lastConnected timestamp of the device in core-metadata

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#371]
Since the update might be high frequencies, this feature should be configurable, and the default setting might be disabled.
We could discuss in the working group meeting

**Comment by iain-anderson** [comment]
core-data updates lastConnected attribute, at [event.go:135](https://github.com/edgexfoundry/edgex-go/blob/1e7bb157cf0c15e1831a4e3b03a3216743e1f80d/internal/core/data/event.go#L135). Please reconsider this patch

**Comment by cloudxxx8** [comment]
thanks, @iain-anderson 
@hahattan please remove the code change block in SendEvent func.
I noticed we don't update the lastConnect in Put command.  Please move the logic to Put command.

**Comment by cloudxxx8** [comment]
fixed by #429
