### ISSUE TITLE
Attribution.txt file is out-of-date, update test target to test for out-of-date

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#399]
The Attribution.tx file is missing the following entries:
```
An attribution for github.com/cenkalti/backoff is missing from in  Attribution.txt, please add
An attribution for github.com/davecgh/go-spew is missing from in  Attribution.txt, please add
An attribution for github.com/edgexfoundry/go-mod-core-contracts is missing from in  Attribution.txt, please add
An attribution for github.com/edgexfoundry/go-mod-registry is missing from in  Attribution.txt, please add
An attribution for github.com/go-kit/kit is missing from in  Attribution.txt, please add
An attribution for github.com/go-logfmt/logfmt is missing from in  Attribution.txt, please add
An attribution for github.com/gorilla/context is missing from in  Attribution.txt, please add
An attribution for github.com/kr/logfmt is missing from in  Attribution.txt, please add
An attribution for github.com/mitchellh/consulstructure is missing from in  Attribution.txt, please add
An attribution for github.com/mitchellh/copystructure is missing from in  Attribution.txt, please add
An attribution for github.com/mitchellh/reflectwalk is missing from in  Attribution.txt, please add
An attribution for github.com/pelletier/go-toml is missing from in  Attribution.txt, please add
An attribution for github.com/pmezard/go-difflib is missing from in  Attribution.txt, please add
An attribution for github.com/stretchr/testify is missing from in  Attribution.txt, please add
An attribution for github.com/ugorji/go is missing from in  Attribution.txt, please add
```
The above data was generated by running the `test-attribution-txt.sh` found in `edgex-go/bin/`. Running this and the `test-go-mod-tidy.sh` the script should be added to the makefile `test` target same ass in edge-go and app-service-configurable.

**Comment by anonymouse64** [comment]
Note that attribution.txt files are only meant for delivered binaries, so unless we release a binary or a dynamic library (i.e. some distribution which includes the dependencies) with device-sdk-go this is unnecessary.

**Comment by lenny-intel** [comment]
@anonymouse64 , Per @jpwhitemn it also applies to the SDKs since they are pulled by Devs to build their services.

**Comment by anonymouse64** [comment]
I Am Not A Lawyer, but the Attribution.txt file is providing attribution to 3rd party dependencies that someone who ships software uses. If we don't ship the device SDK in binary form then we don't need to include the Attribution.txt file. AFAIK, the Go SDK is not ever shipped somewhere in a binary way except as services, and there we should have Attribution.txt files. 

Note that the C SDK is in fact shipped as a dynamic library so the Attribution.txt requirement also applies to the C SDK.

**Comment by jpwhitemn** [comment]
At one time, the SDK was copied to create a new service and so we needed the attribution file in it for the copies that got created.  We don't copy anymore, and to @anonymouse64 point, we don't ship the SDK, but I suppose someone could fork or take our SDK and extend it (?? - not sure what the legal ramifications of this would mean).  Unless there is harm in having the attribution file in the SDK, I would say we leave it.  It also provides a good example for those creating new DS and gives a good starter list of 3rd party attributions.

**Comment by anonymouse64** [comment]
> suppose someone could fork or take our SDK and extend it (?? - not sure what the legal ramifications of this would mean)

There are no issues with this, the Apache License already covers this situation and ensures we don't have to do anything when somebody forks and extends the project. 

> It also provides a good example for those creating new DS and gives a good starter list of 3rd party attributions

When it comes to this sort of thing I would rather us not do this because it could be a form of liability for the project that we are not actually legally required to have. For example if we have a list of 3rd party dependencies for the SDK now, and somehow that gets out of date and is wrong and another developer takes that and uses the wrong version for their project and they get sued or something, they could claim that it was our fault because they just copied what we have (no idea what a judge would say to this defense but you get the point). In almost every other situation I'd say sure let's add it because it will help the developer out, but in this instance I would rather the developer of a derivative work be solely responsible so there's no liability on us. This is of course orthogonal to our legal requirements to attribute software we use when we build device services.

**Comment by cloudxxx8** [comment]
In this case, how about removing Attribution.txt from Go SDK to solve this issue?

**Comment by anonymouse64** [comment]
> In this case, how about removing Attribution.txt from Go SDK to solve this issue?

This is what I was advocating for. I think we should only put Attribution.txt files in device services, not the SDK.

**Comment by cloudxxx8** [comment]
@iain-anderson may we discuss and decide this in today's working group meeting?  thanks.

**Comment by iain-anderson** [comment]
There was positive response in the WG meeting to the suggestion that we remove the Attribution file from the top of the repository, but include an example Attribution.txt for the example device service. We should be able to verify the contents of this file in the same way that we do for the real DSs.
