### ISSUE TITLE
The float32 value is different with the value which input by put command

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/device-sdk-go#400]
OS version: ubuntu 18.04
Device SDK version: (Using device virtual 1.1.0)
Environment details: Docker container

Steps to reproduce:
1. Sending put command to the device

```
API : /api/v1/device/fc3289e2-da3d-4ea6-8f4d-aed736cdeff4/GenerateDeviceValue_FLOAT32_RW
Body : {"DeviceValue_FLOAT32_RW":"1.1411858360194436"}
```

2. Retrieve data by get command
```
API: /api/v1/device/fc3289e2-da3d-4ea6-8f4d-aed736cdeff4/GenerateDeviceValue_FLOAT32_RW
Reponse : 
{
    "device": "Test-Device",
    "origin": 1573525575748864288,
    "readings": [
        {
            "origin": 1573525575740928768,
            "device": "Test-Device",
            "name": "DeviceValue_FLOAT32_RW",
            "value": "P5ISYQ=="
        }
    ],
    "EncodedEvent": null
}
```
**Expected result:** 
   Decode value should be the same as put data "1.1411858360194436"
**Actual result:** 
   Decode value: P5ISYQ== is "1.1411858797073364"

**Comment by iain-anderson** [comment]
I think this is as expected: a 32-bit float cannot hold the requested precision

**Comment by cloudxxx8** [comment]
@cherrycl , to test float32, please shorten the test data to 1.14

**Comment by cloudxxx8** [comment]
confirmed work as expected
