### ISSUE TITLE
Overriding Configuration by Environment Variables causes error if the config data type is not string

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#406]
When using Overriding Configuration by Environment Variables if the config value is not string type, it would cause the following error:

> error loading config file: could not marshal configTree to configuration: (0, 0): Can't convert false(string) to bool

It is caused by this func
https://github.com/edgexfoundry/device-sdk-go/blob/4e953d909777d90d184b5b28c71b8b6288bdb857/internal/config/environment.go#L65

Recreate step:
Set an environment variable such as `Logging_EnableRemote=true`
Start device service with `-r` flag

**Comment by iain-anderson** [comment]
This presumably applies for config-seed also?

**Comment by lenny-intel** [comment]
Also applies to App functions SDK.
https://github.com/edgexfoundry/app-functions-sdk-go/issues/149

**Comment by cloudxxx8** [comment]
@hahattan could you please verify whether this issue is fixed after using go-mod-bootstrap

**Comment by lenny-intel** [comment]
Yes, this should be fixed. The NightlyBuild compose files now have  `Logging_EnableRemote: "true"` which would have tripped this error when it tried to set the bool `EnableRemote` field to a string "true". The new bootstrap has code to convert the string values to the proper type.

**Comment by cloudxxx8** [comment]
thanks, @lenny-intel
