### ISSUE TITLE
VERSION vs Version

### ISSUE THREAD

**Issue by RozitaTeymourzadeh** [edgexfoundry/device-sdk-go#407]
When we follow the steps to setup sdk here
https://docs.edgexfoundry.org/Ch-GettingStartedSDK-Go.html

and in command : cp ./device-sdk-go/Version ./device-simple/
The Version file can not be found. Instead, VERSION is available. Please update the documentation or repository to be aligned.

**Comment by cloudxxx8** [comment]
@RozitaTeymourzadeh thanks for reporting this issue.  Since it is a documentation issue, I've moved it to https://github.com/edgexfoundry/edgex-docs/issues/58
