### ISSUE TITLE
mod vs mode

### ISSUE THREAD

**Issue by RozitaTeymourzadeh** [edgexfoundry/device-sdk-go#408]
In documentation here step 4 : 

https://docs.edgexfoundry.org/Ch-GettingStartedSDK-Go.html

The command is: 
GO111MODULE=on go mode init
it should be:

GO111MODULE=on go mod init

Typo on Syntax. Please edit it

**Comment by cloudxxx8** [comment]
@RozitaTeymourzadeh thanks for reporting this.  This is a documentation issue, so I move this to https://github.com/edgexfoundry/edgex-docs/issues/57
