### ISSUE TITLE
Error when accessing deviceCommands or deviceResource through REST API

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-sdk-go#419]
1. 
In device service, if you only define deviceCommands but did not define corresponding coreCommands, there will be an error when calling deviceCommands via device endpoints: `/api/v1/device/name/{name}/{command}` or `/api/v1/device/{id}/{command}`

```
level=ERROR ts=2019-12-05T07:52:13.309919Z app=device-simple source=command.go:72 msg="Switch for Device: Simple-Device01 not found; GET"
```

The root cause is that device service will only check whether incoming request is defined in coreCommand mapping (`ccMap`) in cache:  
https://github.com/edgexfoundry/device-sdk-go/blob/c317e538ac9d78012123289528b65937d6d981c1/internal/cache/profiles.go#L197-L205

If not it will assume the request is trying to access DeviceResource directly and call `execRead/WriteResource` and in this case if deviceCommand name is different from deviceResource name, there would be an error.

To resolve this problem we should reconsider the logic of [CommandExists](https://github.com/edgexfoundry/device-sdk-go/blob/1e86c8aa08f3d791813f32f72efddd3a7e7379cb/internal/cache/profiles.go#L193) function to check whether command exists in either coreCommand or deviceCommand.

2.
If neither deviceCommands nor coreCommands are defined in Device Profile, when you try to access deviceResource through above REST endpoints, there would be error .(especially GET command)
```
level=ERROR ts=2019-12-05T08:59:56.54852Z app=device-simple source=command.go:148 msg="Handler - execReadCmd: getting resource operation failed: specified ResourceOperation by deviceResource SwitchButton not found"
level=ERROR ts=2019-12-05T08:59:56.548838Z app=device-simple source=command.go:177 msg="Transform failed for dev: Simple-Device01 cmd: SwitchButton method: GET"
```

The reason is that in the end of GET request when transforming `CommandValue` to `Event`, we only check whether `cv.DeviceResourceName` is in deviceCommand mapping. In this case if we didn't define deviceCommand in DeviceProfile there would be an error.

To resolve this we need to check `cv.DeviceResourceName` is defined in deviceResource mapping if we couldn't find it in deviceCommand mapping. (to fully make sure that `cv.DeviceResourceName` was never defined in DeviceProfile) 
https://github.com/edgexfoundry/device-sdk-go/blob/c317e538ac9d78012123289528b65937d6d981c1/internal/handler/command.go#L146-L150

@cloudxxx8 for awareness

**Comment by hahattan** [comment]
1. 
To resolve this problem we should reconsider the logic of  [CommandExists](https://github.com/edgexfoundry/device-sdk-go/blob/1e86c8aa08f3d791813f32f72efddd3a7e7379cb/internal/cache/profiles.go#L193) function to check whether command exists in either coreCommand or deviceCommand. if not we will assume that the request is trying to access DeviceResource directly ( that's why we called `execRead/WriteDeviceResource` if `!cmdExist`). 

2. 
In the end of GET request when transforming `CommandValue` to `Event`, we should try to find `cv.DeviceResourceName` in either deviceCommand mapping or deviceResource mapping.
https://github.com/edgexfoundry/device-sdk-go/blob/1e86c8aa08f3d791813f32f72efddd3a7e7379cb/internal/handler/command.go#L146-L150

**Comment by cloudxxx8** [comment]
@iain-anderson could you please advise the behavior of C SDK?  Can Device Resource be accessed without DeviceCommand defined in profile?

**Comment by iain-anderson** [comment]
Hi Cloud, yes.
deviceResources may be accessed directly - an Event containing one Reading is generated
a deviceCommand will 'hide' a deviceResource if it has the same name
coreCommands are ignored completely
