### ISSUE TITLE
how to stop a virtual device instance?

### ISSUE THREAD

**Issue by imxuemei** [edgexfoundry/device-sdk-go#430]
I want to start several different virtual devices to simulate a group of devices. I have used the example "Simple-Device" from the device-virtual-go source code to start a virtual device instance in my computer. The code is as follow:
`
sd := yxmtest.SimpleDriver{}
startup.Bootstrap("Simple-Device-03", "1.0.0", &sd)
`
It runs successfully, and it can send data to core service.
Now, i want to stop this virtual device instance, how can i stop it? I have tired to call the sd.Stop(), but it didn't work.

**Comment by cloudxxx8** [comment]
What do you mean Stop here?  Normally we press Ctrl + C to send a OS signal.
If you want to sd.Stop(), you have to implement the Stop() function in your yxmtest.SimpleDriver

**Comment by imxuemei** [comment]
> What do you mean Stop here? Normally we press Ctrl + C to send a OS signal.
> If you want to sd.Stop(), you have to implement the Stop() function in your yxmtest.SimpleDriver
Thanks for your reply.
My whole code is as follows. I use StartSimpledevice() to receive a rest api request and create a thread which is used to start a simple device example.  I use StopSimpledevice() to receive another rest api request to stop the virtual device. 
Is there any method like startup.Stop(serviceName) used to stop the whole driver manager and a driver. If I implement sd.Stop(), how can i do?

`
func StartSimpledevice(w http.ResponseWriter, r *http.Request){
	//create a thread to run the virtual device
	go startSimpleDeviceThread()

	defer r.Body.Close()
	w.Header().Set(common.ContentTypeKey, common.JsonContentType)
	w.Write([]byte("starting"))
}

func StopSimpledevice(w http.ResponseWriter, r *http.Request)  {
	//todo no stop entrance

	defer r.Body.Close()
	w.Header().Set(common.ContentTypeKey, common.JsonContentType)
	w.Write([]byte("stoping"))
}

func startSimpleDeviceThread(){
	sd := yxmtest.SimpleDriver{}
	startup.Bootstrap("Simple-Device-yxm", "1.0.0", &sd)
}
`

**Comment by cloudxxx8** [comment]
No, it's not what Device Service design for.
One service can only start a Device Service thread right now.  If you want to handle multiple Device Service thread in one service, you need to implement the management logic to stop all the thread.

**Comment by imxuemei** [comment]
Ok. Thanks.
