### ISSUE TITLE
Should modify the comment about BinValue in commandvalue.go

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/device-sdk-go#433]
https://github.com/edgexfoundry/device-sdk-go/blob/master/pkg/models/commandvalue.go#L133-L136
`
BinValue is a CBOR encoded binary value with a maximum capacity of 1MB, used to hold binary values returned by a ProtocolDriver instance. Its decoded value is externally accessed using BinaryValue() method`
1. Should remove the parts related to CBOR encoding/decoding here. (Because now we encode/decode the entire event with CBOR encoder/decoder if one of the readings is a binary value.)
2. Refer to https://github.com/edgexfoundry/device-sdk-go/blob/master/pkg/models/commandvalue.go#L71, the maximum capacity of BinValue should be 16MB

@cloudxxx8 for awareness

**Comment by cloudxxx8** [comment]
@FelixTing please just open a PR to modify the comments for this
