### ISSUE TITLE
Implement -n / -name flag

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-go#435]
to set the service name. Each DS implementation will continue to have a hardcoded default name but this flag will override it.
This matches the C device services.

**Comment by iain-anderson** [comment]
Note - the primary utility of being able to do this is to enable multiple instances of a particular device service type to run in a single EdgeX deployment.
An alternative possibility is to use the configuration profile (-p flag) to scope the device service name but I'm not sure what advantages that would bring, and it may confuse the existing use of profiles. @tonyespy can you comment please.

**Comment by hahattan** [comment]
@iain-anderson @tonyespy should we implement this by geneva ?

**Comment by iain-anderson** [comment]
I'd like to have it, but it isn't the end of the world if we don't make it. Other issues have priority.

**Comment by lenny-intel** [comment]
I assume this is an override of the ServiceKey constant, correct?

Should this be in go-mod-bootstrap so it applies to all services and include an environment override, like `EDGEX_SERVICE_NAME`?

**Comment by iain-anderson** [comment]
I've used EDGEX_DSNAME as a device-service-specific override. If we think that changing the service name on any service is useful, happy to change this to EDGEX_SERVICE_NAME

**Comment by lenny-intel** [comment]
@iain-anderson , I don't see this in the CSDK for Geneva?

We found we need to add this same ability to App Functions SDK as the profile approach only goes as far as multiple instances using different profiles, not ones using the same profile. 

Since this is really about the `Service Key` we propose -sk/-serviceKey and EDGEX_SERVICE_KEY. Thoughts? @cloudxxx8 , @hahattan

**Comment by rsdmike** [comment]
if its called service key in consul, I def think we should match it and stay consistent.

**Comment by lenny-intel** [comment]
FYI, add this issue for App Functions SDK
https://github.com/edgexfoundry/app-functions-sdk-go/issues/355
and this PR
https://github.com/edgexfoundry/app-functions-sdk-go/pull/356
will not merge until we have consensuses on the names used.

**Comment by iain-anderson** [comment]
> @iain-anderson , I don't see this in the CSDK for Geneva?

It's in :
https://github.com/edgexfoundry/device-sdk-c/blob/716d0d1fd62b2b124fc0e75af12a8b27a6999d72/src/c/service.c#L178-L207

> 
> We found we need to add this same ability to App Functions SDK as the profile approach only goes as far as multiple instances using different profiles, not ones using the same profile.
> 
> Since this is really about the `Service Key` we propose -sk/-serviceKey and EDGEX_SERVICE_KEY. Thoughts? @cloudxxx8 , @hahattan , @rsdmike

I prefer "name" as that is what is used in our metadata.
