### ISSUE TITLE
Error in installing device-sdk-go via command line

### ISSUE THREAD

**Issue by Nitu-coder** [edgexfoundry/device-sdk-go#445]
go get -v github.com/edgexfoundry/device-sdk-go
github.com/edgexfoundry/go-mod-core-contracts/clients/interfaces
github.com/OneOfOne/xxhash
github.com/google/uuid
github.com/ugorji/go/codec
github.com/go-logfmt/logfmt
github.com/pkg/errors
github.com/go-kit/kit/log
github.com/edgexfoundry/go-mod-registry/pkg/types
github.com/edgexfoundry/go-mod-core-contracts/clients
github.com/hashicorp/consul/api
github.com/pelletier/go-toml
github.com/edgexfoundry/go-mod-core-contracts/clients/general
gopkg.in/yaml.v2
github.com/edgexfoundry/go-mod-registry/internal/pkg/consul
github.com/edgexfoundry/go-mod-registry/registry
github.com/edgexfoundry/device-sdk-go/internal/endpoint
# github.com/edgexfoundry/device-sdk-go/internal/endpoint
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:26:34: undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:42:32: undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:50:35: undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams
github.com/edgexfoundry/go-mod-core-contracts/models
github.com/edgexfoundry/go-mod-core-contracts/clients/logger
github.com/edgexfoundry/go-mod-core-contracts/clients/coredata
github.com/edgexfoundry/go-mod-core-contracts/clients/metadata
github.com/edgexfoundry/device-sdk-go/pkg/models
github.com/edgexfoundry/device-sdk-go/internal/common
# github.com/edgexfoundry/device-sdk-go/internal/common
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:81:53: cannot use event.EncodedEvent (type []byte) as type context.Context in argument to EventClient.AddBytes:
	[]byte does not implement context.Context (missing Deadline method)
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:81:53: cannot use ctx (type context.Context) as type []byte in argument to EventClient.AddBytes
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use event.Event.Device (type string) as type context.Context in argument to DeviceClient.UpdateLastConnectedByName:
	string does not implement context.Context (missing Deadline method)
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use t (type int64) as type string in argument to DeviceClient.UpdateLastConnectedByName
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use ctx (type context.Context) as type int64 in argument to DeviceClient.UpdateLastConnectedByName
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:93:102: cannot use clients.ContentType (type string) as type context.Context in argument to clients.FromContext:
	string does not implement context.Context (missing Deadline method)
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:93:102: cannot use ctx (type context.Context) as type string in argument to clients.FromContext
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:94:108: cannot use clients.ContentType (type string) as type context.Context in argument to clients.FromContext:
	string does not implement context.Context (missing Deadline method)
../../../../../go/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:94:108: cannot use ctx (type context.Context) as type string in argument to clients.FromContext

# 🐞 Bug Report

### Affected Services

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@Nitu-coder please provide your version and recreate steps.  It would be good to follow the issue template.

**Comment by Nitu-coder** [comment]
Hello Cloud Tsai,
I m trying to integrate the device virtual-go example in my home edge code to make my device register to the metadata running at some ip. So this requires importing the 	"github.com/edgexfoundry/device-sdk-go"
so this was not present in my gopath and hence i tried to download it with the following command
"**go get -v github.com/edgexfoundry/device-sdk-go**"

But i get this following error
github.com/edgexfoundry/device-sdk-go/internal/endpoint
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:26:34: undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:42:32: undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:50:35: undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams
# github.com/edgexfoundry/device-sdk-go/internal/common
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:81:53: cannot use event.EncodedEvent (type []byte) as type context.Context in argument to EventClient.AddBytes:
        []byte does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:81:53: cannot use ctx (type context.Context) as type []byte in argument to EventClient.AddBytes
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use event.Event.Device (type string) as type context.Context in argument to DeviceClient.UpdateLastConnectedByName:
        string does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use t (type int64) as type string in argument to DeviceClient.UpdateLastConnectedByName
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use ctx (type context.Context) as type int64 in argument to DeviceClient.UpdateLastConnectedByName
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:93:102: cannot use clients.ContentType (type string) as type context.Context in argument to clients.FromContext:
        string does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:93:102: cannot use ctx (type context.Context) as type string in argument to clients.FromContext
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:94:108: cannot use clients.ContentType (type string) as type context.Context in argument to clients.FromContext:
        string does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:94:108: cannot use ctx (type context.Context) as type string in argument to clients.FromContext


This error I get even when i try to build the integrated code.

Today I have downloaded the sdk code from github and build it. It build fine but again when i try to download it i get the same error.

**Comment by Nitu-coder** [comment]
Is it some version mismatch issue?

**Comment by brandonforster** [comment]
This looks like the version for `go-mod-core-contracts` got bumped when it shouldn't have. #446 will address the contracts changes in this repo. As a fix for this, decrement the version in the `go.mod` for core-contracts.

**Comment by Nitu-coder** [comment]
Issue resolved with chaning the verison of sdk to 1.1.1 and contracts to 33 instead of 31
