### ISSUE TITLE
Integrate go-mod-contracts changes to service clients

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/device-sdk-go#446]
The device SDK needs to be updated to integrate with the latest version of go-mod-core-contracts (0.1.47 as of writing this issue) that contains breaking changes to the signatures of the service client methods.

**Comment by Nitu-coder** [comment]
r u also facing some errors of client/types with device sdk

**Comment by brandonforster** [comment]
> r u also facing some errors of client/types with device sdk??

Please elaborate.

**Comment by Nitu-coder** [comment]
When i build the code i get this error

github.com/edgexfoundry/device-sdk-go/internal/endpoint
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:26:34: **undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams**
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:42:32: **undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams**
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/endpoint/endpoint.go:50:35: **undefined: "github.com/edgexfoundry/go-mod-core-contracts/clients/types".EndpointParams**
 github.com/edgexfoundry/device-sdk-go/internal/common
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:81:53: **cannot use event.EncodedEvent (type []byte) as type context.Context in argument to EventClient.AddBytes:
        []byte does not implement context.Context (missing Deadline method)**
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:81:53: cannot use ctx (type context.Context) as type []byte in argument to EventClient.AddBytes
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use event.Event.Device (type string) as type context.Context in argument to DeviceClient.UpdateLastConnectedByName:
        string does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use t (type int64) as type string in argument to DeviceClient.UpdateLastConnectedByName
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:87:54: cannot use ctx (type context.Context) as type int64 in argument to DeviceClient.UpdateLastConnectedByName
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:93:102: cannot use clients.ContentType (type string) as type context.Context in argument to clients.FromContext:
        string does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:93:102: cannot use ctx (type context.Context) as type string in argument to clients.FromContext
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:94:108: cannot use clients.ContentType (type string) as type context.Context in argument to clients.FromContext:
        string does not implement context.Context (missing Deadline method)
vendor/src/github.com/edgexfoundry/device-sdk-go/internal/common/utils.go:94:108: cannot use ctx (type context.Context) as type string in argument to clients.FromContext

This is the error i m facing and currently have made no changes just calling the driver in my code

**Comment by brandonforster** [comment]
@Nitu-coder `master` should work fine. Use that code.

I am going to work this issue when I am finished with my current task in `edgex-go`. If you need support, try Slack.
