### ISSUE TITLE
Allow Device Service to manage a device's OperatingState

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#454]
This is the counterpart of https://github.com/edgexfoundry/device-sdk-c/issues/215

Device Service should be responsible for updating device's OperatingState

**Comment by iain-anderson** [comment]
Suggest in the first instance we provide a function that takes the Device name and the OperatingState to apply. This can then map directly to a PUT to /v1/device/name/{name} on core-metadata. The resulting device update callback should effect the state change in the device service.
