### ISSUE TITLE
[snap] device services listen on all interfaces (not restricted to localhost)

### ISSUE THREAD

**Issue by GotDisk** [edgexfoundry/device-sdk-go#456]
Installed fuji stable with SNAP on Ubuntu 18.04 and Ubuntu Core 16. The expected behavior would be for services running in the snap (any version) would be configured to listen only on localhost since the snap install has security enabled by default.   When kong is enabled, any requests made to the services from another system should be routed through kong.

**Comment by hahattan** [comment]
@tonyespy @anonymouse64 could you please help take a loot at this issue ? thanks

**Comment by tonyespy** [comment]
@GotDisk thanks for reporting this issue. I've re-titled it, as your original title wasn't quite accurate.

The fuji version of the edgexfoundry snap includes **device-random** and **device-virtual**, and both are disabled by default, so immediately after install, there are no services listening on ports 49000-49999:

```
$ sudo snap install edgexfoundry --channel=fuji/stable
edgexfoundry (fuji/stable) 1.1.0-20200213+5c8c3243 from EdgeX Foundry (edgexfoundry✓) installed

$ snap services edgexfoundry | grep device
edgexfoundry.device-random               disabled  inactive  -
edgexfoundry.device-virtual              disabled  inactive  -

$ sudo lsof -i :49000-49999
(no output)
```
That said, it appears there is an issue with the snap configuration of device services. If I enable **device-virtual**, it appears it is listening on all interfaces, not just localhost:

```
$ sudo snap set edgexfoundry device-virtual=on
$ sudo lsof -i :49000-49999
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
device-vi 19080 root    9u  IPv6 3902066      0t0  TCP *:49990 (LISTEN)



```
Also note that the Geneva version of edgexfoundry now only includes device-virtual, device-random was removed, as it wasn't particularly useful...

**Comment by hareshkainthcanonical** [comment]
Hi, could this be the cause
https://github.com/edgexfoundry/go-mod-bootstrap/commit/38f87ec6a0eaff894d461718761e0a1834e1f8e4 = "fix: Chnaged from using blank hostname to 0.0.0.0"

Wouldnt setting it 0.0.0.0 refer to all interfaces?

**Comment by tonyespy** [comment]
It could be, however all of the core-*, support-*, and security-* services also use this bootstrap code, and none of them exhibit this behavior. I would look to how the device services use the bootstrap module, and in particular how that usage differs from the non-device services.

**Comment by lenny-intel** [comment]
Note that with the above change in bootstrap, all services (core, DS, AS, etc) listen on all interfaces. That was the purpose of the change.

**Comment by tonyespy** [comment]
Then what's the purpose of Kong?

**Comment by lenny-intel** [comment]
> Then what's the purpose of Kong?

In the docker compose environment, the access is limited to localhost via the ports section on each service. 
```
    ports:
      - "127.0.0.1:48080:48080"
      - "127.0.0.1:5563:5563"
```
It was a miss that this change opened it up on snaps w/o an alternative way to restrict it like we do in docker.

The plan is to add a specific setting that allows you to control what interfaces the service listens. It previously used Service.Host which wasn't meant for interfaces.

**Comment by tonyespy** [comment]
Got it, but what's odd is that this is localized to device services, not the core-*, support-*, or security-* services, so we have some more investigation needed...

**Comment by lenny-intel** [comment]
> When kong is enabled, any requests made to the services from another system should be routed through kong.

Requests to services have to be made via Kong, i.e. https://<ip>:8443/coredata/api/v1/... 
They are not automatically "routed" through Kong using that service port.
Also, Device Services endpoints are not setup to be hit via Kong.

**Comment by hareshkainthcanonical** [comment]
The solution would be to create a patch in the snap file that reverts the change back in the bootstrap mod.

**Comment by lenny-intel** [comment]
For device services and app service the plan is to do another feature release and do a snap patch of edgex-go that uses the earlier version of go-mod-bootstrap.

**Comment by iain-anderson** [comment]
Is this issue now resolved @hareshkainthcanonical ?

**Comment by hareshkainthcanonical** [comment]
@iain-anderson The issue was resolved.
