### ISSUE TITLE
Remove Data Type Enumerations

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/device-sdk-go#468]
This issue is dependent on the completion of https://github.com/edgexfoundry/go-mod-core-contracts/issues/225

As we move forward with implementing the [Array Data Types ADR](https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0002-Array-Datatypes.md), we want to move the data type enumerations from this module to `mod-core-contracts`. Once the migration is complete we need to remove the references here, since they will be a duplicate.

The enumerations we are looking to remove are:
https://github.com/edgexfoundry/device-sdk-go/blob/9e6d46c2b077c5ce04ff29192bd4c5718c8c2e91/pkg/models/commandvalue.go#L26-L66

Please refer to the meeting notes and recording from the [March 26 Core Working Group Meeting](https://wiki.edgexfoundry.org/display/FA/Core+Working+Group) for more details

**Comment by cloudxxx8** [comment]
It would break the backward compatibility because those constants are in the public API.  All the Device Service implementations might use those constants.  We can't remove it until v2.0

**Comment by hahattan** [comment]
This is implemented in v2 core-contract and device service will adopt it when we finish #528
