### ISSUE TITLE
Don't log CBOR event/reading.

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#469]
Currently the SDK simply logs the new event/reading as a DEBUG message. This can cause a lot of data when it is CBOR and doesn't provide any useful information. The new device-virtual is creating CBOR via auto events, so the log is not pretty when set to DEBUG.

Suggest logging a message like `CBOR event/reading was pushed`

**Comment by hahattan** [comment]
Besides autoevent, there's another place that'll log the whole reading in the commandhandler:
https://github.com/edgexfoundry/device-sdk-go/blob/79a40a317d1b6800d1816ffd538dea299a9d4c8b/internal/handler/command.go#L172

Do we also need to avoid log the reading if it has binary value ?

**Comment by cloudxxx8** [comment]
Yes, please modify all of the repository to avoid this situation.  thanks.
