### ISSUE TITLE
run my device-simple fail

### ISSUE THREAD

**Issue by xuexiqiangzhe** [edgexfoundry/device-sdk-go#470]
hello,I follow the doc on edgexfoundry<Writing a Device Service in Go>
https://fuji-docs.edgexfoundry.org/Ch-GettingStartedSDK-Go.html

in the last step,I have Created Device Profile and configuration.toml according to the EdgeX doc.
and make build.
the log is following

~/go/src/github.com/edgexfoundry/device-simple/cmd/device-simple$ ./device-simple 
Init: useRegistry:  profile:  confDir: 
Loading configuration from: /home/yuanxiaohang/go/src/github.com/edgexfoundry/device-simple/cmd/device-simple/res/configuration.toml

Load configuration from local file and bypassing registration in Registry...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f1eed]

goroutine 1 [running]:
github.com/edgexfoundry/device-sdk-go.NewService(0xb90c45, 0xd, 0xb994de, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/yuanxiaohang/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.1.2/service.go:287 +0x22d
github.com/edgexfoundry/device-sdk-go/pkg/startup.startService(0xb90c45, 0xd, 0xb994de, 0x1a, 0xcb95c0, 0xc0001827b0, 0x0, 0x40e508)
	/home/yuanxiaohang/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.1.2/pkg/startup/bootstrap.go:46 +0xd4
github.com/edgexfoundry/device-sdk-go/pkg/startup.Bootstrap(0xb90c45, 0xd, 0xb994de, 0x1a, 0xcb95c0, 0xc0001827b0)
	/home/yuanxiaohang/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.1.2/pkg/startup/bootstrap.go:39 +0x10a
main.main()
	/home/yuanxiaohang/go/src/github.com/edgexfoundry/device-simple/cmd/device-simple/main.go:23 +0x74

**Comment by cloudxxx8** [comment]
@xuexiqiangzhe could you please try the same behavior in fuji branch or v1.1.2 tag?  they should be more stable.

**Comment by hahattan** [comment]
@xuexiqiangzhe try use the latest SDK release, modify `go.mod`:
```
module github.com/edgexfoundry/device-simple

go 1.13

require (
	github.com/edgexfoundry/device-sdk-go v1.2.0-dev.20
	github.com/edgexfoundry/go-mod-core-contracts v0.1.57
)
```
and use the updated `configuration.toml`:
```
[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = '192.168.0.4'
Port = 49990
Protocol = 'http'
StartUpMsg = 'device tutorial started'
Timeout = 5000
ConnectRetries = 3
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consu'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

[Logging]
EnableRemote = false
File = './device-simple.log'

# Pre-define Devices
[[DeviceList]]
  Name = 'RandNum-Device01'
  Profile = 'RandNum-Device'
  Description = 'Random Number Generator Device'
  Labels = [ 'random', 'test' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = 'random'
      Port = '300'
  [[DeviceList.AutoEvents]]
    Resource = 'Random'
    OnChange = false
    Frequency = '10s'
```
I've tested it and it worked well

**Comment by xuexiqiangzhe** [comment]
> @xuexiqiangzhe could you please try the same behavior in fuji branch or v1.1.2 tag? they should be more stable.

I have tried.It‘s still the same

**Comment by xuexiqiangzhe** [comment]
> module github.com/edgexfoundry/device-simple
> 
> go 1.13
> 
> require (
> 	github.com/edgexfoundry/device-sdk-go v1.2.0-dev.20
> 	github.com/edgexfoundry/go-mod-core-contracts v0.1.57
> )

I have modified go.mod and configuration.toml.
but there are problems of "make build failed"
````
CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/device-simple.Version=0.0.0" -o cmd/device-simple/device-simple ./cmd/device-simple
# github.com/fxamacker/cbor/v2
../../../../pkg/mod/github.com/fxamacker/cbor/v2@v2.2.0/encode.go:832:11: v.MapRange undefined (type reflect.Value has no field or method MapRange)
../../../../pkg/mod/github.com/fxamacker/cbor/v2@v2.2.0/encode.go:913:11: v.MapRange undefined (type reflect.Value has no field or method MapRange)
note: module requires Go 1.12Makefile:18: recipe for target 'cmd/device-simple/device-simple' failed
make: *** [cmd/device-simple/device-simple] Error 2
```

the sdk I cloned is the branch of master.

The content of the go.mod in the sdk:
```
module` github.com/edgexfoundry/device-sdk-go

require (
	github.com/OneOfOne/xxhash v1.2.6
	github.com/edgexfoundry/go-mod-bootstrap v0.0.26
	github.com/edgexfoundry/go-mod-core-contracts v0.1.54
	github.com/edgexfoundry/go-mod-registry v0.1.17
	github.com/fxamacker/cbor/v2 v2.2.0
	github.com/google/uuid v1.1.0
	github.com/gorilla/mux v1.7.1
	github.com/pkg/errors v0.8.1
	github.com/stretchr/testify v1.5.1
	gopkg.in/yaml.v2 v2.2.8
)

go 1.13
```

according to this line of the go.mod in sdk,maybe I should modify go.mod in device-simple to the same version?
github.com/edgexfoundry/go-mod-core-contracts v0.1.54

**Comment by hahattan** [comment]
what's your go version ? the log said `note: module requires Go 1.12`

**Comment by xuexiqiangzhe** [comment]
> what's your go version ? the log said `note: module requires Go 1.12`

$ go version
go version go1.11.5 linux/amd64

**Comment by hahattan** [comment]
> > what's your go version ? the log said `note: module requires Go 1.12`
> 
> $ go version
> go version go1.11.5 linux/amd64

can you try upgrade to 1.13 and build again ?

**Comment by xuexiqiangzhe** [comment]
> > > what's your go version ? the log said `note: module requires Go 1.12`
> > 
> > 
> > $ go version
> > go version go1.11.5 linux/amd64
> 
> can you try upgrade to 1.13 and build again ?

It works.
Build successfully,run and I can see the device service and device in the edgex-ui.

But,I send the command,the ReadValue is failed

**Comment by hahattan** [comment]
I don't think there's problem in configuration and device profile (at least it worked quite well to me).
> and add the random under the xRotation of driver.go.it returns the random value. 

If that's the case you should modify the device profile as well because the deviceResource defined in device profile is `randomnumber` not `xRotation`.
you can instead add `randomnumber` logic right after what is provided in driver.go:
![example](https://imgur.com/rhOShLm.jpg)

you can also verify it via autoevent which will send `randomnumber` to coredata every 30 seconds and it'll log something like `msg="SendEvent: Pushed event to core data"`

**Comment by xuexiqiangzhe** [comment]
I can't open the picture you send.
I show you my configuration.toml,random-generator-device.yaml and driver.go
configuration.toml:
like yours

random-generator-device.yaml:
```
name: "RandNum-Device"
manufacturer: "Dell Technologies"
model: "1"
labels:
 - "random"
 - "test"
description: "random number generator to simulate a device"

deviceResources:
    -   
        name: "randomnumber"
        description: "generated random number"
        attributes:
            { type: "random" }
        properties:
            value:
                { type: "INT32", readWrite: "R", defaultValue: "0.00", minimum: "0.00", maximum: "100.00"  }
            units:
                { type: "String", readWrite: "R", defaultValue: "" }

deviceCommands:
    -
        name: "Random"
        get:
            -
                { operation: "get", object: "randomnumber", property: "value", parameter: "Random" }

coreCommands:
  -
    name: "Random"
    get:
        path: "/api/v1/device/{deviceId}/Random"
        responses:
          -
            code: "200"
            description: ""
            expectedValues: ["Random"]
          -
            code: "503"
            description: "service unavailable"
            expectedValues: []

```
HandleReadCommands of driver.go:
```
func (s *SimpleDriver) HandleReadCommands(deviceName string, protocols map[string]contract.ProtocolProperties, reqs []dsModels.CommandRequest) (res []*dsModels.CommandValue, err error) {
	s.lc.Debug(fmt.Sprintf("SimpleDriver.HandleReadCommands: protocols: %v resource: %v attributes: %v", protocols, reqs[0].DeviceResourceName, reqs[0].Attributes))

	if len(reqs) == 1 {
		res = make([]*dsModels.CommandValue, 1)
		now := time.Now().UnixNano()
		if reqs[0].DeviceResourceName == "randomnumber" {
                        cv, _ := dsModels.NewInt32Value(reqs[0].DeviceResourceName, now,  int32(rand.Intn(100)) )
			res[0] = cv
		} else if reqs[0].DeviceResourceName == "Xrotation" {
			cv, _ := dsModels.NewInt32Value(reqs[0].DeviceResourceName, now, s.xRotation)
			res[0] = cv
		} else if reqs[0].DeviceResourceName == "Yrotation" {
			cv, _ := dsModels.NewInt32Value(reqs[0].DeviceResourceName, now, s.yRotation)
			res[0] = cv
		} else if reqs[0].DeviceResourceName == "Zrotation" {
			cv, _ := dsModels.NewInt32Value(reqs[0].DeviceResourceName, now, s.zRotation)
			res[0] = cv
		} else if reqs[0].DeviceResourceName == "Image" {
			// Show a binary/image representation of the switch's on/off value
			buf := new(bytes.Buffer)
			if s.switchButton == true {
				err = getImageBytes("./res/on.png", buf)
			} else {
				err = getImageBytes("./res/off.jpg", buf)
			}
			cvb, _ := dsModels.NewBinaryValue(reqs[0].DeviceResourceName, now, buf.Bytes())
			res[0] = cvb
		}
	} else if len(reqs) == 3 {
		res = make([]*dsModels.CommandValue, 3)
		for i, r := range reqs {
			var cv *dsModels.CommandValue
			now := time.Now().UnixNano()
			switch r.DeviceResourceName {
			case "Xrotation":
				cv, _ = dsModels.NewInt32Value(r.DeviceResourceName, now, s.xRotation)
			case "Yrotation":
				cv, _ = dsModels.NewInt32Value(r.DeviceResourceName, now, s.yRotation)
			case "Zrotation":
				cv, _ = dsModels.NewInt32Value(r.DeviceResourceName, now, s.zRotation)
			}
			res[i] = cv
		}
	}

	return
}
```
Maybe there is some problem in my logic of these three files.

**Comment by hahattan** [comment]
It actually looks good, can you provide some error log from device service to narrow down the problem?  
Also try modify the `Host` under Service config to your IP instead of localhost so that other edgex service can connect to device-simple:
```
[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = '<IP_ADDR>'
Port = 49990
Protocol = 'http'
StartUpMsg = 'device tutorial started'
Timeout = 5000
ConnectRetries = 3
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16
```

**Comment by xuexiqiangzhe** [comment]
> It actually looks good, can you provide some error log from device service to narrow down the problem?
> Also try modify the `Host` under Service config to your IP instead of localhost so that other edgex service can connect to device-simple:
> 
> ```
> [Service]
> BootTimeout = 30000
> CheckInterval = '10s'
> ClientMonitor = 15000
> Host = '<IP_ADDR>'
> Port = 49990
> Protocol = 'http'
> StartUpMsg = 'device tutorial started'
> Timeout = 5000
> ConnectRetries = 3
> Labels = []
> EnableAsyncReadings = true
> AsyncBufferSize = 16
> ```

I have modified to my IP address
no error log?
In terminal,I only got an empty return
```
 $ curl http://192.168.1.107:48080/api/v1/event/device/RandNum-Device-01/100
[]
```
on the edgex-ui-logging:
```
INFO   2020-04-12 14:47:57   Event Published on message queue. Topic: events, Correlation-id: 4a460a3b-f6a5-43d5-b025-b00772a7ee91

INFO   2020-04-12 14:47:57   Event Published on message queue. Topic: events, Correlation-id: 845eff7d-f612-4ad1-bc49-090b82e3034c

INFO   2020-04-12 14:47:57   Putting event on message queue

INFO   2020-04-12 14:47:57   Event Published on message queue. Topic: events, Correlation-id: 845eff7d-f612-4ad1-bc49-090b82e3034c

INFO   2020-04-12 14:48:01   Event Published on message queue. Topic: events, Correlation-id: ea898643-cb18-464d-83bc-45840505683d

INFO   2020-04-12 14:48:01   Putting event on message queue

INFO   2020-04-12 14:48:01   Putting event on message queue

INFO   2020-04-12 14:48:01   Event Published on message queue. Topic: events, Correlation-id: 253a9074-c31d-4df7-959a-f8309540c784

INFO   2020-04-12 14:48:01   Putting event on message queue
```

**Comment by hahattan** [comment]
there's typo in your device name, should be:
`curl http://192.168.1.107:48080/api/v1/event/device/RandNum-Device01/100`

**Comment by xuexiqiangzhe** [comment]
> there's typo in your device name, should be:
> `curl http://192.168.1.107:48080/api/v1/event/device/RandNum-Device01/100`
It works! It's very kind of you to help me.thanks a lot！
```
$ curl http://192.168.1.107:48080/api/v1/event/device/RandNum-Device01/100
[{"id":"b2e67ab6-e89c-4da5-864c-27d11d7b0074","device":"RandNum-Device01","created":1586670638986,"modified":1586670638986,"origin":1586670638984552671,"readings":[{"id":"fe715a19-21da-4c8b-89cd-44dfd28f5c11","created":1586670638985,"origin":1586670638984538224,"modified":1586670638985,"device":"RandNum-Device01","name":"randomnumber","value":"59"}]},{"id":"c94f249b-03ec-4bd1-9a9c-ec49800ba760","device":"RandNum-Device01","created":1586670628986,"modified":1586670628986,"origin":1586670628984102555,"readings":[{"id":"546bbed8-44cd-4c25-9e83-3ba9ca780306","created":1586670628985,"origin":1586670628984087842,"modified":1586670628985,"device":"RandNum-Device01","name":"randomnumber","value":"47"}]},{"id":"15d79a85-7039-4e49-8a23-6c46e70e11bc","device":"RandNum-Device01","created":1586670618984,"modified":1586670618984,"origin":1586670618983184072,"readings":[{"id":"6f074abd-1ffb-46fd-8a8c-4dea49083ef3","created":1586670618983,"origin":1586670618983157668,"modified":1586670618983,"device":"RandNum-Device01","name":"randomnumber","value":"87"}]},{"id":"179d1076-73fe-477b-998e-b47911ae4a20","device":"RandNum-Device01","created":1586670608984,"modified":1586670608984,"origin":1586670608982449729,"readings":[{"id":"a86a8de7-b724-402d-9634-e60052a060f0","created":1586670608983,"origin":1586670608982413572,"modified":1586670608983,"device":"RandNum-Device01","name":"randomnumber","value":"81"}]}]

```
