### ISSUE TITLE
Run Data Race Detector in makefile for unit test

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#472]
According to the recent WG meeting, we should verify the service with Data Race Detector
Refer to: 
https://github.com/edgexfoundry/edgex-go/blob/28c25972b4512281f3666373bb21b36fa0252d7e/Makefile#L71
https://golang.org/doc/articles/race_detector.html

**Comment by hahattan** [comment]
we'll manually run race detector by geneva
