### ISSUE TITLE
Support array data type in device sdk

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#476]
To implement Array Datatypes Design
https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0002-Array-Datatypes.md

**Comment by novuscy** [comment]
The scaling transformation and FloatEncoding seem NOT working when use float array data types.

**Comment by hahattan** [comment]
https://github.com/edgexfoundry/edgex-docs/pull/122
The ADR (which is still under review though) suggests that scaling transformation will not be applied to the values in an array.

@cloudxxx8 should we add FloatEncoding to the value of float array type ?

**Comment by novuscy** [comment]
> [edgexfoundry/edgex-docs#122](https://github.com/edgexfoundry/edgex-docs/pull/122)
> The ADR (which is still under review though) suggests that scaling transformation will not be applied to the values in an array.
> 
> @cloudxxx8 should we add FloatEncoding to the value of float array type ?

if I have to do the scaling manually in the device service, how can I get the scale value defined in the profile? The CommandValue only has Attribute field but no properties.

**Comment by cloudxxx8** [comment]
@novuscy there is a workaround.  you can call GetDeviceByName(name string) public API from service package in SDK, and you retrieve all the profile content.
