### ISSUE TITLE
Add Support for handling CBOR content for commands

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/device-sdk-go#479]
This is dependent on https://github.com/edgexfoundry/edgex-go/issues/2272 so the `Content-type` header is present so we can determine the content type rather than assuming JSON. I think we should  default to JSON so that we are still backwards compatible for situations where that header is not present.

**Comment by akramtexas** [comment]
- This issue can be closed in favor of the newly-created issue: https://github.com/edgexfoundry/device-sdk-go/issues/488
