### ISSUE TITLE
SDK can't retrieve the configuration from Core Metadata correctly

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#494]
When the device service starts up, the following error always shows:
level=ERROR ts=2020-04-20T10:21:33.6402923Z app=device-simple source=profiles.go:162 msg="Error when getting configuration from Core Metadata: 404 - 404 page not found\n "

**Comment by hahattan** [comment]
https://github.com/edgexfoundry/device-sdk-go/blob/dfaaf3db4a48c41e92535fbbc26dffa7770b5bf3/internal/provision/profiles.go#L160-L164

https://github.com/edgexfoundry/go-mod-core-contracts/blob/38d0cc147a837ce191fd6fcb9b0683ab407438b4/clients/general/client.go#L45

not sure the issue belongs to SDK or core-contract..., but eventually the request will be sent to `http://<host>:48081/api/v1/config/api/v1/config
