### ISSUE TITLE
Device Service can't be terminated if the dependency services doesn't start up

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#495]
If the user starts device-simple without starting core-metadata or core-data, it will keep re-trying.
Users should be able to press Ctrl-C to terminate the service instead of waiting util time out.

**Comment by hahattan** [comment]
Currently you can press Ctrl-C twice and the device service should be shut down gracefully.  
@lenny-intel do you have any comment on this behavior? I think the first Ctrl-C is redirected to the bootstrap package to stop long running goroutines and the second Ctrl-C would actually stop the device service main thread.

**Comment by lenny-intel** [comment]
Should only require a single Ctrl-C. Beyond that I don't have any comment. Seems more like a low priority issue.
