### ISSUE TITLE
Add Attribution.txt and LICENSE to all service artifacts

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-sdk-go#497]
### Affected Services
All device services 

### Description
Per architect's meeting of 4/20/20, all artifacts (snaps, docker images, etc.) should include the LICENSE and Attribution.txt at the root directory of the image (same place that the binary is placed).

**Comment by cloudxxx8** [comment]
@hahattan I remember you have done this request.  Please help check in each Go Device Services.

**Comment by hahattan** [comment]
I've went thought all device services  and for the docker image they have `Attribution.txt` and `LICENSE` under root directory(`/`). For some services that have snap support, they also have these 2 files installed under `/usr/share/doc/device-xxx-go/`
