### ISSUE TITLE
Unable to remove AutoEvents using API

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/device-sdk-go#508]
AutoEvents can not be removed since added, sending device payload with 
```
{
...
"autoEvents":[]
}
```
or
```
{
...
"autoEvents":null
}
```
to /v1/device endpoint using PUT method is not working, perhaps the autoEvents payload is omitted by the  `omitempty` tag?

the only way I found working is to send 
```
{
...
"autoEvents":[{}]
}
```
to stop the auto events, is this the correct way to achieve that?

**Comment by hahattan** [comment]
I've tried check the updated device in device update callbackHandler and the autoevents is still not updated in your first 2 method.  So I think this is an edgex-go issue which device isn't updated correctly and currently we're unable to fix this from SDK.

**Comment by cloudxxx8** [comment]
@novuscy it is the bug in core metadata, so please move this issue to edgex-go repository.  you are right.  it should be removed by 
```
{
...
"autoEvents":[]
}
```

**Comment by cloudxxx8** [comment]
fixed in edgex-go

**Comment by novuscy** [comment]
In the recent V2 release, by sending 
```
{
...
"autoEvents":[]
}
```

to core-metadata can delete autoEvents in device, but autoEvents won't stop until I restart the device service, any thing changed in the V2 implementation?
