### ISSUE TITLE
[HOME-EDGE -EDGEX Integration]Getting the device id for the new device added in metadata

### ISSUE THREAD

**Issue by Nitu-coder** [edgexfoundry/device-sdk-go#512]
Hello,
I m working on integrating edgex with home edge for data storage module as already discussed in the open source calls of LF-Edge. For the same integration i need the device id that is generated when a device is added to metadata. But the interface that is made available for the developers for device service does not make this available. But when i checked the device sdk code i could see that id is obtained in handledevice function in device.go file. 
@jpwhitemn   can you please help me with this issue as it is kind of blocker for us in the integration and development part

**Comment by cloudxxx8** [comment]
@Nitu-coder are you developing a new device service?  when you create a new device, the protocol driver you implemented will get an `AddDevice` call back with device name.   Then, you could call the public API `GetDeviceByName` to retrieve the device with id.
https://github.com/edgexfoundry/device-sdk-go/blob/59d7bbd65c65af3ab25ed9f69c8c28db04e20564/pkg/service/manageddevices.go#L66

**Comment by Nitu-coder** [comment]
Hello @cloudxxx8 
Thanks for such quick reply,I checked the code but if there are multiple devices with same name then how will that situation be handled as for home environment there can be multiple devices with same name.
Can you please help with this issue.

**Comment by cloudxxx8** [comment]
@Nitu-coder in EdgeX environment, name is always an unique value in core-metadata.  That's a kind of architectural decision.

**Comment by Nitu-coder** [comment]
@cloudxxx8  Thanks alot for this information. I will take this point into consideration while desiginign for Home Edge module. 
Also one more query ,
In Home edge we  also generated uuid and there is one one uuid for device added to metadata
So i need to update that uuid with our uuid . From sdk i checked the following function
**(s *Service) UpdateDevice(device contract.Device) error**
in this function how can i pass the value that needs to be updated and its updated value

Or the UUid cannot be changed? Can you please clarify this doubt also

**Comment by cloudxxx8** [comment]
@Nitu-coder  id is the filed cannot be updated.  could you please try to assign your uuid into the "id" field when you create the device?  it works in the older version.

**Comment by Nitu-coder** [comment]
@cloudxxx8, by the above comment did u mean to put in the yaml file itself before my device creation?

yeah i tried to update the name also but i m getting 409 error of duplicate name. none of the fields in this version canbe updated it seems. So what is the updateDevice used for ??
my sdk version 1.1.2

**Comment by cloudxxx8** [comment]
no, YAML file is for profile, not device.  how do you normally create a device?

Did you try to update device from core-metadata directly?  What is the data you are updating?  You need to provide to full information and recreate steps for the trouble shooting.
UpdateDevice just forward the request to core-metadata.

**Comment by Nitu-coder** [comment]
@cloudxxx8  i using the device service sample for rest devices and it automatically adds the device using the yaml. I m just getting the call back in add device function of rest driver. and then using it to code it. How do i create the device ?
For update of device 
device, err := service.GetDeviceByName(deviceName)
	if err != nil {
		log.Println("Error is not nill", err)
		return err
	}
	log.Println("The device id obtained is ", device.Id)
	device.Name = "Changing the name"

	err = service.UpdateDevice(device)
this is the code i have added in the same callback function of rest driver file. Earlier the name was "sample-json"

**Comment by Nitu-coder** [comment]
@cloudxxx8 , if you could give your suggestion in the above issue, as this feature will also play a important role in deciding the design of the data storage module using the edgex foundry in home edge.
Its a kind of blocker, because if we could not update the value then we will have a discussion and accordingly make changes in the design document.

Thanks alot for your help till now, your response would be appreciated.

**Comment by cloudxxx8** [comment]
I still don't understand how you create the device and what kinds of error you got.
Please provide all the information to identify the issue, including your YAML (it supposes for profile, not device), configuration, and the error log from the device service and core-metadata.

Have you tried to create or update Device by the API of core-metadata directly?

**Comment by Nitu-coder** [comment]
@cloudxxx8 
I have dowbloaded the device service rest-go code, https://github.com/edgexfoundry/device-rest-go
link.
I m not doing anything to create a device. I have just build this code and running it. yaml file and confuguration file of above device service i have attached. I have also attached the configuration of metadata. Since it doesnot support the other versions i have copy pates those files in simple txt files.
[json-device-yaml.txt](https://github.com/edgexfoundry/device-sdk-go/files/4549922/json-device-yaml.txt)
[configuration-deviceservice.txt](https://github.com/edgexfoundry/device-sdk-go/files/4549923/configuration-deviceservice.txt)
[_metatdata_config.txt](https://github.com/edgexfoundry/device-sdk-go/files/4549928/_metatdata_config.txt)
![error](https://user-images.githubusercontent.com/43419655/80564052-6494c980-8a0a-11ea-979b-d075a7ab7008.png)

AAnd the code changes that i have made in file resthandler.go file of device service that i had downloaded 
func (driver *RestDriver) AddDevice(deviceName string, protocols map[string]contract.ProtocolProperties, adminState contract.AdminState) error {
	// Nothing required to do for AddDevice since new devices will be available
	// when data is posted to REST endpoint
	log.Println("This function is called after the device is added")
	log.Println("protcols", protocols)
	log.Println("deviceName", deviceName)
	device, err := service.GetDeviceByName(deviceName)
	if err != nil {
		log.Println("Error is not nill", err)
		return err
	}
	log.Println("The device id obtained is ", device.Id)
	device.Name = "2601qwer-tya4-46f8-a39b-41ae12ed282"

	err = service.UpdateDevice(device)

	if err != nil {
		log.Println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Error is not nill", err)
		return err
	}

	return nil
}

Attcahed the error logs. also. I m not able to undestand your question "Have you tried to create or update Device by the API of core-metadata directly?" since our prjct requirement is to update using device service only. since metadata will be running in only one master device and device service service in all other client. Our architecture design is centralized storage so metadataand coredata will be running in only one machine.

**Comment by cloudxxx8** [comment]
@Nitu-coder please check the log in core-metadata.  Please help confirm the name you are updating doesn't exist in core-metadata.  You could list all the Device via the Get API.
By the way, the YAML you provided is the Device Profile, not Device.  The Device is defined in the configuration.toml.  Also, the pre-defined devices in configuration.toml is for developoment purpose.  It's not recommended for production.  You should create the Devices and Profiles via core-metadata APIs.
"Have you tried to create or update Device by the API of core-metadata directly?" means you should create or update Device via core-metadata.  It won't be impacted by your centralized architecture.

**Comment by Nitu-coder** [comment]
@cloudxxx8 metadata apis i checked in the raml file but for device creation i didnt find any . Yes the name i directly  updated is not present in core metadata but then for update generally we provide which column to update and the updated value. but in the api exposed by device service i didnt find that and so got confused. 

Regarding updating using coremetadata api, that i wll try an dping you back in case of error.

Also one more thing if i create the device by calling core metadata api then that info will be automatically recorded int he configration toml.? Any documentation links that i can use for the same query that i hjave asked would be more helpful.

**Comment by cloudxxx8** [comment]
no, the configuration.toml won't be changed at runtime.

**Comment by cloudxxx8** [comment]
the device creation API is 
POST ​/v1​/device

**Comment by Nitu-coder** [comment]
@cloudxxx8 as per our conversation i understand i should be first creating a device using the api u mentioned in the initialize funciton of device service and then start posting the evnts. and updating can be done directly using the coremetadata api. please correct me if i m wrong anywhere.
SO i can remove the predefined devices from the configuration file since i will be creating one using POST api and yaml file will be as it is since it defines the device profile.

**Comment by Nitu-coder** [comment]
@cloudxxx8 any sample code i can get that creates a device and also sends the reading? all the pther have sample devices predefined

**Comment by cloudxxx8** [comment]
@hahattan please help identify whether this is a real issue we need to fix in Geneva

**Comment by cloudxxx8** [comment]
@Nitu-coder After some investigation, it works as the design of core-metadata.
Currently, it doesn't allow users to assign the id, and the name cannot be updated after a device created.
The real issue here is that the returned error you saw is incorrect.  `409 error of duplicate name` is not correct error message and easy to get people confused.

To create a device, you can just use the client in go-mod-core-contracts to call the REST API
https://github.com/edgexfoundry/go-mod-core-contracts
https://docs.edgexfoundry.org/1.2/api/core/Ch-APICoreMetadata/

**Comment by cloudxxx8** [comment]
@Nitu-coder To fulfill your requirement, we need to open an issue in edgex-go repository about allowing the customized id, and discuss the solution in EdgeX meeting.
The workaround is to use `Label` to store your id for now.

**Comment by Nitu-coder** [comment]
@cloudxxx8 i have updated the yaml file first the name value as the uuid i wanst to update and then registered the device using the sample device-rest-go available on github. Its working fine. But i want to try using the apis to upload the profile and provision the device after adding it. Just one last query is the yaml file necessary, i mean the yaml file should be predefined  to get registered?

**Comment by cloudxxx8** [comment]
Device Profile is necessary, but it can be add in YAML format or JSON format.  The API is just different.  You don't have to pre-defined in Device Service, but you have to add into Core Metadata in some way.

**Comment by cloudxxx8** [comment]
You can read the new document about Profile in this PR to get more understanding about Device Profile
https://github.com/edgexfoundry/edgex-docs/pull/139

**Comment by Nitu-coder** [comment]
@cloudxxx8 Thanks for the info. i tried to register the device following this link and calling the apis mentioned with the same json data  using postman. I got all the apis succeded but when i try to add the device i get no protocol specified error. Can you help me with this?
The link is 
Also one more request since comments here are increasing can we have some other mode of communication so that i can close the issue here. Any suitable mode that is convenient to you also.

**Comment by cloudxxx8** [comment]
@Nitu-coder that article is for the older version of EdgeX.  We made some changes before releasing Edinburgh (v1.0).  There is no addressable in the Device, and we use protocol property instead.
Please see https://github.com/edgexfoundry/edgex-go/pull/2533/files

You can always join the Device Service WG meeting to highlight your issues, or please contact me via mail or slack to schedule an online meeting.

**Comment by cloudxxx8** [comment]
close this issue due to no new activity
