### ISSUE TITLE
Add labels to ValueDescriptor when adding new Profile

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/device-sdk-go#516]
It would be very convenient when adding a new Profile, the Tag field of the DeviceResource automatically being added to the Labels field of the ValueDescriptor, which let the tag serve its purpose of labeling some information.

**Comment by cloudxxx8** [comment]
We are going to remove ValueDescriptor in V2, and all the information will be in Reading
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x
