### ISSUE TITLE
Replace --serviceName with --instance

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#526]
PR [253](https://github.com/edgexfoundry/device-sdk-go/pull/523) landed support for a new device service command-line option `--serviceName `which allows someone at runtime to change the name of the service name used when creating it's metadata DeviceService instance and when registering to the registry.

This change means it's possible once again for someone to run the device-service, populating objects in Core Metadata, and then re-run the same service with a different name, which can lead to undefined behavior, which is why service name wasn't included as a configuration value when device-sdk-go was first created.

Also as the service name defined in the code essentially identifies which device service is running, allowing it to be changed to an arbitrary value doesn't seem correct either.

We discussed this during today's device service WG meeting, and the consensus is that we should update this command-line option to instead provide a service name suffix which allows unique instance names to be created, but still allows for identification of the service (i.e. if you ran multiple instances of device-ble, you'd still know that they're all instances of device-ble).

I would suggest the option be called --instanceName (or just --instance) with -i as the short option. This name would be then just appended with a "_" separator (as opposed to ";") to the pre-defined service name. Ex.

```
service name = device-ble

-i beacon-reader
```

resulting service name would be `device-ble_beacon-reader`

Also the current option help description is:

> -n, --serviceName Overrides the service name to be stored in metadata, used with
> Registry and/or Configuration Providers. If the profile is also provided, name will be
> replaced with "<name>;<profile>"

I don't see an added benefit to automatically appending profile when we have `--instanceName`? This is similar to my original proposal for running multiple instances of a device service (based on app-service-configurable's approach), but the issue with that approach as @lenny-intel described this morning, is you could still only run one instance of a specific profile. So I think we should just drop this behavior.

**Note** - when I tested the feature earlier today, I also noticed that specifying a serviceName w/out specifying a profile resulted a "**;res**" being appended to the service name.

**Comment by iain-anderson** [comment]
re: profile, this should still be useful for selecting alternative configurations for the same service instance? So when the service is registering in core-metadata and in consul, the profile is not used, but when it is loading configuration, the profile is used.
I don't think detailing how that works in the help text for --instance clarifies anything though.

**Comment by iain-anderson** [comment]
Also should use EDGEX_INSTANCE_NAME rather than EDGEX_SERVICE_NAME for the environment override.
