### ISSUE TITLE
Implement V2 Device Service REST API

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-go#529]
Specification is at https://github.com/edgexfoundry/device-sdk-go/tree/master/api/oas3.0/v2

Until the v2.0 release, both v1 and v2 endpoints need to be available

**Comment by hahattan** [comment]
According to [v2api](https://github.com/edgexfoundry/device-sdk-go/blob/master/openapi/v2/device-sdk.yaml), the `/ping`, `/config`, `/metrics`, `/version` all require POST method instead of GET, is it correct ?

**Comment by cloudxxx8** [comment]
that's incorrect, so we have https://github.com/edgexfoundry/device-sdk-go/issues/555

**Comment by cloudxxx8** [comment]
We have ADR here
https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md

**Comment by lenny-intel** [comment]
@hahattan , for consistency across the services, please look at App Services V2 implementations of the common APIs here:
https://github.com/edgexfoundry/app-functions-sdk-go/tree/master/internal/v2

**Comment by hahattan** [comment]
The v2 API are addressed separately in #602, #603, #605, and #619, there's still some unfinished part which depends on core-services v2 API and I'll create new issue to track them . (e.g. #629 )
