### ISSUE TITLE
Use message bus to send events to App services (and potentially core-data / support-data)

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-go#530]
Via go-mod-messaging module

**Comment by lenny-intel** [comment]
FYI, that this feature must use a message bus that allows multiple publishers for the same topic since we'll have multiple device services publishing to the message bug. ZMQ will not work for this.

**Comment by iain-anderson** [comment]
For v2.0 use of message bus should be the default, but posting via REST to core-data should be available by configuration

**Comment by iain-anderson** [comment]
Superceded by #688 and #689 - closing
