### ISSUE TITLE
device driver with consul takes so much cpu

### ISSUE THREAD

**Issue by kaisawind** [edgexfoundry/device-sdk-go#532]
I think it's a bug here. driver and consul takes so much cpu.
Using i7 CPU, the CPU usage is 20+%，Using A53 CPU,the CPU usage is 100+%.consul will use more CPU.
When using netstat to view the connection, you will find that there are many tcp timewait.

![Screenshot_20200529_093714](https://user-images.githubusercontent.com/4010613/83212273-c70bf180-a191-11ea-98a3-d912d35e87c0.png)

**Comment by kaisawind** [comment]
There is something wrong with message queue.
![Screenshot_20200529_095704](https://user-images.githubusercontent.com/4010613/83212830-29b1bd00-a193-11ea-8e4f-d87f76abe203.png)

**Comment by kaisawind** [comment]
I found the problem, but I need to confirm. Should it really be `Millisecond` here， or `Second`.
Using i7 CPU, fetchURL takes more than 290ms, but every 15ms will fetch url.

https://github.com/edgexfoundry/device-sdk-go/blob/e392cb03206751630a245b46d5bf5d4bcc819dd1/internal/endpoint/endpoint.go#L50-L52

**Comment by cloudxxx8** [comment]
solved by #533

**Comment by cloudxxx8** [comment]
Thanks, @kaisawind , I will ask to release 1.2.2 for this fix
