### ISSUE TITLE
Add the feature to automatically register Provision Watchers.

### ISSUE THREAD

**Issue by kurokobo** [edgexfoundry/device-sdk-go#534]
# 🚀 Feature Request

### Relevant Package

This feature request is for around Provision Watcher.

### Description

If we use the automatic device discovery feature, we have to manually register new Provision Watcher using the metadata API every time when we start a new EdgeX instance.
This is a little cumbersome.

### Describe the solution you'd like

It would be nice if we could invoke registration for new Provision Watcher automatically when edgex startup without any manual operation by just putting some files down in a designated location.

Similar feature already exists e.g. YAML for new Device Profiles, [[DeviceList]] for new Devices.
Not only hassle-free, but it also benefits that all configurations can be described in text files in advance.

**Comment by cloudxxx8** [comment]
@kurokobo we had a discussion about that, and we didn't make this feature on purpose.
We plan to remove this feature for Porfile and Device in the future.
The reason is that users are easy to get confused by that.  It should be for development purpose.
@iain-anderson please correct me if anything wrong

**Comment by kurokobo** [comment]
Thank you for the information, sorry for not knowing that you've already considered it.

It's a shame it won't be implemented, but it's good to know the detail and the reason.
Thank you, it's ok to close this issue.

**Comment by cloudxxx8** [comment]
no problem.  thanks for the contribution in the community.
