### ISSUE TITLE
How to distinguish physical devices

### ISSUE THREAD

**Issue by YvesZHI** [edgexfoundry/device-sdk-go#540]
I'm learning how to develop a Device Service for my own physical devices.

I'm reading the source codes: https://github.com/edgexfoundry/device-sdk-go/blob/master/example/driver/simpledriver.go

I've also tried to make some tests with this project: https://github.com/edgexfoundry/device-rest-go

As my understanding, if I have more than one physical devices with the same type, it doesn't seem that it is possible to distinguish the data sending to EdgeX-core through the Device Service.

Saying that I have two temperature sensors, S1 and S2, both of them are sending integers as the temparature values. After running EdgeX with `device-rest-go`, I get the output at the North Side as below:

```
{"device":"rand-numeric","id":"b7cb8bf3-4d0f-424e-9905-260715bddc20","origin":"1592211541283246270","readings":[{"origin":"1592211541283162186","valueType":"Int64","name":"int","device":"rand-numeric","value":"1"}]}
{"device":"rand-numeric","id":"9b956df5-55be-4d87-ba16-c4f37ba9a328","origin":"1592211544283997004","readings":[{"origin":"1592211544283926477","valueType":"Int64","name":"int","device":"rand-numeric","value":"2"}]}
```

The first message is generated by S1, and the second one is generated by S2. But I can't distinguish them. I was expecting some information about device name in the messages but I didn't find it.

So is it true that EdgeX doesn't provide any method to distinguish messages or did I misunderstanding something?

**Comment by cloudxxx8** [comment]
If they are different sensors, the device name should be different.  We distinguish devices by their names. The device fields here should be S1 or S2.

```
{"device":"S1","id":"b7cb8bf3-4d0f-424e-9905-260715bddc20","origin":"1592211541283246270","readings":[{"origin":"1592211541283162186","valueType":"Int64","name":"int","device":"S1","value":"1"}]}
{"device":"S2","id":"9b956df5-55be-4d87-ba16-c4f37ba9a328","origin":"1592211544283997004","readings":[{"origin":"1592211544283926477","valueType":"Int64","name":"int","device":"S2","value":"2"}]}
```

**Comment by YvesZHI** [comment]
@cloudxxx8   Are you sure that the real physical devices can send their own device names to the Device Service? 

They are two independent sensors but their types are the same. So I want to use one Device Service to serve the two sensors. In this case, I'm asking who can add a device name for each physical device. Do the physical devices have such a function? I kind of don't think so... So does it mean that I need to code my own Device Service, which has the capacity to distinguish the physical devices?

**Comment by cloudxxx8** [comment]
The Devices should be defined in core-metadata with their names, and the Device Service has to assign the name into Async value if it is asynchronous.
https://github.com/edgexfoundry/device-sdk-go/blob/fd75c29bc70b45e81e8d6526ecff9c2e7979e15f/pkg/models/asyncvalues.go#L11

If the Event/Reading is generated by Command, the Device would be also clear from the command client side.
https://github.com/edgexfoundry/device-sdk-go/blob/fd75c29bc70b45e81e8d6526ecff9c2e7979e15f/pkg/models/protocoldriver.go#L32
