### ISSUE TITLE
Update config.Clients usage for new naming scheme

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#546]
Related edgex-go issue: https://github.com/edgexfoundry/edgex-go/issues/2424

Idea is to use the service key constants as the keys. 

Need to do the same here to stay consistent, but this will have to what for v2.0.0 as it is a breaking change.

**Comment by iain-anderson** [comment]
Should this not be reversed, ie configurations which use "CoreData" changed to "Data". Looking in edgex-go, "CoreData" is the only place that a prefix to the service name is used.

**Comment by lenny-intel** [comment]
Yep, that does seem to be the smaller impact and more consistent change.

**Comment by lenny-intel** [comment]
I will create the issue on edgex-go and close this issue.

**Comment by lenny-intel** [comment]
Actually there is an older issue on edgex-go to address the key values is a "better" way, so I have changed this issue to match that one.

**Comment by cloudxxx8** [comment]
fixed in #804
