### ISSUE TITLE
Auto discovery on service startup

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#547]
https://github.com/edgexfoundry/device-sdk-go/blob/237059a1cc6afe5d06dcb2973311674b604926bf/internal/autodiscovery/autodiscovery.go#L32-L37

I propose the `time.Sleep` be moved to the bottom of the for loop to trigger discovery on service startup.

**Comment by hahattan** [comment]
Autoevents will wait for one duration to actually start reading event,  in my opinion it's better to keep these two consistent.
@iain-anderson what's the behavior of this issue in C-SDK, do we need to make this change ?

**Comment by iain-anderson** [comment]
CSDK fires the first autoevent immediately on startup
