### ISSUE TITLE
Update V2 swagger file to consist with edgex-go

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#555]
1. Change ping, metrics, and version APIs to GET and remove their request DTO
2. Add Versionable to all the response DTO

**Comment by cloudxxx8** [comment]
hold until the following PR merged
https://github.com/edgexfoundry/edgex-go/pull/2627
https://github.com/edgexfoundry/edgex-go/pull/2631

**Comment by iain-anderson** [comment]
Removed `hold` label as the prerequisite PRs are merged

**Comment by cloudxxx8** [comment]
reopen for #595
