### ISSUE TITLE
AutoEvent Resource field can't access DeviceResource without DeviceCommand

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#560]
see the issue 1 in https://github.com/edgexfoundry/edgex-docs/pull/192#issuecomment-667560073
AutoEvent Resource field should work with DeviceResource

**Comment by tonyespy** [comment]
I can confirm this behavior. I installed the edgexfoundry snap (1.2.1-20200721+14637657, revision: 2388), edited the **device.virtual.float.yaml** device profile and removed all of the deviceCommands. Once I activated the device-virtual, I started seeing errors for the auto events which specified deviceResources:

```
level=ERROR app=device-virtual source=command.go:206 msg="specified cmd: Float32 not found"
level=ERROR app=device-virtual source=executor.go:52 msg="AutoEvent - error occurs when reading resource Float32"
level=ERROR app=device-virtual source=command.go:206 msg="specified cmd: Float64 not found"
level=ERROR app=device-virtual source=executor.go:52 msg="AutoEvent - error occurs when reading resource Float64"

```

**Comment by tonyespy** [comment]
Please note that for this issue to occur, a coreCommand must exist with the exact name of the deviceResource.
