### ISSUE TITLE
Go Device SDK Provide internal API to retrieve credentials from a secret store

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#564]
https://github.com/edgexfoundry/edgex-go/issues/2888

Currently, device services need to store user name and password in the configuration file, and they should be stored in a secret store for production.

**Comment by lenny-intel** [comment]
Note that App Services already has this capability, which should be abstracted into go-mod-secrets so it can be used by both SDKs.

**Comment by tonyespy** [comment]
For reference, I opened the following issue for device-mqtt which deals with the same problem:

https://github.com/edgexfoundry/device-mqtt-go/issues/159

**Comment by iain-anderson** [comment]
Depends on https://github.com/edgexfoundry/go-mod-secrets/issues/53
