### ISSUE TITLE
SDK should update device service in metadata to reflect the configuration change

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-sdk-go#572]
In the edgex device service requirement document: 
> On startup, a DS must first query the Core Metadata service to determine if a _DeviceService_ instance (and associated _Addressable_ instance) with its _serviceName_ already exists. If a matching instance is found, a DS should update the instance to reflect to reflect current configuration.

GO-SDK currently didn't update the instance if a match is found, we should add this feature to be consistent with C-SDK.
https://github.com/edgexfoundry/device-sdk-go/blob/108cafbdc36a33829f2cd6e77abc07459d29f393/pkg/service/service.go#L142-L154

**Comment by masterclock** [comment]
this issue should be addressed asap, current I have to manually update the entry by hand
