### ISSUE TITLE
Option to prevent empty event creation

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-sdk-go#573]
In a device service generated from the SDK, on the AutoEvent loop, an event is always generated - even, in some cases, the HandleReadCommands does not have any readings to add to the event.  Today, the only way to interrupt this process is to throw an error in the HandleReadCommands.  This causes the event creation to be aborted but with an error message that does not indicate an appropriate reason why.  

Instead, configuration should be offered that allows no readings to be returned (the command value list is returned empty) and then the event is not create and sent to core data.

The use case for this is one where a device service must poll the device for new sensor readings/values.  On any given poll, the device could return no information.  This should, at the user's discretion, not cause a new and empty event to be created.

**Comment by iain-anderson** [comment]
Suggest that
- If HandleReadCommands returns an error, the SDK should report the error and not generate an Event
  - If this isn't the current behavior, it's a bug and should be fixed for Hanoi
- If HandleReadCommands returns no error and no readings, the SDK should generate an empty Event
  - If this isn't the current behavior, it's an enhancement and doesn't need to happen for Hanoi

**Comment by cloudxxx8** [comment]
> Suggest that
> 
> * If HandleReadCommands returns an error, the SDK should report the error and not generate an Event
>   
>   * If this isn't the current behavior, it's a bug and should be fixed for Hanoi
@hahattan please help confirm the behavior.

> * If HandleReadCommands returns no error and no readings, the SDK should generate an empty Event
>   
>   * If this isn't the current behavior, it's an enhancement and doesn't need to happen for Hanoi
@iain-anderson what is the current behavior in C SDK?  we should just make it the same as C SDK.

**Comment by iain-anderson** [comment]
Current CSDK implementation expects that if the Driver returns success, it should have recorded values for all of the readings. I think your device service will segfault if there are missing readings.

**Comment by cloudxxx8** [comment]
> Current CSDK implementation expects that if the Driver returns success, it should have recorded values for all of the readings. I think your device service will segfault if there are missing readings.

Do you mean there is no way to send out an event without readings in C Device Service?

**Comment by hahattan** [comment]
> Suggest that
> 
> * If HandleReadCommands returns an error, the SDK should report the error and not generate an Event
>   
>   * If this isn't the current behavior, it's a bug and should be fixed for Hanoi

This is the current behavior, if there's error both autoevent and http handler will report the error and no event would be generated.

> * If HandleReadCommands returns no error and no readings, the SDK should generate an empty Event
>   
>   * If this isn't the current behavior, it's an enhancement and doesn't need to happen for Hanoi

In this case, there's a segfault when converting CommandValue(readings) to Event

**Comment by hahattan** [comment]
> Suggest that
> * If HandleReadCommands returns no error and no readings, the SDK should generate an empty Event
>   
>   * If this isn't the current behavior, it's an enhancement and doesn't need to happen for Hanoi

v2 API doesn't allow empty Event, how about just not creating the event and skip pushing event to coredata like @jpwhitemn suggested ?

**Comment by iain-anderson** [comment]
> v2 API doesn't allow empty Event, how about just not creating the event and skip pushing event to coredata like @jpwhitemn suggested ?

OK, this also matches up with what is being proposed for filtering in the device service, ie events may be pushed with readings missing, but if there are no readings the event does not get pushed.
