### ISSUE TITLE
[Enhancement] Device-SDK should be notified about all the devices present at Start of Service

### ISSUE THREAD

**Issue by salmanazmat666** [edgexfoundry/device-sdk-go#590]
Whenever a device service starts it should know what devices are already present in the DB. This would be helpful in scenarios when service pushes data asynchronously only, and the service is restarted for some reason (e.g., some error occurred or the edge device is rebooted). In such cases, the service currently has no way of knowing what devices are present and with what configurations.

One possible way is to pass an array of devices in the `Initialize(logger, asyncCh, deviceCh)` function.

**Comment by ajcasagrande** [comment]
This is already possible like so:

```go
package driver

import (
	"fmt"
	"github.com/edgexfoundry/device-sdk-go/pkg/models"
	"github.com/edgexfoundry/device-sdk-go/pkg/service"
	"github.com/edgexfoundry/go-mod-core-contracts/clients/logger"
)

func (d *Driver) Initialize(lc logger.LoggingClient, asyncCh chan<- *models.AsyncValues, deviceCh chan<- []models.DiscoveredDevice) error {
	registered := service.RunningService().Devices()
	for _, device := range registered {
		lc.Debug(fmt.Sprintf("%+v", device))
	}
	return nil
}
```
