### ISSUE TITLE
Bug in Provision Watcher whitelist logic

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#598]
# Problem 
The [current implementation of whitelist logic for provision watchers](https://github.com/edgexfoundry/device-sdk-go/blob/master/pkg/service/async.go#L168-L186) will loop through all protocols and returns `false` the first time a whitelisted identifier is not found. On the surface this looks great, but the problem with this is that if you have 2 protocols, and only 1 of them matches (the other does not contain the field at all), this code will incorrectly fail it.

Example:

**ProtocolProperties**
```go
Protocols: map[string]contract.ProtocolProperties{
	"tcp": {
		"host":      info.host,
		"port":      info.port,
	},
	"metadata": {
		"vendor": "SomeCompany",
	},
},
```

**Provision Watcher**
```json
{
  "name": "my-provision-watcher",
  "identifiers": {
    "vendor": "SomeCompany"
  },
  "blockingidentifiers": {},
  "profile": {
    "name": "My.Device.Profile"
  },
  "service": {
    "name": "edgex-device-awesome"
  },
  "adminState": "UNLOCKED"
}
```

Result: **Not Matched**
`vendor` field was not found in `tcp` protocol, so `false` was returned.

# Solutions
There are two proposed solutions _depending on the functionality that is preferred_. Both will solve the issue presented above, however there is an edge case to be considered. I have provided code for both if you click the dropdowns. (EDIT: Example code removed as it was not tested and potentially buggy)

Here is a test setup that will be referred to in the solutions.

**Test Provision Watcher**
```json
"identifiers": {
  "port": "1883"
},
```

**Device A**
```go
Protocols: map[string]contract.ProtocolProperties{
	"mqtt": {
		"port": "1883",
	},
	"tcp": {
		"port": "80",
	},
},
```

**Device B**
```go
Protocols: map[string]contract.ProtocolProperties{
	"mqtt": {
		"port": "1883",
	},
	"other": {
		"some": "data",
	},
},
```

## Solution 1
- Passes if identifier is matched in at least 1 protocol, and is missing in the rest. 
- Will fail if any protocol contains the identifier field but does not match.

### Results
- `Device A` **fails** because `tcp` protocol contained field `port` which did not match `1883`, even though `mqtt` matched
- `Device B` **passes** because `mqtt` protocol matches, and `other` did not contain the field `port` at all

## Solution 2
- Passes as long as at least 1 protocol contains a proper match, regardless of any failures in other protocol matching

### Results
- `Device A` **passes** because even though `tcp` protocol match failed, we only required 1 protocol to match, which did: `mqtt`
- `Device B` **passes** because `mqtt` protocol matches, and `other` did not contain the field `port` at all

**Comment by iain-anderson** [comment]
This is ambiguous in the Discovery design. I prefer solution 2, ie the new device is accepted if any of its protocols match the provision watcher.

**Comment by ajcasagrande** [comment]
I wanted to point out that the current implementation in #615 will still fail in certain scenarios, which one _might_ expect it to pass. Again it comes down to design and expectations, partially because of the ambiguity like @iain-anderson has mentioned.

**Watcher**
```go
contract.ProvisionWatcher{
	Identifiers: map[string]string{
		"port": "1883",
		"some": "data",
	},
}
```

**DiscoveredDevice**
```go
Protocols: map[string]contract.ProtocolProperties{
	"mqtt": {
		"port": "1883",
	},
	"other": {
		"some": "data",
	},
},
```

The code from #615 expects all identifiers to be matched in a single protocol, thus causing this device to not be matched.

**Comment by ajcasagrande** [comment]
My original solution 2 (which I edited out the code as it was un-tested) does pass in the above scenario. 

However, with all of the corner cases that exist due to the ambiguity, I believe it really needs to have some unit tests as a baseline of what should and what shouldn't pass.

**Solution 2**
```go
func whitelistPass(d dsModels.DiscoveredDevice, pw contract.ProvisionWatcher, lc logger.LoggingClient) bool {
	// a candidate device should pass all identifiers
	for name, regex := range pw.Identifiers {
		foundMatch := false

		// ignore the device protocol properties name
		for _, protocol := range d.Protocols {
			if value, ok := protocol[name]; ok {
				matched, err := regexp.MatchString(regex, value)
				if !matched || err != nil {
					lc.Debug(fmt.Sprintf("Device %s's %s value %s did not match PW identifier: %s", d.Name, name, value, regex))
				} else {
					lc.Debug(fmt.Sprintf("Device %s's %s value %s matches PW identifier: %s", d.Name, name, value, regex))
					foundMatch = true
				}
			}
		}

		if !foundMatch {
			lc.Debug(fmt.Sprintf("Identifier field: %s, did not exist or was not matched in discovered device %s", name, d.Name))
			return false
		}
	}
	return true
}
```

**Comment by hahattan** [comment]
I went back to original design and it did state that `A candidate new device passes a ProvisionWatcher if all of the Identifiers match, and none of the BlockingIdentifiers.`  So the question is do we allow the `PW.identifiers` to be matched in different `Device.Protocols`. Once we have the conclusion I can then make the change, add the unit test and update the docs if necessary.

**Comment by iain-anderson** [comment]
Suggest the following is added to the design doc:

> For devices with multiple `Device.Protocol`s, each `Device.Protocol` is considered separately. A match on any of the protocols results in the device being added.

**Comment by hahattan** [comment]
> Suggest the following is added to the design doc:
> 
> > For devices with multiple `Device.Protocol`s, each `Device.Protocol` is considered separately. A match on any of the protocols results in the device being added.

Need clarification on **A match** here, does it mean the protocol match all of the identifiers ? (which is the current implementation of Go-SDK) If that's the case I'll go ahead update the README and add the unit tests.

**Comment by iain-anderson** [comment]
> > Suggest the following is added to the design doc:
> > > For devices with multiple `Device.Protocol`s, each `Device.Protocol` is considered separately. A match on any of the protocols results in the device being added.
> 
> Need clarification on **A match** here, does it mean the protocol match all of the identifiers ? (which is the current implementation of Go-SDK) If that's the case I'll go ahead update the README and add the unit tests.

Yes. I'll keep the line which says "A candidate new device passes a ProvisionWatcher if all of the `Identifiers` match, and none of the `BlockingIdentifiers`."

**Comment by ajcasagrande** [comment]
Thank you for the clarification and unit tests.
