### ISSUE TITLE
Add registry settings support

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#6]
If the registry/consul is enabled on service startup, try to read initial configuration settings from consul.  

In order for this feature to work, the settings for the device service need to be injected into consul via core-config-seed, or some other out-of-band mechanism.

**Priority**: High
**Estimated effort**: 5d

**Comment by tonyespy** [comment]
This has been partially implemented as a device service that uses the SDK will register itself, and attempt to read its configuration from the registry if told to do so on startup.

What hasn't been implemented is a mechanism to populate the consul/registry with initial configuration for device services.  We decided this should be the responsibility of a device service (via the SDK). If the device service is told to use the registry, but finds no configuration exists in the registry, then it should use its local configuration to seed the registry.

**Note** - I'm fine if we want to close this and open a new issue specifically for the initial configuration seeding.

**Comment by cloudxxx8** [comment]
fixed by #186
