### ISSUE TITLE
More Provision Watcher Bugs

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#606]
https://github.com/edgexfoundry/device-sdk-go/blob/4a1412fe3679be6652f13296ba45411ccc085237/pkg/service/async.go#L128-L162

There are a couple of code flow bugs in the above code. Namely:

- You are looping through each of the provision watchers, but are breaking out of the loop at the first non-pass result. This makes the rest of the PWs unusable.

- If a device is matched and added, it will continue to be matched against the rest of the PWs, instead of breaking.

**Comment by hahattan** [comment]
@ajcasagrande please help verify #615 resolved your concern, thanks.
