### ISSUE TITLE
Discover function lock release issue

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#609]
Currently the lock for a currently running discover process is only released when data is sent over the `deviceCh`.

https://github.com/edgexfoundry/device-sdk-go/blob/fb7330ff9bf92f9fa1366cf6687914141b9e28cd/pkg/service/async.go#L124-L125

In reality it should be tied to when the discover function completes.

https://github.com/edgexfoundry/device-sdk-go/blob/5d943473fe8cb7b2263b29163a15a9eda06ca963/internal/handler/control.go#L57

The reason for this is because the way it is now, the only way to "tell" the SDK that you are done is to send data over that channel, even if it is just `nil`. If you do not send data on that channel the SDK will assume you are still discovering forever.

On top of that it does not allow the discover process to add devices on-the-fly as they are discovered, otherwise the SDK will incorrectly assume discovery is complete and release the lock. This forces the developer to buffer up the discovered devices and release them as a batch at the end.

**Comment by hahattan** [comment]
> The reason for this is because the way it is now, the only way to "tell" the SDK that you are done is to send data over that channel, even if it is just `nil`. If you do not send data on that channel the SDK will assume you are still discovering forever.

202 indicates `discovery has been triggered or is already running`. Back during I was implementing this, in my opinion whenever there's something return from Discovery (i.e. sent back to channel) we can continue trigger another discovery process.

> On top of that it does not allow the discover process to add devices on-the-fly as they are discovered, otherwise the SDK will incorrectly assume discovery is complete and release the lock. This forces the developer to buffer up the discovered devices and release them as a batch at the end.

This do limit the implementation of ProtocolDiscovery to send devices as a batch in one protocol-specific discovery process though.

 @lenny-intel @iain-anderson @cloudxxx8 may you share you thought on above topics ?

**Comment by iain-anderson** [comment]
I'd be tempted to write a wrapper function that called discovery.Discover() and released the lock when that call had completed.
Then `go wrapper`, and remove the unlock code from the async handler
