### ISSUE TITLE
Golang sdk doc is not updated

### ISSUE THREAD

**Issue by ThomasGeor** [edgexfoundry/device-sdk-go#618]
If you follow https://docs.edgexfoundry.org/1.2/getting-started/Ch-GettingStartedSDK-Go/ tutorial you will be asked to copy this file in the new device service, but the file doesn't exist. This is miss breaks the make build process and can be found in the Makefile, in line :
https://github.com/edgexfoundry/device-sdk-go/blob/7376f7b5b06e33bb8acc21cf64a8bee67a63ba67/Makefile#L12

Commenting out this line made a successful build.

**Comment by FelixTing** [comment]
The doc is OK. @ThomasGeor  I guess you missed the step shown below:
![image](https://user-images.githubusercontent.com/43240457/96204035-e1eecf00-0f95-11eb-9838-486404036e3f.png)
Could you please help check this part in your Makefile?

**Comment by iain-anderson** [comment]
Closing. Please re-open if you think the documentation is still incorrect.
