### ISSUE TITLE
DeviceService struct naming incompatibility

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#643]
I noticed a small breaking change from `1.2.3` to `1.2.4-dev.34` (current latest tag).

In the public package:
```go
import "github.com/edgexfoundry/device-sdk-go/pkg/service"
```

`Service` was renamed to `DeviceService`, which introduced compilation errors in my project. Easily to fix, yes, but would typically warrant more than just a `patch` bump in `semver`.

**Comment by cloudxxx8** [comment]
@ajcasagrande in the official release, the version number will become 1.3.0.
Is it ok?
