### ISSUE TITLE
Implement Device AutoEvents SDK APIs

### ISSUE THREAD

**Issue by tzstoyanov** [edgexfoundry/device-sdk-go#647]
Currently there are two ways to attach an AutoEvent to a device:
 - Define events in the configuration.toml, in the DeviceList with pre defined devices.
 - Use the [V1 API](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.0#/default/put_v1_device) to update the whole device

However these two ways are not suitable for device auto discovery use case, where an AutoEvent should be attached to the newly discovered device, from the Device Service context.
It will be useful to have SDK APIs to add / remove AutoEvents to cover the device auto discovery use case. 

I need such functionality and would like to implement and post a PR. What do you think, will it be useful to have such APIs ?

**Comment by iain-anderson** [comment]
Agreed that this can be landed for 1.3.1. Hold until Hanoi is released.
For V2 / Ireland, Provision Watchers will be extended to include AutoEvent declarations
