### ISSUE TITLE
General configuration loading mechanism for the [Driver] section

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#648]
The [Driver] section in the configuration file is for the Device Service which is based on the SDK.
We should provide an internal API for the developers to load the configuration in a general way.

**Comment by lenny-intel** [comment]
Suggest using this approach from one of Intel's Reference Implementations.
https://github.com/intel-iot-devkit/automated-checkout-utilities/blob/master/config.go#L45

**Comment by tonyespy** [comment]
@cloudxxx8 I don't understand this issue. It actually seems somewhat related to the issue #324 which was closed recently as the **[Driver]** section can easily be accessed via `service.DriverConfigs`.

**Comment by cloudxxx8** [comment]
@tonyespy yes, developers can access them via `service.DriverConfigs`, but the returned type is `map[string]string`
they need to write the code like we did in mqtt:
https://github.com/edgexfoundry/device-mqtt-go/blob/7a1b18f551239dfc150e88617034cadc3790dddc/internal/driver/config.go#L78-L106

The purpose of this issue is to provide a helper function for that, as the Reference Implementations Lenny suggested.

**Comment by hahattan** [comment]
Does #833 resolve this ?

**Comment by iain-anderson** [comment]
@lenny-intel  @hahattan  #833 allows the custom structured config to take any name, so we could continue to use `[Driver]` ?

**Comment by lenny-intel** [comment]
> allows the custom structured config to take any name, so we could continue to use `[Driver]` ?
@iain-anderson,  We choose to leave the existing `[Driver]` (Device Services) and `[ApplicationSettings]` (App Service) in place for those services that only have simple needs. 
As for `custom structured config to take any name`,  with the way the TOML module works, we can not restrict the `name` they choose to use when loading from the local file. We require they provide the `name` so we can push/pull that section from Consul.

**Comment by lenny-intel** [comment]
> do you think #833 resolve this,
> If we use [CustomConfig] section instead of strictly under [Driver] section ?

@hahattan , yes I think the new Custom config resolves this issue.

**Comment by iain-anderson** [comment]
Would prefer to continue use of existing `Driver` section but with the additional capabilities re: structure

**Comment by lenny-intel** [comment]
@iain-anderson , can we have this on the agenda for the next Device Service WG meeting?

**Comment by iain-anderson** [comment]
@lenny-intel  @cloudxxx8 yes we can talk about this on the 12th

**Comment by iain-anderson** [comment]
closed #833 using custom config
