### ISSUE TITLE
Asynch channel of custom driver doesn't push data to core-data

### ISSUE THREAD

**Issue by ThomasGeor** [edgexfoundry/device-sdk-go#660]
Hello ,

I have made a custom device-service to support a KNX device and i am using identical code to mqtt-device-service's **onIncomingDataReceived** from **incominglistener.go** file example to push data to core data. 
I want to push data to core data using **asyncCh chan<- *sdkModel.AsyncValues**. 
I pass my driver's **asyncCh chan<- *sdkModel.AsyncValues** member to the **goroutine** which handles this asynchronous feature and is executed in the driver's Initialize function. After executing **asyncCh <- asyncValues**, i don't see any logging printing that my event was pushed to core-data and i want to ask if this is an error. I am attaching my code below as well as **the output i expect to see but don't see it:**
```
func Asynchronous_Readings(ip_addr string,log logger.LoggingClient,wg *sync.WaitGroup,asyncCh chan<- *sdkModel.AsyncValues){
  defer wg.Done()
  StartIndicationSession(ip_addr,log)
  for {
    data,read_status := GetIndication(ip_addr,log)
    // if the indication is from a put command's response
    // don't push the data because it's already pushed
    if read_status {
      // extract the info from the response
      dpt_id := data["Datapoint"].(float64)
      datapoint_id := int(dpt_id)
      // corvert based on the datapoint's format
      value := DatapointResponseToValue(data)
      log.Info(fmt.Sprintf("Datapoint,Value : %v,%v",datapoint_id,value))
      device_resource := DatapointIdToDeviceResource(datapoint_id)
      // prepare to load the data to core-data
      service := sdk.RunningService()
      deviceObject, ok := service.DeviceResource(Device_Name, device_resource, "get")
      if !ok {
        log.Info(fmt.Sprintf("Failed to find device resource"))
    	}else{
        req := sdkModel.CommandRequest{
      		DeviceResourceName: device_resource,
      		Type:               sdkModel.ParseValueType(deviceObject.Properties.Value.Type),
      	}
        result, err := newResult(req, value)
        if err != nil {
          log.Info(fmt.Sprintf("Failed to make the request"))
      	}else{
          asyncValues := &sdkModel.AsyncValues{
        		DeviceName:    Device_Name,
        		CommandValues: []*sdkModel.CommandValue{result},
        	}
          // send the data
          if service.AsyncReadings(){
            log.Info(fmt.Sprintf("Data was sent"))
            asyncCh <- asyncValues
          }
        }
      }

    }else{
      log.Info(fmt.Sprintf("Read failed"))
    }
  }
}
```

**The output i should see is in util.go of the device-sdk-go/internal/common:**
```
LoggingClient.Debug("SendEvent: EventClient.MarshalEvent encoded event", clients.CorrelationHeader, correlation)
LoggingClient.Info("SendEvent: Pushed event to core data", clients.ContentType, clients.FromContext(ctx, clients.ContentType), clients.CorrelationHeader, correlation)
```
Is this a go channel problem? Is my custom driver which is based in the sdk-driver implemented incorrectly? An MQTT device i am using is working properly and pushes the events to core-data.

**Comment by ThomasGeor** [comment]
Even if it does not print the messages, you can check if your data arrive by sending an http request to core-data asking for the count of event it receives using :
**http://localhost:48080/api/v1/event/count/{device name in string}**
You can check out this link :
**https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.0#/default/get_v1_event_count__deviceId_**
In my case it arrives there without printing the Push messages so everything is good .

**Comment by cloudxxx8** [comment]
It depends on which version of SDK you are using.  The latest one print the log in Debug level, not Info
https://github.com/edgexfoundry/device-sdk-go/blob/cbcd560d226450c2fc49532ec953a0990705dfef/internal/common/utils.go#L97
