### ISSUE TITLE
"Writable" configuration changes

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/device-sdk-go#662]
- LogLevel should be at the top level of the Writable section
- Other elements should be structured to mirror the non-writable structure

**Comment by hahattan** [comment]
Do we need to work on this still ? The current configuration seems fit the requirement:
https://github.com/edgexfoundry/device-sdk-go/blob/9c99b3ad7d2e4ca826a6fb04090188d28e886681/example/cmd/device-simple/res/configuration.toml#L1-L9

**Comment by cloudxxx8** [comment]
you are right.  We can close this one.
