### ISSUE TITLE
Model / DTO changes

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/device-sdk-go#663]
- Reading: "Name" → "ResourceName"
- Event, Reading: Add "ProfileName"
- OperatingState: States change to "UP" and "DOWN"

**Comment by cloudxxx8** [comment]
fixed in 
https://github.com/edgexfoundry/go-mod-core-contracts/pull/374
https://github.com/edgexfoundry/go-mod-core-contracts/pull/385
