### ISSUE TITLE
core-metadata to inform DS of changes to its AdminState via callback

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/device-sdk-go#664]
It is available for V1, but need some enhancement for V2.

**Comment by iain-anderson** [comment]
This should include an update in openapi/v2/device-sdk.yaml

**Comment by hahattan** [comment]
this is resolved in https://github.com/edgexfoundry/device-sdk-go/commit/9ee22048eba5e2985511ad40af05891377efe0df
