### ISSUE TITLE
Replace the DeviceList in the toml file with a "devices" directory, as for profiles

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/device-sdk-go#668]
DeviceList in the configuration makes people confused.
It should be defined in another folder with JSON format.

**Comment by iain-anderson** [comment]
Add configuration element `[Device]/DevicesDir` to go with `[Device]/ProfilesDir`. If not set, no devices/profiles are uploaded.

**Comment by iain-anderson** [comment]
This was discussed in the WG on Dec 14th 2020 and there was a preference to retain the possibility to use .toml
Both .toml (re-using the [[DeviceList]] format) and .json should be supported

**Comment by iain-anderson** [comment]
Discussed again in the WG on Mar 15th 2021:
.toml files should be supported
.json as an alternative for both devices and device profiles is a stretch goal for v2.0
Recommend that configuration.toml, profiles and devices be in three separate directories, eg:
```
res/configuration.toml
res/profiles/*
res/devices/*
```
Examples should follow this pattern, but the SDK should tolerate all files being in the same directory. So when considering .toml files for device upload, the configuration file should be skipped. And when considering .json files the SDK should auto-detect whether they contain profiles or devices.

**Comment by hahattan** [comment]
there's a `ProfilesDir` setting in the configuration.
https://github.com/edgexfoundry/device-sdk-go/blob/5b084bdeafa1e122a5c890164a05a3ac30530fc3/example/cmd/device-simple/res/configuration.toml#L65
Do you think we can add something like `DevicesDir`(defaulting `/res/devices`) and put the .json in the directory. On the other hand if this is not set, we update what's defined in .toml ?

**Comment by iain-anderson** [comment]
`DevicesDir` is right, but default should be to not load devices. Similar for `ProfilesDir`

**Comment by hahattan** [comment]
Do you mean default to an empty string and load from .toml file ?

**Comment by iain-anderson** [comment]
No, if empty don't load from anywhere
