### ISSUE TITLE
Add param member to CommandRequest and remove from ProtocolDriver.HandleCommands

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#67]
The ProtocolDriver HandleCommands function has a parameter called 'params' which is used to pass command actuation parameters to the protocol specific code. Currently if the 'set/put' form of the command endpoint is called, this parameter is the corresponding JSON passed to the endpoint. It was suggested instead that we should parse this JSON and add a new parms field to the CommandRequest struct to simply the work the ProtocolDriver has to perform.

**Comment by iain-anderson** [comment]
I think the above should read "set" form or "put" form rather than "All" form.
In the C SDK I've re-used the CommandResult struct to hold the parsed JSON - so for readings the protocol driver fills in the CommandResult and for commands it reads parameters from it.

**Comment by iain-anderson** [comment]
Also in the CommandResult I've omitted the Device Name and ID (as these may be common across an array / slice of CommandResults), the Resource Operation (as this may be found in a corresponding CommandRequest) and the ValueDescriptor (as this is unused).

**Comment by tonyespy** [comment]
@iain-anderson I've updated the my original description.

As for leaving out the DeviceId and DeviceName values, I think that's OK, however removing them completely (as well as ResourceOperation) would cause problems for asynchronous readings (see async.go).

**Comment by iain-anderson** [comment]
Would typing the channel (for async) on `struct { CommandRequest; CommandResult }` do what we need?

**Comment by iain-anderson** [comment]
@tonyespy could we change the typing on the async channel, eg to `{ string; []CommandRequest; []CommandResult }` ?
(the string being the device name)

**Comment by tonyespy** [comment]
@iain-anderson I don't see why not? That said, currently a protocol impl can set device name or id in the `CommandResult`, so maybe we make the channel `{ string; string; []CommandResult }`?

I see you also are including a `[]CommandRequest` parameter, probably so that the ResourceOperation can be used to lookup the `DeviceObject`, right? What if we changed removed the  ResourceOperation pointer from `CommandRequest` and replaced it with the `DeviceObject.Name`? This is all its used for in the command endpoint reply processing.

And finally, there's a TODO comment in `CommandResult` which suggests encoding `BoolResult` into `NumericResult`. Doing so allows us to drop `BoolResult` from the struct, so we should do this prior to our first release.

**Comment by iain-anderson** [comment]
@tonyespy I think the processing on the async channel will need the `DeviceObject` (for `DeviceObject.Name` and the `PropertyValue`) and the `ResourceOperation` (for `Mappings`).

**Comment by cloudxxx8** [comment]
For the async channel, I am wondering whether we could deal with that in CommandHandler to reduce the complexity of ProtocolDriver.  ProtocolDriver only needs the Addressable information and CommandHandler always knows Device information.

**Comment by iain-anderson** [comment]
The reason I'd like to re-use CommandResult for the parameters in a put command is that we'd do the conversion from strings in the SDK and save the ProtocolDriver implementer from having to do it.

**Comment by cloudxxx8** [comment]
Please ignore my previous comment.  I just realized the async channel is for the scenario of the device would push data to Device Service positively.

**Comment by cloudxxx8** [comment]
@tonyespy  and @iain-anderson, to leverage "CommandResult" for put command, it should look like the following:
```
HandlePutCommands(addr models.Addressable, reqs []CommandRequest, params map[string]CommandResult) error
```

However, the type name of CommandResult looks weird here.  Do you have any idea to rename this struct?  May we rename it to CommandValue or CommandParameter? This struct could be used generally.  In this case, the API might look like:

```
HandleGetCommands(addr models.Addressable, reqs []CommandRequest) ([]CommandValue, error)

HandlePutCommands(addr models.Addressable, reqs []CommandRequest, params map[string]CommandValue) error
```
