### ISSUE TITLE
Support for certain dynamic updates to device profiles

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/device-sdk-go#671]
Need additional design

**Comment by weichou1229** [comment]
Related issue https://github.com/edgexfoundry/go-mod-core-contracts/issues/326

**Comment by iain-anderson** [comment]
See https://github.com/edgexfoundry/edgex-docs/pull/674

**Comment by cloudxxx8** [comment]
ADR is approved, so this issue is good to go

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/issues/3918 and https://github.com/edgexfoundry/edgex-go/issues/3933
