### ISSUE TITLE
In Go Device SDK, asynCh is closed by SDK while it is supposed to be closed by the driver upon stopping the service.

### ISSUE THREAD

**Issue by salmanazmat666** [edgexfoundry/device-sdk-go#683]
In the comments above the driver.Stop() it says the driver is supposed to close the async channel.
```
// Stop the protocol-specific DS code to shutdown gracefully, or
// if the force parameter is 'true', immediately. The driver is responsible
// for closing any in-use channels, including the channel used to send async
// readings (if supported).
```

While this not the case. The channel is closed by the SDK before driver.Stop() is called. This causes issues because the driver might try to send the data on a closed channel before it is made aware of the fact that shutdown procedure has started.

**Comment by FelixTing** [comment]
The closing channel call in SDK has been removed by [PR#628](PR#628).

**Comment by cloudxxx8** [comment]
@salmanazmat666 Please use the 1.3.0 release, it should contain the fix you need
