### ISSUE TITLE
Question about deleting a device service

### ISSUE THREAD

**Issue by ThomasGeor** [edgexfoundry/device-sdk-go#693]
Is there any way to delete a device service?

I am trying to change one of my device-services Host address and there is not option to delete it in edge-ui-go nor any api to delete the device service itself and start it with a new service Host address.

**Comment by cloudxxx8** [comment]
Please use the Device Service DELETE API in core-metadata
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.0#/default/delete_v1_deviceservice_name__name_

**Comment by ThomasGeor** [comment]
Thank you for your information!
It worked this way. It would be good if this option was added to the ui as well!
Also is there a way to update the Service's variables e.g Host when it' already registered?

**Comment by ThomasGeor** [comment]
I finally fixed it . 
Way to fix a device service's full delete and then register it with new configuration options:
While the device service is running use this delete service [Api](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.0#/default/delete_v1_device_name__name_).
After that use this [Api](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.0#/default/delete_v1_addressable_name__name_) to delete it's addressable as well since it's still stored.
After doing both steps restart the service e.g docker restart edgex-device-virtual.

**Comment by cloudxxx8** [comment]
@ThomasGeor thanks for the feedback, and we will make it easier to use in V2.  We at least remove the external Addressable object.
I guess this issue will address what you need
https://github.com/edgexfoundry/device-sdk-go/issues/589

**Comment by cloudxxx8** [comment]
Sorry, it should be this one
https://github.com/edgexfoundry/device-sdk-go/issues/572
