### ISSUE TITLE
Failed to push event - too many events that core data can’t keep up

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-sdk-go#698]
Related to #657 - the long term solution to this problem (per Core WG meeting of 12/17) is to explore better flow control.
This is something to explore past increase in buffers or retry loop.

**Comment by cloudxxx8** [comment]
@jpwhitemn why did you put invalid label?  do you mean ireland?

**Comment by jpwhitemn** [comment]
Apologies @cloudxxx8 - meant to put ireland tag on it and selected wrong "i" word.

**Comment by cloudxxx8** [comment]
this issue is resolved by the message bus usage in V2
@jpwhitemn please see whether we can close this issue

**Comment by cloudxxx8** [comment]
this issue is resolved by the message bus usage in V2, closing this issue
