### ISSUE TITLE
Add service dependency startup logic

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#7]
Per the [California Service Name design](https://wiki.edgexfoundry.org/download/attachments/7602423/ServiceNameDesign-v6.pdf?version=1&modificationDate=1523468903000&api=v2), an EdgeX service should ensure that its dependent services are available before responding to REST endpoints, including ping.

If the registry/consul is specified on startup, then the SDK should query Consul to determine availability of Core Data and Metadata.  If the registry is not specified, then the SDK must query the service directly via REST to ensure availability.

Once dependent services have been been verified as available:
 * if the registry is being used, then the SDK should register the device service with consul

 * the SDK should start responding to REST requests

**Priority**: High
**Estimated effort**: 2d

**Comment by weichou1229** [comment]
@tonyespy I'm working on this issue.

**Comment by cloudxxx8** [comment]
fixed by #74
