### ISSUE TITLE
Consume dependent V2 modules

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#736]
Update to V2 version of these modules:

- go-mod-bootstrap
- go-mod-core-contracts 
- go-mod-registry 

1. Update go.mod file to reference new v2.0.x version of module
2. Update all import paths for the module to include /v2 in the path.

See the PR for edgex-go for example:  https://github.com/edgexfoundry/edgex-go/pull/3032/files

**Comment by hahattan** [comment]
pending on https://github.com/edgexfoundry/go-mod-bootstrap/pull/149, https://github.com/edgexfoundry/go-mod-core-contracts/pull/434, https://github.com/edgexfoundry/go-mod-registry/pull/68
