### ISSUE TITLE
Use yaml.v3 library instead of yaml.v2

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#748]
We have a dependency using yaml.v3 and our code is using yaml.v2, so we have both library in our build.
We should use only one of them.

**Comment by cloudxxx8** [comment]
hold this issue until yaml v3 is official released

**Comment by jpwhitemn** [comment]
Discussed in the Kamakura planning meeting.  Considered a stretch goal for Kamakura.  Needed for code hygiene purposes.

**Comment by cloudxxx8** [comment]
this has been done by https://github.com/edgexfoundry/device-sdk-go/commit/cf13810e1e59382d3745b709a3f2cecf0d1bf80c#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
