### ISSUE TITLE
feat: Optimize the Modbus client's error log

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#749]
User may setup the Modbus device incorrectly and device-modbus throw error log like the following message:
> Handler - execReadCmd: error for Device: Modbus TCP test device cmd: HVACValues, modbus: exception '2' (illegal data address), function '131' /api/v1/device/f6d51c16-1a47-4020-a579-091e56723124/HVACValues 

So it worth to improve the error log according to online docs:
https://en.wikipedia.org/wiki/Modbus#Exception_responses
http://www.simplymodbus.ca/exceptions.htm

**Comment by vijay-hcl-epl** [comment]
@cloudxxx8 , I have made changes in device-sdk-go repo and submitted a PR. Please check.

The old error log was not readable. It was like below"

> Handler - execReadCmd: error for Device: Modbus-TCP-Device-2 cmd: Current, modbus: exception '2' (illegal data address), function '131' /api/v1/device/6c2ffedd-6b54-4443-bf9e-130395d5a402/Current

The new error log is readable and looks like below:

> Read Error - modbus: exception '2' (illegal data address), function '131'; Device Name: Modbus-TCP-Device-2; CMD: Current

**Comment by hahattan** [comment]
v2 API has refactored the error message to the following format:
https://github.com/edgexfoundry/device-sdk-go/blob/2e0b14878cfb4a574be8745ab7c226ce26d53775/internal/v2/application/command.go#L164

which is quite similar to what you've proposed in the PR. If it's acceptable are you willing to wait for the v2 release because v1 code is going to be removed soon or later.

**Comment by vijay-hcl-epl** [comment]
@cloudxxx8 , @hahattan , Thank you for the comments.

As part of the PR#750, I have suggested a change to remove the URL path in http response in restfuncs.go. This URL path showing up in http response might confuse the user on error cases. This change is not there in PR #746.

Please check and let me know whether this URL path removal change is needed or not for v2.

Thank you,
Vijay

**Comment by hahattan** [comment]
in v2 http controller we only include the URL path inside the log:
https://github.com/edgexfoundry/device-sdk-go/blob/2e0b14878cfb4a574be8745ab7c226ce26d53775/internal/v2/controller/http/controller.go#L64-L66

**Comment by vijay-hcl-epl** [comment]
Thank you @hahattan for the clarification. Sorry I missed to notice. Then I think this issue can be closed. Requesting @cloudxxx8 to confirm.

**Comment by cloudxxx8** [comment]
no problem.  thanks for the help from both of you.
close this issue.
