### ISSUE TITLE
Insert more Debug and Warning log inside the source code

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#75]

**Comment by tonyespy** [comment]
@cloudxxx8 please provide a description.

**Comment by cloudxxx8** [comment]
Not all of the functions contain Debug or Warning log, and they are important to issue handling.
We should examine the code and insert proper Debug or Warning log into the code

**Comment by tonyespy** [comment]
I'm not sure this really needs to be considered a bug/issue? I think as we move forward, developers should strive to add Debug and/or Warning log messages where necessary. That said, I don't think we should retroactively go back and add additional Debug and/or Warning log messages at this point.

**Comment by tonyespy** [comment]
We're going to close this out based on our discussion today. @cloudxxx8 if there are specific areas which need additional logging, please file an issue with the details...
