### ISSUE TITLE
Standardize the format of log messages

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#76]
The format of log messages are not consistent in the code, so we should identify the format and refine all the log messages

**Comment by tonyespy** [comment]
@cloudxxx8 please provide a description.

**Comment by cloudxxx8** [comment]
The format of log messages are not consistent in the code, so we should identify the format and refine all the log messages

**Comment by tsconn23** [comment]
Recommend using the LoggingClient from go-mod-core-contracts which will provide key/value logging format as well as some basic fields (time, service name, log level) etc.

I added some documentation regarding the keys we currently use in this PR
https://github.com/edgexfoundry/edgex-go/pull/1083

It doesn't look like it has made it out to the documentation site yet though.

**Comment by tonyespy** [comment]
@cloudxxx8 Please add a description.

**Comment by tsconn23** [comment]
I'm asking @brandonforster to defer work on this for now until more clarity around message structure is obtained. The current SDK logger utilizes the `contracts.LoggingClient` through an alias so log messages are currently output as key/value pairs, which is a step in the right direction.

You can find documentation related to the existing keys here:
https://github.com/edgexfoundry/edgex-go/blob/master/docs/support/logging/Ch-Logging.rst#edgex-logging-keys

It would be good to utilize existing keys were necessary in re-formatting log statements. However adding new keys is fine if the use case warrants.

**Comment by cloudxxx8** [comment]
We've opened PR https://github.com/edgexfoundry/device-sdk-go/pull/280 to add correlation id.
This issue would focus on the message format only.  How about using the following format?
[$package.$func]  xxxxxxxx

**Comment by cloudxxx8** [comment]
Some log message uses the following format, but not all
$package - $func: xxxxx
The purpose of this issue is to make all log message consistent in this repository, or we could just remove all the package and func name information

**Comment by cloudxxx8** [comment]
After discussing with @weichou1229 , we will remove "$package - $func:" from log messages because the current logger prints out the file name and line number.  The $package and $func in log messages is unnecessary.
