### ISSUE TITLE
Review, refine, and publish the go doc content of public APIs

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#77]
when I opened this issue, we didn't have complete go doc for each public API. Now, I would like to examine all of them before next release

**Comment by tonyespy** [comment]
@cloudxxx8 please provide a description... it's unclear what this issue means.

**Comment by cloudxxx8** [comment]
when I opened this issue, we didn't have complete go doc for each public API.  Now, I would like to examine all of them before next release

**Comment by tonyespy** [comment]
@cloudxxx8 Where is our godoc published? Also your comment sounds reasonable, can you make it the description instead of comment?

**Comment by cloudxxx8** [comment]
@tonyespy we didn't publish our godoc. I thought we should do that in this release.
