### ISSUE TITLE
Replace all normal error type with errors.EdgeX in v2

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#778]
errors.EdgeX could be also used as a normal error.  We should make the source code consistent.

**Comment by hahattan** [comment]
I think it's fine to return `errors.Edgex`, but the returning type should still remain `error`.
This prevent the scenario that device service developer get the `Type does not implement 'errors.Edgex...` error when calling SDK function right after DS's custom function.

**Comment by cloudxxx8** [comment]
agree.  we just need to modify the SDK internal error usage.
