### ISSUE TITLE
Create a customizable configuration field and API for users

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#78]
The SDK currently manages all configuration (local and via the registry). If an author of a device profile wants to add protocol-specific configuration values, this is not possible today. Instead, they would be required handle protocol configuration entirely separate from the existing mechanisms. Fixing this issue would allow a DS develop to leverage the existing configuration mechanisms to support protocol-specific configuration values, perhaps via the use of another level of path in the configuration key naming.

**Comment by iain-anderson** [comment]
In the CSDK we have a "Driver" section in the configuration, and we pass its content as a collection of name-value pairs to the protocol driver in the init() callback.

**Comment by cloudxxx8** [comment]
@weichou1229 please work on this feature as @iain-anderson 's design after #159 merged
you should also apply the change to device-mqtt-go once this issue resolved
