### ISSUE TITLE
[V2] Return BaseResponse instead of empty EventResponse for PUT /device/name/{name}/{command}

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/device-sdk-go#787]
The current version of device-sdk-go will return empty EventResponse for PUT /device/name/{name}/{command}; which is contradict with https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/device-sdk/2.x#/default/put_device_name__name___command_.  After discussion with @cloudxxx8 , BaseResponse should be the proper response for PUT /device/name/{name}/{command}

**Comment by hahattan** [comment]
found out that I've done this already:
https://github.com/edgexfoundry/device-sdk-go/blob/6125dba09cfc805438589ab7aad954d8cad7589e/internal/v2/controller/http/command.go#L57-L62

wondering do we need to put requestId and message or leave it empty ?

**Comment by cloudxxx8** [comment]
No, requestId should be the same as the one in the request.
message is empty if the return code means successful. it normally for the error message.

**Comment by hahattan** [comment]
device command doesn't have requestId in its request body, should we use correlationId instead ?

**Comment by cloudxxx8** [comment]
no, they are different, and we should always add correlationId into header.
we don't have to assign requestId for now.  we might need to refactor the command request.
let's close this issue for now.
