### ISSUE TITLE
Implement the ping endpoint

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#8]
Implement the ping endpoint, and ensure that if the consul/registry is enabled, the ping endpoint is specified when registering as a service.

Estimated effort: 1d

**Comment by jduranf** [comment]
Ping endpoint is already implemented in the same way is implemented in other EdgeX go services. What should be done in this issue?

**Comment by cloudxxx8** [comment]
confirmed Ping endpoint implemented and verified work as expected.
closed this issue.
