### ISSUE TITLE
make the internal schedule and schedule event can be managed dynamically

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#80]
the current design and implementation of internal scheduler mechanism can only run the pre-defined schedule event.  To make it can be managed at run time, we could allow callback of schedule event CRUD or periodically re-load all schedule event by service name from Core Metadata

**Comment by tonyespy** [comment]
I think with our new AutoEvent design, this isn't really relevant anymore as if a device was changed in metadata, the existing callback should pickup the change to AutoEvent?

**Comment by tonyespy** [comment]
Closing this out, as it has no meaning in the new AutoEvent model.
