### ISSUE TITLE
data transformation on reading value

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-sdk-go#807]
In [device service requirement](https://wiki.edgexfoundry.org/display/FA/Device+and+Device+SDK+Working+Group?preview=/329488/46760195/edgex-device-service-requirements-v11.pdf), Data transformation section it stated that :

> Note that shift and mask operations apply only to uint* types, and should not be used together with base, scale, offset.

What if the user define all 5 transformation parameters and the ValueType fits the transformation requirement ?

Is there a priority between the bit-wise operation(mask, shift) and numeric operation (base, scale, offset) ?

For example we only perform the bit-wise transformations and skip the others ?

**Comment by cloudxxx8** [comment]
@tonyespy @iain-anderson could you please help clarify the behavior here?  thanks.

**Comment by iain-anderson** [comment]
The "don't use together" language is dropped in the ADR.
https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md
So if all transforms are specified and the type is ok, we can perform all of them.
I'll update the wiki to point at the ADR

**Comment by hahattan** [comment]
@iain-anderson besides overflow, do we need to check if transformed value changed its type ?
for example:
1. int8 reading value 10 with scale set to "1.2345" => 12.345, which becomes a float value
2. int8 reading value -2 with base set to "2" => 0.25, which becomes a float value

**Comment by iain-anderson** [comment]
In the first case I think setting a float value for scale where the reading type is int, is an error
In the second case it rounds to 0

**Comment by cloudxxx8** [comment]
@hahattan please see this document
https://docs.edgexfoundry.org/1.3/examples/Ch-ExamplesModbusdatatypeconversion/

We have resolved this case by the new attribute "rawType" in device modbus.
We currently don’t have a general solution in SDK, but this can be resolved in the Device Service level.

**Comment by hahattan** [comment]
@iain-anderson I'm implementing mask/shift operation on set command and needs some clarification:
the formula in the adr is `new-value = (current-value & !mask) | request-value`
How do we get the current value of the requested device resource in SDK ?

**Comment by iain-anderson** [comment]
Hi Chris,
What I've done in C is add a `mask` field to the command request structure and leave it to the driver to perform the calculation. I actually pass ~mask so the requirement for the driver is `new-value = (current-value & mask) | request-value` - which only needs to be performed if mask is nonzero.
I'm not sure if anyone has actually implemented this, it will probably end up being done if and when a use case arises

**Comment by iain-anderson** [comment]
The alternative would be to make a call to HandleReadCommands to get the current value. My thinking is that the driver will be able to handle the locking requirement (the resource must be locked between the read and the write) more efficiently than doing it in the SDK. We can look at this again if we get real uses and implementations.

**Comment by hahattan** [comment]
The first method sounds more reasonable to me.
I'll keep what it is right now (ignore the `shift`/`mask` for set command) and like you said maybe we come back to this again if a real use case arises.

**Comment by hahattan** [comment]
Current implementation in summary:

numeric transformation (scale/base/offset): allow float value, but will check if the transformed value is the same type with original one. Also checks overflow error.
bit-wise transformation (mask/offset): the value type needs to be the same as original DeviceResource(unsigned integer). Will not check overflow error.
