### ISSUE TITLE
Device OperatingState should be recovered when Assertion passed

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#828]
Currently, we modify Device OperatingState to down if the Assertion failed.
According to the user feedback, we should recover the OperatingState to up if the new value passed the Assertion
https://edgexfoundry.slack.com/archives/CE4KJ5VV2/p1615486753098600?thread_ts=1614784173.077200&cid=CE4KJ5VV2

**Comment by cloudxxx8** [comment]
@iain-anderson do you agree with this change request?

**Comment by iain-anderson** [comment]
If Operating State is down, autoevents will stop and /api/v2/device requests will be blocked.
We could do something on the Async channel? If an event is posted to it we could check OperatingState and if it's down, change it to up (unless the assert fails again)

**Comment by cloudxxx8** [comment]
I thought we should stop communicating the Device when adminState is Lock.
OperatingState is Down means the Device is not working, but should we keep talking to it until it starts working again, and modify the OperatingState back to Up?  AutoEvent could keep running.

**Comment by iain-anderson** [comment]
We could do that, and make OperatingState purely informational, but at the moment it's specified to deny access (ADR0011)

**Comment by cloudxxx8** [comment]
I would like to bring up this topic in the WG meeting.
Furthermore, if assertion accepts regular expression, it would be more useful.

**Comment by jpwhitemn** [comment]
Per Device Service WG meeting of 3/22:  if the assertion trips and sets the opState to down, then it requires human
intervention to reset the opState back to up and to allow the device to send data again - which is by design.
[Use Patch device on metadata ](https://app.swaggerhub.com/apis/EdgeXFoundry1/core-metadata/2.x#/default/patch_device) to reset the opState

**Comment by raycola** [comment]
Hi @jpwhitemn I agree with you, but consider that if resource assertion attribute could accept regular expression would be more useful as enhancement. 
Thanks

**Comment by cloudxxx8** [comment]
I just opened https://github.com/edgexfoundry/device-sdk-go/issues/839 for discussing regular expression support in the future.
