### ISSUE TITLE
make the interval configurable in clients initialization when monitoring registry

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#83]
The current implementation of clients/init.go:

```
	params := types.EndpointParams{
		UseRegistry: isUG,
		Interval:    15,
	}
```
The interval should be configurable.

**Comment by tonyespy** [comment]
@cloudxxx8 what is this interval used for? This sounds like an enhancement, not a bug?

**Comment by cloudxxx8** [comment]
yes, it is an enhancement
it is about how long to check the endpoints URL registered in Consul

**Comment by tsconn23** [comment]
I agree this should be done. It's probably low priority though since the real value from this won't be realized until we do an HA/Cloud type of deployment. When you're deploying one instance of a given service that isn't scaling you always know where the endpoint is.

**Comment by cloudxxx8** [comment]
we are removing client monitoring
