### ISSUE TITLE
Integrate Edinburgh Config format with Consul

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#85]

**Comment by cloudxxx8** [comment]
"Service/StartupMsg" in their configuration where we have  "Service/OpenMsg". We should change to make it consistent.

**Comment by tonyespy** [comment]
As there's an even newer proposal for configuration for Edinburgh (confusingly title EdgeX-Config-Proposal-v2), we should make sure a pointer to this new proposal gets added once it's been posted on the wiki.

**Comment by tonyespy** [comment]
@cloudxxx8 Is this still a valid issue?

**Comment by cloudxxx8** [comment]
yes, it is still valid.  I should put some configuration under "Writable", such as logging level

**Comment by tsconn23** [comment]
Please note that the most recent spec for how Consul configuration should be structured is located at the bottom of this page:
https://wiki.edgexfoundry.org/display/FA/Architecture+Issues+and+Decisions

**Comment by lenny-intel** [comment]
@cloudxxx8, @tonyespy , @tsconn23 , I can handle this as part of my integration with the new Abstract Register, i.e. issue #159. I already have it 90% complete with the stem set properly per link above. Would just need to add the Writeable section for logging.

**Comment by lenny-intel** [comment]
PR #186 addressed this issue.
