### ISSUE TITLE
v2: "Overwrite" for Profiles/Devices Loaded From Disk

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/device-sdk-go#869]
Currently if you are loading profiles or devices from disk, the SDK will favor what is already stored in metadata.

I think it might be worth adding the ability to overwrite these with what is in the local files - similar to the "--overwrite" flag that is passed for the config provider.  I would actually propose using the same flag, and I think it would keep with the way it behaves for the config provider to clear and rebuild the device/profile lists in metadata each time the service starts.  This would make the most sense for the majority of "--overwrite" use cases that I can think of.

**Comment by iain-anderson** [comment]
Discussed at the device WG meeting 12th April, the view taken was that edgex-cli is a more flexible way of managing metadata (and does not require device service reboots). Moving this to icebox for now.

**Comment by AlexCuse** [comment]
Agreed on the CLI.  The main thing we use --overwrite for is to ensure any changed configuration that is built into a container is updated in the config provider after a docker pull.  I think it would be nice to be able to do the same for any metadata that is defined with the service and may have been updated without needing to do anything "custom".  

Long way to say I may take a crack at implementing this - any thoughts on if it would make more sense to approach it via --overwrite flag or a new one (or a new config setting)?
