### ISSUE TITLE
Handle the value when there's no mapping found for a reading

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#89]
The issue is that mapping values exist for the ValueProperty, however the reading from the ProtocolDriver doesn't match any of the mapping values.

It's unclear if this is an error or not (i.e. should a error or warning be logged)?

@trcox could you comment on this?

**Comment by cloudxxx8** [comment]
For now, I keep the value as is for both read and write operation and log a warning when there is no matched mapping for a value.

**Comment by tonyespy** [comment]
So should issue be closed as "invalid"?

**Comment by tonyespy** [comment]
After some discussion, we agree that the code shouldn't log a warning when there's no mapping for a reading.

**Comment by hahattan** [comment]
I came across this issue while implementing v2 API. Currently the warning log still exist, if I remove it(according to tony's comment above) then the behavior would be like omit the situation which mapping cannot be found.
https://github.com/edgexfoundry/device-sdk-go/blob/0cafa7decaaa0dab3b86f836c2c615e8e839d11b/internal/handler/command.go#L180-L188

**Comment by cloudxxx8** [comment]
@tonyespy @iain-anderson should we remove the warning for the mapping not found or do anything for V2?
I thought this issue is "won't fix" in V1

**Comment by iain-anderson** [comment]
The warning should be removed, but it's low priority. If there's new code for V2, that should not include the warning.
