### ISSUE TITLE
Add public Service methods to remove or update Devices

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#9]
Top-level Service methods should be added to allow device service implementations to dynamically update or remove devices. The operations result in changes to Core Metadata in addition to the device service's local Device objects.

A top-level [AddDevice](https://github.com/edgexfoundry/device-sdk-go/blob/master/devices.go#L69) Service method already exists.

**Estimated effort**: 3-4d

**Comment by weichou1229** [comment]
@tonyespy I'm working on this issue.

**Comment by cloudxxx8** [comment]
fixed by #74
