### ISSUE TITLE
Add Event Tagging capability

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#915]
In the documentation about Event Tagging
https://docs.edgexfoundry.org/1.3/microservices/general/

> For example, a device service could populate the Tags property with latitude and longitude key/value pairs of the physical location of the sensor when the Event is created to send sensed information to Core Data.

However, we don't provide any Event Tagging mechanism in the SDK.

My proposal is to add Tags field in the CommandValue model.
https://github.com/edgexfoundry/device-sdk-go/blob/6cc4c25230d964bbb6ccd74e42769d1c7a10d9be/pkg/models/commandvalue.go

Then, SDK could the Tags to Event when it is making AddEventDTO.

**Comment by lenny-intel** [comment]
> My proposal is to add Tags field in the CommandValue model.

I agree with this proposal which allows the flexibility for individual device service to add Tags dynamically as their use case requires. 
Do we also want to provide a way to add tags via configuration?

**Comment by jpwhitemn** [comment]
Need to get this done for Ireland to avoid API change for SDK Go.  With C SDK - may get done in Ireland but can avoid API change in this instance.  Per Core WG 5/13/21
