### ISSUE TITLE
CORS support for REST APIs

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/device-sdk-go#916]
Trying to make API calls to device services via common web-browsers fails due to lack of CORS support.

For example:
- A webserver running on `http://localhost:48086` presents the user with a `Discover` button.
- When the user clicks that button, an AJAX call is made to `POST http://localhost:49989/api/v1/discovery`.
- It fails with the following error:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:49989/api/v1/discovery. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

[Learn More](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)

**Comment by lenny-intel** [comment]
Example utility for CORS from Intel reference implementation
https://github.com/intel-iot-devkit/automated-checkout-utilities/blob/0dd0e1e344399f3042b1f64b82ccbc2d2e0333aa/utilities.go#L69

We might be able to handle this in the middleware for REST

**Comment by iain-anderson** [comment]
Issue in edgex-go: https://github.com/edgexfoundry/edgex-go/issues/1913

**Comment by iain-anderson** [comment]
Targeted for Jakarta at Core WG 13th May

**Comment by jpwhitemn** [comment]
Discussed in Core WG meeting 5/13/21.  To be done for Jakarta release.  Looking at whether there is common code (such as in bootstrapping) or if this needs to be added to edgex-go, SDKs (and associated services) separately as part of the request handling process.

**Comment by lenny-intel** [comment]
@iain-anderson , we have an issue for Security WG that is taking care of this when in secure mode. Should we close this one?

**Comment by bnevis-i** [comment]
@lenny-intel @iain-anderson We need an update on this now that we have CORS support for core-command microservice.

**Comment by lenny-intel** [comment]
This has been addressed by:

https://github.com/edgexfoundry/go-mod-bootstrap/pull/286
https://github.com/edgexfoundry/go-mod-bootstrap/pull/288
https://github.com/edgexfoundry/go-mod-bootstrap/pull/290
