### ISSUE TITLE
The initial profile slice size in cache should not the same as device slice

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#93]
in internal/cache/init.go:

```
		}
		newDeviceCache(ds)
 		dps := make([]models.DeviceProfile, len(ds))
```

The size of profile slice might not be the same as device slice

**Comment by cloudxxx8** [comment]
@tonyespy How about creating a default slice and append it for each Device Profile?

```
dps := make([]models.DeviceProfile, 0)
for _, d := range ds {
	dps = append(dps, d.Profile)
}
newProfileCache(dps)
```

**Comment by cloudxxx8** [comment]
The total number of DeviceProfile is definitely less than the number of Device.  The code create a slice of DeviceProfile we are using here, although some of the DeviceProfile might be the same.  We could filter the duplicated ones in the cache creation.

```
func newProfileCache(profiles []models.DeviceProfile) ProfileCache {
	defaultSize := len(profiles) * 2
	dpMap := make(map[string]models.DeviceProfile, defaultSize)
	nameMap := make(map[string]string, defaultSize)
	doMap := make(map[string]map[string]models.DeviceObject, defaultSize)
	getOpMap := make(map[string]map[string][]models.ResourceOperation, defaultSize)
	setOpMap := make(map[string]map[string][]models.ResourceOperation, defaultSize)
	cmdMap := make(map[string]map[string]models.Command, defaultSize)
	for _, dp := range profiles {
		if _, ok := dpMap[dp.Name]; ok {
			continue
		}
		dpMap[dp.Name] = dp
		nameMap[dp.Id.Hex()] = dp.Name
		doMap[dp.Name] = deviceObjectSliceToMap(dp.DeviceResources)
		getOpMap[dp.Name], setOpMap[dp.Name] = profileResourceSliceToMaps(dp.Resources)
		cmdMap[dp.Name] = commandSliceToMap(dp.Commands)
	}
	pc = &profileCache{dpMap: dpMap, nameMap: nameMap, doMap: doMap, getOpMap: getOpMap, setOpMap: setOpMap, cmdMap: cmdMap}
	return pc
}
```

**Comment by tonyespy** [comment]
The ValueDescriptor and Device caches both query Core Metadata first, and use the size of the returned slices to set the initial cache size. I think we should just do the same for Profiles cache. Either way, I would categorize this as low priority.

**Comment by tonyespy** [comment]
After discussion, we should just use the default size when creating this slice.

**Comment by cloudxxx8** [comment]
we have used the default map size in v2 as we discussed
https://github.com/edgexfoundry/device-sdk-go/blob/d47b03cf12e2f169eefdaad978a8d5668b399891/internal/v2/cache/init.go#L26

close this issue
