### ISSUE TITLE
Support JSON profile provision in V2

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#954]
Also parse .json in the profile folder when the service starts up
C SDK has supported it

**Comment by hahattan** [comment]
We already supported it:
https://github.com/edgexfoundry/device-sdk-go/blob/93abf715a89b706c53091008ba2aa1c6f00d3b1a/internal/provision/devices.go#L68-L78

**Comment by cloudxxx8** [comment]
it is for device, and we need the same for device profile.
we haven't supported it
https://github.com/edgexfoundry/device-sdk-go/blob/93abf715a89b706c53091008ba2aa1c6f00d3b1a/internal/provision/profiles.go#L57
