### ISSUE TITLE
Remove Core Data dependency from Device Service

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#964]
Device Services check whether core-data is alive when they are starting up.
After eliminating Value Descriptors and implementing Message Bus, core-data is no longer a necessary dependency.
We should remove the dependency check in V2.

**Comment by lenny-intel** [comment]
POSTing events to Core Data is still a supported configuration, so don't think we should have removed this dependency check.

**Comment by cloudxxx8** [comment]
@lenny-intel it's not a hard dependency.  We made this dependency for ValueDescriptor cache initialization.
If core-data is not available, users might just encounter Event pushing error. Device Services can live without core-data.
Furthermore, if the user want to eliminate core-data from the system, all the Device Services will be blocked by the core-data dependency check.
