### ISSUE TITLE
Device service got crash when failing to get credential from vault

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/device-sdk-go#974]
See the following logs.
```
level=INFO ts=2021-06-18T03:18:20.842795376Z app=device-modbus source=messaging.go:69 msg="Setting options for secure MessageBus with AuthMode='usernamepassword' and SecretName='redisdb"
level=ERROR ts=2021-06-18T03:18:20.843605932Z app=device-modbus source=messaging.go:48 msg="Unable to get Secret Data for secure message bus: Error found on handling secrets from underlying data-store: Received a '404' response from the secret store"
level=INFO ts=2021-06-18T03:18:20.843625277Z app=device-modbus source=secrets.go:285 msg="context cancelled, dismiss the token renewal process"
level=INFO ts=2021-06-18T03:18:20.843636447Z app=device-modbus source=httpserver.go:109 msg="Web server shutting down"

```

**Comment by cloudxxx8** [comment]
The Device Service should not shutdown directly.

**Comment by lenny-intel** [comment]
@cloudxxx8 , this is on start up to connect to the Secure MessageBus, so IMO it should shutdown.

**Comment by cloudxxx8** [comment]
@lenny-intel We have secret setup service to initialize the credential of Redis in Vault.
However, if the user want to use an external MQTT broker with security credentials, they have to:

1. start up the Device Service
2. store the credentials via /secret API from the Device Service (https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/device-sdk/2.x#/default/post_secret)

If the service shuts down in the very beginning, the /secret API would be useless, and the user is hard to push the credentials.
The secure connection should be able to established when the Device Service needs to connect to the Message Bus, not at the start up time.

**Comment by lenny-intel** [comment]
@cloudxxx8 , that doesn't apply to the `known` secrets such as the `redisdb` which Secret Store takes care of adding to the services Secret Store via the ADD_KNOWN_SECRETS environment variable.

Example from default secure compose file.
```
ADD_KNOWN_SECRETS: redisdb[app-rules-engine],redisdb[device-rest],redisdb[device-virtual]
```
The Compose Builder will add `device-mqtt` to this list when using the command `make gen ds-mqtt` to generate a custom compose file with just Device MQTT.

**Comment by cloudxxx8** [comment]
Got it, closing this issue
