### ISSUE TITLE
AutoEvents won't stop until restart 

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/device-sdk-go#980]
In the recent V2 release, by sending 
```
{
...
"autoEvents":[]
}
```

to core-metadata can delete autoEvents in device, but autoEvents won't stop until I restart the device service, any thing changed in the V2 implementation?

_Originally posted by @novuscy in https://github.com/edgexfoundry/device-sdk-go/issues/508#issuecomment-866661057_

**Comment by novuscy** [comment]
the updateDeviceRequest in the UpdateDevice function of callback.go seems right, but device after requests.ReplaceDeviceModelFieldsWithDTO(&device, updateDeviceRequest.Device) seems wrong, maybe it's a caching problem?

**Comment by hahattan** [comment]
> the updateDeviceRequest in the UpdateDevice function of callback.go seems right, but device after requests.ReplaceDeviceModelFieldsWithDTO(&device, updateDeviceRequest.Device) seems wrong, maybe it's a caching problem?

Not sure why the `updateDeviceRequest.Device.AutoEvents` became nil when we received it in SDK (It was an initialized empty slice when sending from metadata)

**Comment by cloudxxx8** [comment]
it is caused by the `omitempty` tag in the UpdateXXX DTO.
we should remove all of them.

**Comment by cloudxxx8** [comment]
related to https://github.com/edgexfoundry/go-mod-core-contracts/issues/638

**Comment by lenny-intel** [comment]
@cloudxxx8 , @hahattan , will you be able to make all the needed changes to go-mod-core-contracts before we need to release it tomorrow morning (our time)

**Comment by jpwhitemn** [comment]
Per planning meeting of 6/24/21, this issue should be closed as it was taken care of with the core contracts fix (https://github.com/edgexfoundry/go-mod-core-contracts/issues/638).
