### ISSUE TITLE
Error message showed up when upgraded to latest dev.86

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/device-sdk-go#987]
I'm running the device services which use 2.0.0-dev.86 version SDK, without Consul config provider, just local config file, and an error message show up when booting up:

```
level=ERROR ts=2021-06-25T08:09:24.477479703Z app=device-modbus source=service.go:220 msg="failed to update device service device-modbus with local config: request failed, status code: 400, err: {\"apiVersion\":\"v2\",\"message\":\"device service json decoding failed\",\"statusCode\":400}\n"
```

and an error message of core-metadata:
```
level=ERROR ts=2021-06-25T08:09:24.477363806Z app=core-metadata source=http.go:38 X-Correlation-ID=a967786a-a104-445a-b49e-2b21dbfa08b0 msg="device service json decoding failed -> UpdateDeviceServiceRequest.Service.Id field needs a uuid"
```
The device service works fine, but the message is annoying.
Maybe something wrong with the latest go-mod-contract update?

#980

**Comment by cloudxxx8** [comment]
Thanks for reporting this bug
The long term solution is https://github.com/edgexfoundry/go-mod-core-contracts/issues/640
We will make a workaround in device-sdk-go by today

**Comment by cloudxxx8** [comment]
@weichou1229 please assign the id to nil in UpdateDTO before sending out the request
for example, before this line:
https://github.com/edgexfoundry/device-sdk-go/blob/5b9873fc5658fb4b4c48b057788cd55a404aa657/pkg/service/service.go#L218
