### ISSUE TITLE
How to pass in the parameters when get request?

### ISSUE THREAD

**Issue by Haoyuli1990** [edgexfoundry/device-sdk-go#999]
Edgex 2.0 support pass in the parameters when get request?

**Comment by cloudxxx8** [comment]
It only support query parameters, not from body.
It will be in the Attributes field of CommandRequest
https://github.com/edgexfoundry/device-sdk-go/blob/b8bde01b3040ded824082163a6ece586529576f1/pkg/models/commandrequest.go#L15

**Comment by Haoyuli1990** [comment]
ok, get it!
